### ISSUE TITLE
blacklist isnt working

### ISSUE THREAD

**Issue by gaylordfoker** [SoliaRdi/auto-fishing#100]
all bafs in blacklist, doesnt matter, mod makes fishsalat

**Comment by SoliaRdi** [comment]
already fixed hour ago. Or error remains even after update?

**Comment by gaylordfoker** [comment]
yes still bugged and bait 1 doesnt work for autocraft.

**Comment by SoliaRdi** [comment]
try again with restart. For debug print /8 fish debug

**Comment by gaylordfoker** [comment]
yes, restarted all already. what you mean restart game or proxy?

**Comment by SoliaRdi** [comment]
Proxy ofc

**Comment by gaylordfoker** [comment]
nope, still getting fish salat

**Comment by SoliaRdi** [comment]
maybe dismantle, or you craft fish salat?

**Comment by gaylordfoker** [comment]
ok i made a mistake is working now, thx
