### ISSUE TITLE
Doesn't craft bait.

### ISSUE THREAD

**Issue by kinsyu** [SoliaRdi/auto-fishing#101]
I used fish setrecipe and after I run out of baits it doesn't craft.

**Comment by SoliaRdi** [comment]
I added some min ago fix for this issue. Try again

**Comment by kinsyu** [comment]
It crafts now, but only 10. Also if I have another sort of bait, like the new worms, it uses those. thanks!

**Comment by SoliaRdi** [comment]
Its new feature :D
