### ISSUE TITLE
AutoSell doesn't work

### ISSUE THREAD

**Issue by flytomoon88** [SoliaRdi/auto-fishing#103]
Hi,
after updating to the newest version in patch 80, the autosell got stuck, fish can add to basket automatically but will not autosell to NPC, need manual pressing.
can you please take a look?
thanks!

**Comment by SoliaRdi** [comment]
Region?

**Comment by flytomoon88** [comment]
SEA, I mapped all the opcodes already

**Comment by SoliaRdi** [comment]
Can you check C_STORE_COMMIT via logger? It should look like this(npc is contract id)
![image](https://user-images.githubusercontent.com/34610562/55286129-3e809e00-53a0-11e9-9942-3a10b3b19e37.png)

**Comment by flytomoon88** [comment]
[11:51:38:391] -> [CRAFTED]	 C_STORE_COMMIT    (id 41490)
{
    "gameId": "140737488441614",
    "contract": 0
}
00000004: 0E510100 00800000 00000000                                               .Q..........

100012a20e5101000080000000000000
[11:51:38:889] ->          	 C_STORE_COMMIT    (id 41490)
{
    "gameId": "140737488441614",
    "contract": 773147
}

**Comment by flytomoon88** [comment]
no npcid like yours, but the fish can be put on the basket with the NPC

**Comment by SoliaRdi** [comment]
Well, def file from another mod. His def more accurate. But too many ppls downloaded mine. Idk what to do with this :D

**Comment by flytomoon88** [comment]
so i just overwrite the def from the MOD here, then prob should be solved?

**Comment by SoliaRdi** [comment]
Yes

**Comment by flytomoon88** [comment]
ok thanks!
your mod is nice A_A

**Comment by SoliaRdi** [comment]
Ok,might be fixed even with other def
