### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by teraoo** [SoliaRdi/auto-fishing#104]
![f](https://user-images.githubusercontent.com/40299748/55286706-ac789580-539f-11e9-83b5-cf8da6ee9125.JPG)

**Comment by SoliaRdi** [comment]
See warning

**Comment by teraoo** [comment]
why unsupoorted  since today? yesterday working fine

**Comment by SoliaRdi** [comment]
I rewrote the module. Now support only caali proxy
