### ISSUE TITLE
how to add auto negotiation

### ISSUE THREAD

**Issue by nilsii** [SoliaRdi/auto-fishing#106]
Hi, I read that you don't have a plan to add auto negotiation, so I was just trying to add it and try to make it work, I don't have much programming experience, I only had small experiences and many years ago, I wanted to ask you can you tell me what i should do to add it and make it work? it's complicated? with a lot of patience can I do it? is there any guide where I can read and learn? sorry for the many questions and for my bad english

**Comment by SoliaRdi** [comment]
It based on your programming level and ofc it possible. Sorry, but I'm not interested in providing such info and writing walls of text
