### ISSUE TITLE
Dismantling issues

### ISSUE THREAD

**Issue by mikaxsus** [SoliaRdi/auto-fishing#107]
Dismantling window doesn't get filled with fish, closes itself and opens up again, repeating the process an indefinite amount of times.

**Comment by SoliaRdi** [comment]
Give me additional info. I have not encountered such problem

**Comment by mikaxsus** [comment]
It's weird. I let an acc fish for a while, and nothing happens. But now when I got back, it tries to add something to the dismantling window, but it keeps saying "The item cannot be dismantled". Maybe the crit baits (worms) being used interferes with it?

**Comment by SoliaRdi** [comment]
Added checks for no fishes. Try to fish with debug enabled next time

**Comment by mikaxsus** [comment]
I'll test it, and yeah rip, I didn't turn it on. I'll have it on for a test now.

**Comment by mikaxsus** [comment]
UPDATE: It's happening currently. Debug is on, it's repeating "Decision dismantle" and "This item cannot be dismantled." keeps repeating. Inventory is filled with fish fished from this session (clean session, removed fish used from previous session). "debug, selltonpc 6 and setrecipe" are turned on.

**Comment by SoliaRdi** [comment]
So another question. How many filets do you have rn?

**Comment by mikaxsus** [comment]
51 fillets, 45 bait t3, 10 blue worms

**Comment by SoliaRdi** [comment]
Give me module list, idk how this error pops up. Last time I seen this months ago

**Comment by mikaxsus** [comment]
![image](https://user-images.githubusercontent.com/45637893/55292878-30f30480-53f0-11e9-9feb-8b07fff14551.png)

**Comment by SoliaRdi** [comment]
Well, still no ideas. You can try fishing without others modules or wait someone else with such problem. What region btw?

**Comment by SoliaRdi** [comment]
Another way is enable packet logger when this situation will happen soon

**Comment by mikaxsus** [comment]
EU, and yeah I'll try that now. I know, it's weird, I can't think of any module that interferes with it. Oh, I can now, it's inventory is still full for testing.

**Comment by mikaxsus** [comment]
[logc_logs.txt](https://github.com/SoliaRdi/auto-fishing/files/3026991/logc_logs.txt)

Here you go, client and server logged.

**Comment by mikaxsus** [comment]
It's with client/server logging on and all previous mods on.

**Comment by SoliaRdi** [comment]
[20:16:38:306] -> [CRAFTED]      C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT (id 22773)
{
    "contract": 2107909,
    "dbid": "257866691",
    "id": 0,
    "count": 0
}

**Comment by SoliaRdi** [comment]
wrong defs

**Comment by SoliaRdi** [comment]
(They correct, but fields named differently from mine)

**Comment by mikaxsus** [comment]
Ha, I know why. Your naming convention is different from tera-data's, I'm using the original ones from the first bot KTC got out.

**Comment by SoliaRdi** [comment]
official tera-data's dont have such def =)
