### ISSUE TITLE
No one sent NA Op codes?

### ISSUE THREAD

**Issue by Maaia** [SoliaRdi/auto-fishing#108]
Still no NA Opcodes? I've never done it before but I can try.. Just don't know how to use the logger/sniffer.

**Comment by SoliaRdi** [comment]
Nope, no one send me them

**Comment by MeongMeongMeong** [comment]
NA got new Opcodes? i checked its still the same

**Comment by tsunpot** [comment]
which opcodes are you looking for?

**Comment by Maaia** [comment]
All NA ones. @MeongMeongMeong says theyre the same though.. but after the Kaali proxy update last week it doesnt work for me anymore.

**Comment by tsunpot** [comment]
I need to know which ones specifically, I have a working version but I have too many extra opcodes to dift through

**Comment by Maaia** [comment]
Hmm.. not sure what I did but it seems to be working now.
When I tried earlier, bait wasn't equipping, and START_FISHING_MINIGAME wasnt happening when Bite happened. but seems to be working now.

**Comment by tsunpot** [comment]
you just saved me a lot of time from typing all these opcodes. godbless
