### ISSUE TITLE
Error dismantling

### ISSUE THREAD

**Issue by romainsim** [SoliaRdi/auto-fishing#11]
Hello, i have this error when it tries to dismantle my fish ! 
It adds 20 fishs in the tab, but it doesn't dismantle ...
![error](https://user-images.githubusercontent.com/23208734/50056033-f8882d00-0156-11e9-99d6-956635139525.png)

**Comment by SoliaRdi** [comment]
contract id cannot be undefined, idk. I dont have this issue
