### ISSUE TITLE
SEA OPCODES HERE

### ISSUE THREAD

**Issue by edhe15** [SoliaRdi/auto-fishing#110]
C_STORE_COMMIT = 41490
S_FISHING_CATCH_FAIL = 26569
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 53131
C_START_FISHING_MINIGAME = 58013
S_FISHING_BITE = 29236
S_FISHING_CATCH = 61637
S_STORE_BASKET = 53098
C_STORE_SELL_ADD_BASKET = 60107
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 46411
S_START_FISHING_MINIGAME = 57576
C_PUT_WARE_ITEM = 50576
C_END_FISHING_MINIGAME = 50168
-------------------------------------------------------------------------------
@SoliaRdi U can post it. i dont know how to sent to u.
Oya... Im keep watching what people post, and try it again. What i got, sometime the  id is diffrent.
![a](https://user-images.githubusercontent.com/48638947/55297615-2701ed80-5452-11e9-9dbf-a1be93fd5139.jpg)

*C_STORE_COMMIT and S_STORE_BASKET, Both of this id is really hard to find using Alex. but when u got it, its wrong opcode.
I Got this id my last try. C_STORE_COMMIT = 32143

*Sometime u got  right C_STORE_SELL_ADD_BASKET but with wrong S_STORE_BASKET. Thats why some ppl asked to u about auto sell not work

*Another problem is, if u use fpi with lowercase and mod dsn't work/ find id ur looking for, u need to use FPI uppercase.

**Comment by SoliaRdi** [comment]
:ok_hand:
