### ISSUE TITLE
Pls add Auto Buy Bait I

### ISSUE THREAD

**Issue by Zonq677** [SoliaRdi/auto-fishing#113]
Hi SoliaRdi ;

Fishing give the exp , very good afk exp farm method is fishing but , 65 and low levels not read Bait Recipe ,

do you add the auto buy Bait I ?

very good tactic earn money and exp

Thanks for module and support ,

we love you bro.

**Comment by SoliaRdi** [comment]
Bait recipe for 20% and 40% can be learned from 1st lvl

**Comment by Zonq677** [comment]
no bro :( , all recipe design for level  65 or above

image : https://i.ibb.co/ySnv45S/bait.png

**Comment by SoliaRdi** [comment]
Did they change this in last patch?

**Comment by SoliaRdi** [comment]
Wait ru update

**Comment by Zonq677** [comment]
Ru ? 
sorry i dont understand :(

**Comment by SoliaRdi** [comment]
In 2-4 days

**Comment by SoliaRdi** [comment]
wont add for some reasons, maybe i change my decision over time. :frowning:

**Comment by Zonq677** [comment]
Why ? :(
