### ISSUE TITLE
Fish only lv 0 - lv 2 fish

### ISSUE THREAD

**Issue by flytomoon88** [SoliaRdi/auto-fishing#115]
Hi,
SEA sever, the auto fish can only fish lv0-lv2 fish even fish rod is Tier 4 with fish bait  III.
if i start the fishing after i throw rod manually, it will fish the corresponding level of fish as per the fish rod.  However after the first fish done, the next fish become lv 0 - lv 2 fish.
can you please check why?

**Comment by SoliaRdi** [comment]
You have old rod in inv

**Comment by flytomoon88** [comment]
thanks!! haha.
