### ISSUE TITLE
Sell fish

### ISSUE THREAD

**Issue by ferskoer** [SoliaRdi/auto-fishing#116]
when I stand with fish merchants, he writes to me that they are not around and a wandering merchant will be used

**Comment by SoliaRdi** [comment]
I don't have such messages in mod🤔

**Comment by ferskoer** [comment]
https://pp.userapi.com/c855532/v855532623/16409/p3P-4qF9R-E.jpg
https://pp.userapi.com/c855636/v855636623/15d2d/X6hKUvze6UY.jpg

I'm standing near the NPS, and the module says that they are not there

**Comment by edhe15** [comment]
> https://pp.userapi.com/c855532/v855532623/16409/p3P-4qF9R-E.jpg
> https://pp.userapi.com/c855636/v855636623/15d2d/X6hKUvze6UY.jpg
> 
> I'm standing near the NPS, and the module says that they are not there

Move, and type again fish selltonpc <range to npc>
