### ISSUE TITLE
Filet not getting banked

### ISSUE THREAD

**Issue by Peckspas** [SoliaRdi/auto-fishing#117]
Hey i have a problem with banking filets. When i reach max filets it does not get put into the bank and stops fishing. 
My config is set to bank 5000 filets but its not doing it.
I have banker scroll in my inventory of course.

I used /fish debug "Decision toomanyfilets" after that it stops fishing. No bank npc spawn, no error in game and no error in proxy window. It just stops and i dont know why?

![1](https://user-images.githubusercontent.com/49212609/55438117-0ac09680-55a1-11e9-92c3-d758d72b4397.PNG)

**Comment by SoliaRdi** [comment]
Bug =(

**Comment by Peckspas** [comment]
Love you man ! It works perfect now. Thank you
