### ISSUE TITLE
GM checking afk fishers

### ISSUE THREAD

**Issue by xNeppy** [SoliaRdi/auto-fishing#118]
A GM on EU started to teleport people a few meters and see if they automatically keep fishing to detect if they use autofisher. So there has to be a feature that automatically stops fishing if you get teleported

**Comment by Distortionn** [comment]
This. There's an active GM checking on servers and certain slots for people who are actively afk fishing with the module. They will teleport you a few meters away and if they see you are still fishing after that, they'll most likely ban you.

So if there's a way you could implement a location check that when you get teleport, the module will just stop, that would be honestly amazing.

Thanks in advance already

**Comment by SoliaRdi** [comment]
Tbh, my mod always have clearAllTimeouts in S_LOAD_TOPO. If they tp you another way without loading(idk), then i made check for gm spawn

**Comment by trev44** [comment]
so what does this even mean.
should we just get a mod that notifies of nearby gm?

**Comment by SoliaRdi** [comment]
https://github.com/SoliaRdi/auto-fishing/blob/master/index.js#L425

**Comment by Owyn** [comment]
so any info whenever GMs teleport people few meters away with full location reloading using S_LOAD_TOPO or with priest-like pull skill which doesn't ?

**Comment by SoliaRdi** [comment]
Nope, i even dk if my gm detector ever triggered by someone =)
