### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by bircay** [SoliaRdi/auto-fishing#122]
Hello. There is no tera-data folder to put files in. Can u help me?
![sfe](https://user-images.githubusercontent.com/49292512/55591017-2a8cc180-573d-11e9-812b-21d472b633bc.png)

**Comment by SoliaRdi** [comment]
Did you launch proxy?

**Comment by bircay** [comment]
Yes. I am in game while proxy is open. And proxy is working properly

**Comment by bircay** [comment]
Ah it was in another folder, found it. sorry to bother u
