### ISSUE TITLE
GM Detecting people still.

### ISSUE THREAD

**Issue by Distortionn** [SoliaRdi/auto-fishing#124]
So apparently the GMs are still on a witch-hunt in EU. This time most likely checking out players who are getting a BAF (Superior/gold fish) and then people get an announcement on their screens in their area.

Is there a chance to let the module fail on gold/superior fishes (BAFs) and just skip those? So we won't get any announcements in our channel. That way they won't stalk us either. Just an extra safety precaution - Same goes for TERA whiteknights that might report when they see people fishing like this.

Thanks in advance!

**Comment by SoliaRdi** [comment]
👌
