### ISSUE TITLE
broken after update

### ISSUE THREAD

**Issue by Roxycodone** [SoliaRdi/auto-fishing#126]
ERROR: Error: [dispatch] hook: unmapped packet "S_FISHING_BITE"

**Comment by shinctl** [comment]
give the dev some time, updates has not been live for even 3 hours

**Comment by tsunpot** [comment]
need new opcodes for map 345886

**Comment by AntiScrewdriver** [comment]
Hello again friends ! =D

**Comment by Roxycodone** [comment]
> give the dev some time, updates has not been live for even 3 hours

Informing someone of an issue and complaining are two entirely different things.

**Comment by SoliaRdi** [comment]
![image](https://user-images.githubusercontent.com/34610562/55869980-4b677380-5b90-11e9-9add-e29da95f0756.png)
And why do people still play on NA :D

**Comment by QuestionableUser** [comment]
> ![image](https://user-images.githubusercontent.com/34610562/55869980-4b677380-5b90-11e9-9add-e29da95f0756.png)
> And why do people still play on NA :D

> `Na Protocol.345886
C_MEDAL_STORE_COMMIT = 55033
C_PUT_WARE_ITEM = 34988
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 44332
C_START_FISHING_MINIGAME = 37509
C_STORE_COMMIT = 29419
C_STORE_SELL_ADD_BASKET = 54153
C_END_FISHING_MINIGAME = 46506
C_RQ_START_SOCIAL_ON_PROGRESS_DECOMPOSITION = 549246
C_STORE_COMMIT = 29419
C_STORE_SELL_ADD_BASKET = 5415
C_STORE_COMMIT = 29419
C_CAST_FISHING_ROD = 45109
S_CAST_FISHING_ROD = 34965
S_FISHING_BITE = 27603
S_FISHING_CATCH = 27376
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 27482
S_START_FISHING_MINIGAME = 36415
S_STORE_BASKET = 24779`

**Comment by tsunpot** [comment]
can we also get S_MEDAL_STORE_BASKET?

**Comment by QuestionableUser** [comment]
> can we also get S_MEDAL_STORE_BASKET?

S_MEDAL_STORE_BASKET = 41478

**Comment by ChicknWing** [comment]
@QuestionableUser  can you help me with the op code for S_FISHING_CATCH_FAIL ? 

Also, which packet logger did you use to map these? I tried logging them myself but they never show up in the log file no matter what fishing actions I try to do.
I tried all these: 
https://github.com/Owyn/debug-logger/
https://github.com/Owyn/alex-packet-id-finder
https://github.com/SoliaRdi/PacketsLogger

**Comment by tsunpot** [comment]
@QuestionableUser do you also have C_MEDAL_STORE_BUY_ADD_BASKET?

**Comment by SoliaRdi** [comment]
S_FISHING_CATCH_FAIL not used anymore in my module

**Comment by QuestionableUser** [comment]
> _FISHING_CATCH_FA

S_FISHING_CATCH_FAIL = 59277

**Comment by QuestionableUser** [comment]
> @QuestionableUser do you also have C_MEDAL_STORE_BUY_ADD_BASKET as well as C_MEDAL_STORE_BUY_DEL_BASKET?

C_MEDAL_STORE_BUY_ADD_BASKET = 41593
C_MEDAL_STORE_BUY_DEL_BASKET = 37969
