### ISSUE TITLE
Can this mod work under low FPS ( virtual machine ) ? and another suggestion

### ISSUE THREAD

**Issue by zokiopp** [SoliaRdi/auto-fishing#127]
Can it work in low resources like in a Vmware virtual machine? 
Also, i would add a suggestion to add function to start skipping baf if they are 30 in inventory already. thanks. Or add random baf skipping of total 20% of all times.

**Comment by SoliaRdi** [comment]
I don't see any reason for adding this. On completely low(like 0fps) -no, due to way of throwing a fishing rod. And i won't change this here

**Comment by zokiopp** [comment]
Emulating more human like behavior is the objective of my post. Also, u can sell max 30 baf's a day for a good price. I tried running TERA on vmware, got like 1 fps for 1-2 seconds xD.

**Comment by SoliaRdi** [comment]
30 baf is almost 24h if lucky with regular bait. Module switches between dismantle and selling when needed
