### ISSUE TITLE
issues with sellscroll command

### ISSUE THREAD

**Issue by tsunpot** [SoliaRdi/auto-fishing#128]
with the sellscroll command active, it will open a merchant and get to item screen, but it wont select fish from inventory and place them into the sell box.

**Comment by MeongMeongMeong** [comment]
same with sell to NPC, it wont put fishes in the sell box, but if you manually put fishes in the sell box, it automatically sells.

**Comment by SoliaRdi** [comment]
Problem appeared after update? Region?

**Comment by MeongMeongMeong** [comment]
yes after update, NA region

**Comment by SoliaRdi** [comment]
Weird, i dont see such issues when update come to ru and eu. Dk, try check opcodes with module update

**Comment by QuestionableUser** [comment]
I'v never gotten the sell scroll to work tbh. assumed i was doing something wrong. 
possibly even the merchant ID scroll is different for NA then it is for RU/EU didn't bother looking into it. ]

SelltoNPC works just fine though so. /shurg.

**Comment by SoliaRdi** [comment]
Btw make sure that you dont have this line in your opcode file - C_STORE_SELL_ADD_BASKET = 5415

**Comment by MeongMeongMeong** [comment]
C_STORE_SELL_ADD_BASKET in the  updated op code is 45153, guess thats why it doesnt work. THX

**Comment by SoliaRdi** [comment]
?_? are you sure?

**Comment by MeongMeongMeong** [comment]
oh wait, sorry please ignore me, i read your previous reply wrongly xD

**Comment by Maaia** [comment]
Is 5415 the NA one? I have 45153 but im not sure if that was working or not,

**Comment by tsunpot** [comment]
5415 is incorrect

correct is C_STORE_SELL_ADD_BASKET = 54153

**Comment by Maaia** [comment]
Im not sure what I have wrong then .-. when it opens the store it doesnt move fish to basket.. but if i add all 8 fish manually to basket, it pushes "sell" automatically. Everything else working fine. @tsunpot @MeongMeongMeong 

C_MEDAL_STORE_COMMIT = 55033
C_PUT_WARE_ITEM = 34988
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 44332
C_START_FISHING_MINIGAME = 37509
C_STORE_COMMIT = 29419
C_STORE_SELL_ADD_BASKET = 54153
C_END_FISHING_MINIGAME = 46506
C_RQ_START_SOCIAL_ON_PROGRESS_DECOMPOSITION = 549246
C_STORE_COMMIT = 29419
C_STORE_SELL_ADD_BASKET = 45153
C_STORE_COMMIT = 29419
C_CAST_FISHING_ROD = 45109
S_CAST_FISHING_ROD = 34965
S_FISHING_BITE = 27603
S_FISHING_CATCH = 27376
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 27482
S_START_FISHING_MINIGAME = 36415
S_STORE_BASKET = 24779

**Comment by SoliaRdi** [comment]
I suggest you to not copy opcodes without any thoughts. User opcodes is always 5 digit number

**Comment by SoliaRdi** [comment]
You have 2 C_STORE_SELL_ADD_BASKET and second one override correct opcode
