### ISSUE TITLE
Skipbaf and Autosalad

### ISSUE THREAD

**Issue by Jenoside** [SoliaRdi/auto-fishing#129]
The skipbaf option does not work when using autosalad, probably due to the fact that fish salad lowers the tier of the fish.

**Comment by SoliaRdi** [comment]
Can you tell me baf level with salad? By /8 fish stats

**Comment by Jenoside** [comment]
It looks like it becomes tier 7
![Captu3434re](https://user-images.githubusercontent.com/49515578/55980329-8521a280-5c94-11e9-9386-92490805ae9e.PNG)

**Comment by SoliaRdi** [comment]
Should be fixed,dk about tier 10 fishes. If they have 7 lvl too, they would be skipped too

**Comment by Jenoside** [comment]
Tier 9 becomes tier 6, so I guess tier 10 becomes tier 7 too. So there would only be an issue if you have tier 8 rod.
