### ISSUE TITLE
Doenst catch grade 10 fish

### ISSUE THREAD

**Issue by Peckspas** [SoliaRdi/auto-fishing#131]
Hey i updated today and now it doesnt catch any grade 10 fish anymore. Grade 8+9 and BAFs work but for Grade 10 fish the animation just runs for like 5 seconds and then stops and i get the message "fishing failed"

**Comment by Peckspas** [comment]
My friend said for him BAFs fail now

**Comment by SoliaRdi** [comment]
Oh, my bad, missed 1 parentheses
