### ISSUE TITLE
Bank function

### ISSUE THREAD

**Issue by Sevih** [SoliaRdi/auto-fishing#135]
https://i.imgur.com/M2Hh4cp.png

Seems a fix is needed for it

**Comment by SoliaRdi** [comment]
Not fix but opcode, region?

**Comment by Sevih** [comment]
EU

**Comment by SoliaRdi** [comment]
Do you download new opcodes?

**Comment by Sevih** [comment]
Seems fine with. Thanks

**Comment by SoliaRdi** [comment]
Np
