### ISSUE TITLE
works, but doesn't after the latest update

### ISSUE THREAD

**Issue by treu00** [SoliaRdi/auto-fishing#136]
[command] ERROR: Error: [dispatch] hook: unmapped packet "S_FISHING_BITE"
![image](https://user-images.githubusercontent.com/46444680/56211411-283d3800-6058-11e9-8ff9-57309791c765.png)
Guessing it broke because of today's maint

**Comment by SoliaRdi** [comment]
how tf module is loaded at all =_=

**Comment by SoliaRdi** [comment]
Do you update opcodes?

**Comment by SoliaRdi** [comment]
Do it

**Comment by treu00** [comment]
I did, still doesn't work
