### ISSUE TITLE
gms checking on player accounts

### ISSUE THREAD

**Issue by tsunpot** [SoliaRdi/auto-fishing#138]
A guildie of mine experienced a gm checking on fishing spots while on a normal player account and whispering them to see if they were actively fishing. Luckily he was still there, but the same may not happen to everyone. Is there a way to implement an auto whisper reply option for instances like this?

**Comment by kamusan** [comment]
how can this be a problem , aren't we allowed to not answer normal players , do we have to reply all whispers???

**Comment by SoliaRdi** [comment]
No, i won't make this. And no reason to implement in this mod
