### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by affi94** [SoliaRdi/auto-fishing#139]
after EU patch 16.04 doesn't work anymore

**Comment by SoliaRdi** [comment]
but it work

**Comment by affi94** [comment]
i downloaded all stuff from github. still doesnt work. where i can find this opcodes?

**Comment by affi94** [comment]
![image](https://user-images.githubusercontent.com/45181768/56455086-8f116880-635a-11e9-9793-d3d5b97bcdba.png)

**Comment by affi94** [comment]
I moved "Move the files inside the defs folder into Your-Proxy-Folder/node_modules/tera-data/protocol.
- Move and merge the protocol files into Your-Proxy-Folder/node_modules/tera-data/map."
and now /8 stopped working.

**Comment by SoliaRdi** [comment]
I dont even use s_inven.Are you using caali proxy?

**Comment by affi94** [comment]
yes i downloaded "CaaliTeraProxy-Monkey-fish" pack with your module
