### ISSUE TITLE
Increase delay after successful fish againts Fishing canceled.

### ISSUE THREAD

**Issue by zokiopp** [SoliaRdi/auto-fishing#140]
I look at the previous issues and i saw some command "fish setdelay" to 12000. When i type that command proxy says invalid command. I often get the fishing canceled error on my laptop only(coz of the weaker specs probably) . How can i set the delay or any other way to fix this problem? Thanks

**Comment by SoliaRdi** [comment]
Already in readme

**Comment by zokiopp** [comment]
I saw now that i need to open the saved file. There are several timings and im unsure which one does that specific thing? should i adjust the setfishrod timings or i have to add new line? also, those are in miliseconds? sorry i never done this before.

**Comment by alfpollo** [comment]
![error fish](https://user-images.githubusercontent.com/48500023/56383359-41242580-61df-11e9-8a1b-74d5be41a4b2.jpg)
help on NA

**Comment by SoliaRdi** [comment]
Install needed opcodes. Check this line and find them here
![image](https://user-images.githubusercontent.com/34610562/56383501-9c2b3c00-6222-11e9-994a-f19dc6ce0fd7.png)

**Comment by SoliaRdi** [comment]
@zokiopp yes, in ms. For fishing rod delays you need to override rod timings

**Comment by Swaggerup** [comment]
> ![error fish](https://user-images.githubusercontent.com/48500023/56383359-41242580-61df-11e9-8a1b-74d5be41a4b2.jpg)
> help on NA

Piece of cake, just update the OPcodes yourself, NA v80.5 was just patched hours ago so either you go through the troublesome way of finding the find opcodes yourself using ID finder or you just download protocol.344895.map

No problem at all i am using the auto fishing just fine.
