### ISSUE TITLE
fishing error

### ISSUE THREAD

**Issue by TheNameles** [SoliaRdi/auto-fishing#141]
hello someone can help me how can i fix this error? all files from mods are instaled correctly in proper folders.  NA region. (ps: i am new to proxy, no idea how to map opcodes). 
![error fish](https://user-images.githubusercontent.com/49794767/56439722-89197a00-62bd-11e9-9125-90eb902cceb7.jpg)

**Comment by SoliaRdi** [comment]
Opcodes already in repo. So recheck all. You doing smth icorrectly

**Comment by TheNameles** [comment]
problem solved, feel free to close this topic and ty for answer!
