### ISSUE TITLE
Disable auto fishing but keep the rest functions

### ISSUE THREAD

**Issue by joty79** [SoliaRdi/auto-fishing#142]
Hello 

I think especially after the ban wave we had that it will be nice addition  if we can disable auto fishing but keep the rest functions.
And what i mean by that just fish afk normally but keep the dismantle - craftinh - selling to npc - store bank.
Afk fishing without bot and top gear is around 2 min per fish which is not bad.
Just it finishes the 60 baits in 2 hours so this is the max u can leave your char without attendance.

For me if i have to choose fishing 3 times slower but not afraid to get ban i ll choose this with closed eyes.

Thanks in advance

**Comment by Snake26183** [comment]
use gmmode stop and skipbaf and you won't get banned

**Comment by joty79** [comment]
> use gmmode stop and skipbaf and you won't get banned

Well i dont know if they had baf enabled but trust me ppl got banned with gmmode stop

**Comment by SoliaRdi** [comment]
Well, profit from this is so low, dk if i should add such mode

**Comment by joty79** [comment]
> Well, profit from this is so low, dk if i should add such mode

profit is 2.5-3 slower than bot if u have top whiskers and green rod. But i dont know at least now in tera EU is very risky to bot with main account. Top tier players got banned 30 days . 

Also when u get caught they ban the accounts that are logged at same time also . 
This means u cant bot even with alt account while u play your main.
Its for security reasons not for profit. 
When u have your main account offline still bot its the best option.

**Comment by SoliaRdi** [comment]
This require some effort. Maybe later, maybe never. I lost interest to public version and tera generally ;)
