### ISSUE TITLE
Error running callback for command "fish"

### ISSUE THREAD

**Issue by FalcorPIX** [SoliaRdi/auto-fishing#145]
I am completely lost here.
Copied the files inside defs folder to CaaliTeraProxy\node_modules\tera-data\protocol
Copied the 3 protocol.x.map to CaaliTeraProxy\node_modules\tera-data\map

Run proxy, go to game, type /8 fish and the title error appears.

Maybe because im EU and those protocol files don't matter?

But the EU file protocol.344895.map is empty, do I need to type anything there? 
The other files have text like "C_END_FISHING_MINIGAME = 46506" etc

Help!

**Comment by AntiScrewdriver** [comment]
I think theres no opcodes for NA 344895, not sure for EU.
![image](https://user-images.githubusercontent.com/47073195/56784613-7535c100-6845-11e9-9ad5-d33e47428bd9.png)

**Comment by SoliaRdi** [comment]
Oh, i accidentally removed them. Look here https://github.com/SoliaRdi/auto-fishing/commit/aa94744a1188d241c948d7a12e6481188fb9e4db

**Comment by FalcorPIX** [comment]
Ok, I pasted that into the file, I dont have the error anymore but it does nothing?
type /8 fish, tells me to start fishing manually, but I have to keep doing it myself, wont complete the minigame or anything?

**Comment by SoliaRdi** [comment]
I hope you pasted correct opcodes from deleted  protocol.344895.map ?

**Comment by FalcorPIX** [comment]
ok im dumb af. its working properly now.
