### ISSUE TITLE
Fishing in EU

### ISSUE THREAD

**Issue by Peckspas** [SoliaRdi/auto-fishing#148]
Is anyone still using this module in EU after the ban wave and how save is it to use?
Is this auto detected or did GMs ban all these people manually? 
Also does anyone know if these bans were permanent?

**Comment by trev44** [comment]
ive been fishing for quite sometime, im still fine

**Comment by Distortionn** [comment]
This module has a human + rng timer for fishing. You should be fine.

**Comment by SoliaRdi** [comment]
You can increase delays if afraid
