### ISSUE TITLE
c_put_ware_item is not mapped

### ISSUE THREAD

**Issue by Gurenji** [SoliaRdi/auto-fishing#151]
Hello, I was wondering if anyone could help me with a sudden error I am getting.
Set up the fishing like I normally do. But now I am getting an error for a few functions:

![TERA_TgygaaToRf](https://user-images.githubusercontent.com/49957981/56914639-e5964980-6ab4-11e9-86a2-e40956892207.png)

error running callback for command ''fish''
C_PUT_WARE_ITEM is not mapped

Honestly not sure what is causing it so I removed all files, downloaded the mod file again and tried to install it as shown in the notes. But I am still having this error.

If anyone knows the fix for this it will be appreciated. 
If there is any other info I can provide to help you troubleshoot let me know!

**Comment by SoliaRdi** [comment]
If this opcode not in protocol.{your-region-map-number}.map then i dont have it. And you shoulp map it yourself

**Comment by Gurenji** [comment]
Thank you very much Solia! I found the correct one for EU [protocol.347373.map.](https://github.com/SoliaRdi/auto-fishing/blob/master/protocol.347373.map)
copied the text and placed it in the file. Now it works again!
And thank you for the very quick reply as well.
