### ISSUE TITLE
event in eu

### ISSUE THREAD

**Issue by kriiszmae** [SoliaRdi/auto-fishing#152]
hi, can u add the bait of the fishing event to the baits list?..atm i need to manually select the special bait after every catch. plzzz ty

**Comment by SoliaRdi** [comment]
Send id or name

**Comment by rkswag** [comment]
got the same issue but the baits dont have any name xD

**Comment by NotZiora** [comment]
[12:41:25.658] [item id finder] Item ID | 143188 | found.

**Comment by rkswag** [comment]
some way i can put it in my config myself ?

**Comment by Distortionn** [comment]
ID from NotZiora should work. Otherwise maybe an option to keep it fishing with the current bait you have on, Idk.

EU has an event up right now yeah and you'll get a lot of that bait so being able to use that would be great.

Thanks in advance!

**Comment by kriiszmae** [comment]
I
![notepad++_V4XmdytKiA](https://user-images.githubusercontent.com/47244732/56960588-a66a0600-6b51-11e9-9b9d-44601ab29fc4.png)
 guess u can manually add the item id of the bait here but what are those num in the first column?

**Comment by SoliaRdi** [comment]
Abnormality id
