### ISSUE TITLE
Event Eu

### ISSUE THREAD

**Issue by kriiszmae** [SoliaRdi/auto-fishing#153]
hey sorry to bother u again, but when using the mod and the event bait after catching one it auto select another bait in inventory.

**Comment by SoliaRdi** [comment]
Even after update?

**Comment by kriiszmae** [comment]
yeah :(..it catch one and then select the other bait i have and then telling me fish canceled

**Comment by SoliaRdi** [comment]
Smth wrong with this baits

**Comment by kriiszmae** [comment]
yeah..maybe coz its just an event one
