### ISSUE TITLE
The merchant already supports 18 items instead of 8

### ISSUE THREAD

**Issue by tehtelev** [SoliaRdi/auto-fishing#156]
The latest patch (on RU) updated interface sellers. They contain 18 cells.
In the index.js you need to correct lines 398 and 403.

**Comment by SoliaRdi** [comment]
NA still patch 80?

**Comment by rayted-r** [comment]
NA just went patch 81 couple hrs ago

**Comment by tsunpot** [comment]
81.3

**Comment by tsunpot** [comment]
need S_STORE_BASKET for 347372 we managed to find everything else

**Comment by tsunpot** [comment]
C_END_FISHING_MINIGAME = 35483
C_PUT_WARE_ITEM = 50506
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 45879
C_START_FISHING_MINIGAME = 47653
C_STORE_COMMIT = 31312
C_STORE_SELL_ADD_BASKET = 40423
S_FISHING_BITE = 49451
S_FISHING_CATCH = 22853
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 48398
C_MEDAL_STORE_BUY_ADD_BASKET = 54626
C_MEDAL_STORE_COMMIT = 31312
S_MEDAL_STORE_BASKET = 25898
S_START_FISHING_MINIGAME = 37906

**Comment by EseLen** [comment]
@tsunpot any luck on S_STORE_BASKET? I can't really figure it out but there's a response talking about how to get it here: https://github.com/SoliaRdi/auto-fishing/issues/56

**Comment by tsunpot** [comment]
we are thinking S_STORE_BASKET got changed to S_STORE_SELL_LIST but im not sure

**Comment by EseLen** [comment]
hmm, have to tried it? I dont have that opcode either

**Comment by tsunpot** [comment]
we got that one but no idea, would need to rewrite the module for a bit

**Comment by tsunpot** [comment]
its not vital, only used for selling fish to scroll npc

**Comment by EseLen** [comment]
True, i'm just gonna go the dismantle route since its not really all that important.

**Comment by cybrwolf** [comment]
well even the dismantle is not working with the listed opcode

**Comment by EseLen** [comment]
Huh.. you're right.. well this sucks. lol

**Comment by cybrwolf** [comment]
> Huh.. you're right.. well this sucks. lol

C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 45812

enjoy the dismantle atleast ;)

**Comment by Fedelhoplf** [comment]
what mean this numbers?!

**Comment by SoliaRdi** [comment]
S_STORE_BASKET goes after C_STORE_SELL_ADD_BASKET. You can see it via logger. Packet contain array with listed items so size will grower wlile you adding items

**Comment by SoliaRdi** [comment]
i'll add more slots later
