### ISSUE TITLE
Error (NA Client v81.0)

### ISSUE THREAD

**Issue by crowncola94** [SoliaRdi/auto-fishing#157]
When I type "fish" to turn on the module it states:

"Error running callback for command "fish".

Any quick fixes for this? Already re-downloaded the mod and still same error.

**Comment by SisterDaniel** [comment]
Got the same problem >.<

**Comment by AntiScrewdriver** [comment]
> 
> 
> When I type "fish" to turn on the module it states:
> 
> "Error running callback for command "fish".
> 
> Any quick fixes for this? Already re-downloaded the mod and still same error.

Opcodes arent mapped yet for NA v81.0 .
There are guides to help you find the codes yourself **https://github.com/beng-mods/opcodes-4-dummies** ... but im too tech-illiterate .. so i just sit, wait and hope for someone to post the codes here.
Keep checking back.

**Comment by tsunpot** [comment]
look at the other issue opened, opcodes are posted there

**Comment by shinctl** [comment]
I've managed to get everything working except the sale to NPC... If anyone is interested I can post the opcodes here. Wasn't able to get S_STORE_BASKET

**Comment by crowncola94** [comment]
That would be great. I don't use the sale to NPC function anyways

**Comment by shinctl** [comment]
C_END_FISHING_MINIGAME = 35483
C_MEDAL_STORE_BUY_ADD_BASKET = 37567
C_MEDAL_STORE_COMMIT = 62273
C_PUT_WARE_ITEM  = 49381
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 45812
C_START_FISHING_MINIGAME = 47653
C_STORE_COMMIT = 27539
C_STORE_SELL_ADD_BASKET = 40423
S_FISHING_BITE = 49451
S_FISHING_CATCH = 22853
S_MEDAL_STORE_BASKET = 25898
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 48398
S_START_FISHING_MINIGAME = 37906

**Comment by Fedelhoplf** [comment]
how i put this opcode?

**Comment by shinctl** [comment]
Just put this on file protocol.347372.map located in ...\node_modules\tera-data\map

**Comment by shotodes** [comment]
please post the sell to npc opcode when you find it. Thanks alot :)

> I've managed to get everything working except the sale to NPC... If anyone is interested I can post the opcodes here. Wasn't able to get S_STORE_BASKET

Thanks alot for your help pls post teh sell to npc opcode when you get it.

**Comment by SoliaRdi** [comment]
i'll push opcodes when someone post S_STORE_BASKET, how to find it i already answer in many issues

**Comment by shinctl** [comment]
S_STORE_BASKET not available on this update for NA, probably changed for something else...

**Comment by SoliaRdi** [comment]
this is not possible

**Comment by shinctl** [comment]
I was able to get all other opcodes easily, just replicating the actions... 
Tried to get S_STORE_BASKET selling fish to NPC, filling the slots on the NPC, selling only 1 fish and nothing on FPI/Logger

**Comment by MeongMeongMeong** [comment]
same result here, S_STORE_BASKET has always the issue to find, on both FPI logger and pocker logger shows no result

**Comment by SoliaRdi** [comment]
so no any packet that look like this?
![image](https://user-images.githubusercontent.com/34610562/57390412-f5a0de00-71c4-11e9-9684-6f87c6217015.png)

**Comment by MeongMeongMeong** [comment]
after the patch, that line doesn't seems to appear in pocket logger

**Comment by tsunpot** [comment]
https://gyazo.com/eddf46bc26c89ad77d232bd7f1313cc4

**Comment by SoliaRdi** [comment]
but you see 47324 =_=

**Comment by SoliaRdi** [comment]
this is S_STORE_BASKET

**Comment by SoliaRdi** [comment]
that's how manual mapping working, you looking in hex numbers

**Comment by Aznshorty13** [comment]
[https://cdn.discordapp.com/attachments/199006091122573312/575720835709403146/Capture.JPG](url)

Can confirm that one works.

**Comment by MeongMeongMeong** [comment]
that is the code, in my case, the C_STORE_SELL_ADD_BASKET doesnt shown, thats why i can get the code :_:

**Comment by MeongMeongMeong** [comment]
protocol.347372 is the new NA btw

**Comment by SoliaRdi** [comment]
thx all

**Comment by shotodes** [comment]
> so no any packet that look like this?
> ![image](https://user-images.githubusercontent.com/34610562/57390412-f5a0de00-71c4-11e9-9684-6f87c6217015.png)

S_STORE_BASKET = 47324

this should work for NA (works for me)... there is a problem w NA it shows (null) instead of S_STORE_BASKET.. so have to grab valueafter C_STORE_SELL_ADD_BASKET

**Comment by SoliaRdi** [comment]
(null) means that opcode not mapped to name. This is not an error

**Comment by tsunpot** [comment]
but we are still missing the def for S_STORE_BASKET

**Comment by SoliaRdi** [comment]
i dont need it. If someone want he can do it and share

**Comment by tsunpot** [comment]
found out we dont need it either
