### ISSUE TITLE
Reducing delay

### ISSUE THREAD

**Issue by brnbrito** [SoliaRdi/auto-fishing#158]
How should i go about changing delay to make it slighly faster? (I know about the risks)

I've tried changing the "minigame" and "rod" on config and didn't seem to give me any result, and after messing a bit with the minigame timer it'd just cancel itself, let's say i wanna reduce time/fish by 3-5s~, what should i do?

**Comment by SoliaRdi** [comment]
I don't recommend lower "minigame" less than 2s and "rod" less than 5s(client limits without C_CAST handling). You could lower any other

**Comment by brnbrito** [comment]
When i redownloaded yesterday i think default "rod" was around "4500-5500", was taking me 50s~ per fish, so i decided to change to the values i had before v81 patch, which is "2000-3000" on minigame and "3023-3798" on "rod", time/fish dropped to 39s, i assume that's miliseconds and i shouldn't go any lower than that already? Tried putting lower than 3023-3798 but had the same results of 39s~ per fish.

**Comment by SoliaRdi** [comment]
39s is fine. With low rod delay you will cancel fishing
