### ISSUE TITLE
TypeError: Cannot read property 'shift' of undefined

### ISSUE THREAD

**Issue by Lambda11** [SoliaRdi/auto-fishing#159]
after working for some time gave this:
```
Tera Proxy Caali\mods\auto-fishing-master\index.js:866
                let fish = request.fishes.shift();
                                          ^

TypeError: Cannot read property 'shift' of undefined
    at sellFish (Tera Proxy Caali\mods\auto-fishing-master\index.js:866:29)
    at mod.setTimeout (Tera Proxy Caali\mods\auto-fishing-master\index.js:407:8)
    at Timeout.setTimeout [as _onTimeout] (Tera Proxy Caali\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:278:7)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

Для продолжения нажмите любую клавишу . . .
```

**Comment by SoliaRdi** [comment]
I dont have any idea how you trigger this error

**Comment by SoliaRdi** [comment]
One guess is that you selling operation takes so long so it trigger idleCheckTimer

**Comment by Lambda11** [comment]
Well, I have almost 100 free slots filled with fish...

**Comment by SoliaRdi** [comment]
idleCheckTimer has 5 min delay. 100 fishes is ~40-50s

**Comment by Lambda11** [comment]
Well, I noticed error happens while working with second half of the fish (1st half of my inventory got empty off fish already and then error happened)

**Comment by SoliaRdi** [comment]
Try with debug enabled to see if selling interrupted by makeDecision. This version is working more than month. And such error happened only with you

**Comment by Lambda11** [comment]
yea, it seems cuz of idle check cuz
```
00:44 usescroll
00:49 userod
```
and it crashes proxy with TypeError

**Comment by SoliaRdi** [comment]
Strange, selling part can be done even with suspended client. So the problem is something else. Can you send me "time" section of your config, just to be sure?

**Comment by Lambda11** [comment]
I haven't changed standart times in config anyhow, just turned on autosalad tho, and sellscroll with a proxy command

try using http://mion.faireal.net/BES/ to artificially limit your Tera CPU usage by 98% and leave it for some time, I think it should trigger for you too (just to see the error)

**Comment by SoliaRdi** [comment]
forgot about some packet in selling that can be delayed by this program. I suggest you to just use lowest s1engine with smooth frame rate 8-12fps and disable gui, instead of this program. this mod doesnt support process suspend or similar features

**Comment by Lambda11** [comment]
I didn't say I was using it tho (or anything else), just suggested you try to see the problem cuz it might trigger it

can't you just fix it?
