### ISSUE TITLE
fillet + inventory

### ISSUE THREAD

**Issue by AmazingTeraPlayer** [SoliaRdi/auto-fishing#16]
Breaks when you are near 10,000 fillet (stack/inventory limit) and full inventory. - cannot dismantle fish as it would go above stack limit.

solutions: add option for discarding fish when above a thresh hold of fillet, add option for craft fish crates after dismantle when above a thresh hold of fillet, add option for discarding fillets when above a thresh hold of fillet.

**Comment by SoliaRdi** [comment]
Yeah, i know. https://github.com/SoliaRdi/auto-fishing/issues/15
