### ISSUE TITLE
Error running callback for command "fish".

### ISSUE THREAD

**Issue by Roxarine** [SoliaRdi/auto-fishing#160]
[command] ERROR: Error: [dispatch] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook 
    at Dispatch.hook 
    at Module.hook 
    at hook 
    at toggleHooks 
    at String.mod.command.add 
    at CommandBase.exec 
    at hookCommand 
    at Object.CommandBase.mod.hook.event [as callback] 
    at Dispatch.handle 

I've getting this error since yesterday's TERA update.
how can i resolve this issue?

**Comment by cybrwolf** [comment]
by using the appropriate .map file for your region

**Comment by Roxarine** [comment]
> by using the appropriate .map file for your region

should I try reinstalling the mod again?

**Comment by cybrwolf** [comment]
if you are from NA .. just copy the protocol.347372.map file into your proxy folder node_module/tera-data/map

**Comment by Roxarine** [comment]
> if you are from NA .. just copy the protocol.347372.map file into your proxy folder node_modules/tera-data/map

nope that didn't work

**Comment by SoliaRdi** [comment]
Did you restart proxy after installing opcodes in correct file and folder?

**Comment by Roxarine** [comment]
> Did you restart proxy after installing opcodes in correct file and folder?

I reinstalled the whole mod again and now it's working fine.
Thank you for creating this great mod!
