### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by crowncola94** [SoliaRdi/auto-fishing#161]
Any chance for you to create this mod with the TERA Reward Club in mind since anything about a certain tier gets free bankers?

**Comment by SoliaRdi** [comment]
idk how it works, is this just S_PREMIUM_SLOT_DATALIST+C_PREMIUM_SLOT_USE_SLOT?

**Comment by crowncola94** [comment]
¯\_(ツ)_/¯

**Comment by crowncola94** [comment]
It's a skill you get from Reward Club, not an item. Idk how you would do something like that

**Comment by porkbonesoups** [comment]
i would like to remind that this is NA exclusive

**Comment by SoliaRdi** [comment]
Just give me log when you using it. Idk even how it looks :D

**Comment by SoliaRdi** [comment]
No info - no feature
