### ISSUE TITLE
Configuration save functionality.

### ISSUE THREAD

**Issue by Shippou5** [SoliaRdi/auto-fishing#162]
What does saving configuration mean exactly? Does it mean that it saves literally every command I typed in before saving (meaning bait type, using gmmode, blacklisted fishes etc.) Or does it only apply to certain settings, if so what are those settings?

**Comment by cybrwolf** [comment]
a very quick, but effective answer, in your mod folder you will have a specific configuration files for every character you have.. inside you will have different setting you can tweak.. but the last section of the file.. is the main setting they save, wich are those you apply ingame trough mod command. go take a look at those config files to picture by yourself wich settings are saved
