### ISSUE TITLE
its not dismantling all fish that are not gold.

### ISSUE THREAD

**Issue by TeraPlayer1994** [SoliaRdi/auto-fishing#163]
How do you set it to dismantle all but BAF fishes? I can not find dismantle setting. I blacklisted my golden shark but it wont dismantle some blues as well... like the <Chroma Salmon> and <Dipturus> fish

P.S. Sorry still new to this, sorry in advance

**Comment by SoliaRdi** [comment]
Idk how can i help you tbh. Try to recheck config
