### ISSUE TITLE
Phargo Filetmode Bank

### ISSUE THREAD

**Issue by RogueYin** [SoliaRdi/auto-fishing#164]
Can't seem to get the phargo to move filets into storage when inventory is full and its set to deposit. Summons Phargo using the scroll, opens banker, but then nothing and will sit there and summon another phargo when able. Any solutions? Filetmode bank was set to default 8000.

**Comment by SoliaRdi** [comment]
Region?

**Comment by RogueYin** [comment]
NA

**Comment by SoliaRdi** [comment]
I cant check opcodes for na. It sound like incorrect C_PUT_WARE_ITEM opcode

**Comment by RogueYin** [comment]
Damn, okay, any idea as to where I'd be able to locate it?

**Comment by SoliaRdi** [comment]
Use any packet finder method and put item

**Comment by RogueYin** [comment]
![ID](https://user-images.githubusercontent.com/50600508/57660536-fbd8f500-75de-11e9-914b-9ccee6eff996.png)
Would this be the thing I'm looking for? showed up while depositing the filets into a bank.

**Comment by SoliaRdi** [comment]
Probably. Try it and give responce here to fix it for NA

**Comment by SoliaRdi** [comment]
So this is correct opcode?

**Comment by RogueYin** [comment]
Had to leave it over night to find out as didn't have any filets on me already, can confirm this works.

**Comment by SoliaRdi** [comment]
Thx :ok_hand:
