### ISSUE TITLE
New to this

### ISSUE THREAD

**Issue by ic3dt3a** [SoliaRdi/auto-fishing#165]
I'm new-ish to using these tools. I re-installed Caali's with the tera proxy ui update, so its a fresh install. I keep getting the unknown command error. I believe I'm correctly copying the files into the proper folder. I've only used the fps mode on it, in the past, but went ahead and got the rk9 to verify that it is working. Still, i cannot get it to work, I've even tried deleting the other regions' .map files. I've restarted it after edit to the folder as well. If/When you get a chance, can you direct me on getting it to work? 

![map](https://user-images.githubusercontent.com/50600857/57660764-219dd400-75b6-11e9-803c-9bad73b6d5a9.png)
![protocol](https://user-images.githubusercontent.com/50600857/57660766-219dd400-75b6-11e9-80df-fbdba2c8e2bc.png)

**Comment by SoliaRdi** [comment]
Region?

**Comment by ic3dt3a** [comment]
NA. I've tried it with leaving the other regions' .map and removing them, as well. I'll give it another try when i get home today.

**Comment by SoliaRdi** [comment]
Can't help
