### ISSUE TITLE
Fishing automatically stops when I reach 9000 fillets

### ISSUE THREAD

**Issue by Shippou5** [SoliaRdi/auto-fishing#166]
Is there a way to get around this issue? I have about 496 merchant scrolls which could sell the fillets but I only see option to walk to an npc, possibly is there another solution? Maybe an option to just automatically throw away the fillets?

**Comment by SoliaRdi** [comment]
wat? Why would you need to sell fillets instead of fishes?

**Comment by Peckspas** [comment]
You need to either stand next to an NPC and let the module sell fishes or let the module bank fish fillets after u reached a certain number(with bank npc scrolls).

**Comment by SoliaRdi** [comment]
He can use his merchant scrolls as well

**Comment by Shippou5** [comment]
Okay sure I can use merchant scrolls to sell the fish as well I am just asking how to do it, I have so many scrolls but no clue how to make the program understand to use it instead of running to an npc.

**Comment by SoliaRdi** [comment]
/8 fish sellscroll

**Comment by Shippou5** [comment]
Ah alright got it, but isn't it more risky to have the bot summon the npc every time my inventory is full of fish rather than have it only summon the npc when my inventory is full of fillets so it can go back to fishing? Don't wanna get banned.

**Comment by Peckspas** [comment]
Again if you want that then just use the command for banking fillets with a bank npc scroll and just sell it manually.. how hard can it be to take 2-3 stacks of fillet out your bank and sell them to the npc manually every 24hrs
