### ISSUE TITLE
Does the mod save my settings?

### ISSUE THREAD

**Issue by Shippou5** [SoliaRdi/auto-fishing#167]
I am asking if I have to input commands every single time I start fishing or maybe I need to reloadconf or perhaps it only saves if I use fish save command.

I want the mod to remember basic things such as gmmode, fish blacklisting and filet banking settings.

**Comment by SoliaRdi** [comment]
![image](https://user-images.githubusercontent.com/34610562/58183637-55fd4880-7cb8-11e9-8578-63799925d226.png)

only this

**Comment by Shippou5** [comment]
Okay that is how I save my settings what about reloadconf? Do I need to use it every time I start fishing so it loads up the settings I saved via /8 fish save or does the system remember it?

**Comment by SoliaRdi** [comment]
reloadconf needs only when you edit setting manually in notepad. fish save only when you need to save your settings

**Comment by Shippou5** [comment]
I am asking this because my mod already forgot about my blacklisted baf fish "goldenshark" and started dismantling it over two accounts so it isn't a one time thing plus it changed my settings from gmmode "lobby" to "stop" for no reason, didn't touch any settings.

**Comment by SoliaRdi** [comment]
probably you forgot to save

**Comment by Shippou5** [comment]
Even if I did, why would it change from lobby to stop? I've never used the gmmode command, I didn't even know what was the command until it changed it for me.

**Comment by SoliaRdi** [comment]
stop is in default settings

**Comment by Shippou5** [comment]
So it reverted to default? Weird, when I installed the mod it was lobby but I guess that changed at some point.

**Comment by SoliaRdi** [comment]
Maybe config for some reasons was corrupted. Or you change your nickname

**Comment by Shippou5** [comment]
Ah I see so something must've gone wrong, happens from time to time.

Well thank you for your time Solia :) May your fishing be strong and your coding even stronger.
