### ISSUE TITLE
update it please for the current patch

### ISSUE THREAD

**Issue by kath19x** [SoliaRdi/auto-fishing#169]
Patch ver TH v82.5 Tera Sea.  Fishing does not give errors but it does not work as well.  Caali is already working fine but the mod is not

**Comment by SoliaRdi** [comment]
If your question is not related to opcodes, then wait patch v82 on ru.

**Comment by kath19x** [comment]
Yea it is not about opcodes, oh I guess SEA got the patch earlier than other servers.  I will wait then.  Thanks

**Comment by herowinb** [comment]
I can confirm this module still work correct, just update new opcode for SEA

**Comment by kath19x** [comment]
> 
> 
> I can confirm this module still work correct, just update new opcode for SEA

It is not giving any errors, the patch is new and the mod needs to be updated for v82.5.  Do you play in Tera SEA? Mind sharing your Opcode? Thanks!

**Comment by flytomoon88** [comment]
Opcode for SEA (349932)

C_END_FISHING_MINIGAME = 51894
C_MEDAL_STORE_BUY_ADD_BASKET   = 34609
C_MEDAL_STORE_COMMIT   = 59361
C_PUT_WARE_ITEM   = 27874
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT   = 58231
C_START_FISHING_MINIGAME   = 46191
C_STORE_COMMIT   = 33352
C_STORE_SELL_ADD_BASKET   = 63003
S_FISHING_BITE   = 47647
S_FISHING_CATCH   = 58950
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT   = 40046
S_START_FISHING_MINIGAME   = 40375
S_STORE_BASKET   = 63409

**Comment by kath19x** [comment]
> 
> 
> Opcode for SEA (349932)
> 
> C_END_FISHING_MINIGAME = 51894
> C_MEDAL_STORE_BUY_ADD_BASKET = 34609
> C_MEDAL_STORE_COMMIT = 59361
> C_PUT_WARE_ITEM = 27874
> C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 58231
> C_START_FISHING_MINIGAME = 46191
> C_STORE_COMMIT = 33352
> C_STORE_SELL_ADD_BASKET = 63003
> S_FISHING_BITE = 47647
> S_FISHING_CATCH = 58950
> S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 40046
> S_START_FISHING_MINIGAME = 40375
> S_STORE_BASKET = 63409

Thanks! It worked.  What I find weird is it never gave me error like it used to when there is a new patch, also the mappings.json file  still got the old  "TH": {"version": 347377, "major_patch": 81, " that is why I was under the impression that Caali or the mod needs to be updated.  Can anyone  enlighten me?  Thanks!

**Comment by flytomoon88** [comment]
when you logged in to the game, it shows the protocol version which the proxy is using.  You need to update the corresponding Opcodes if the protocol version changed.

**Comment by kath19x** [comment]
> 
> 
> when you logged in to the game, it shows the protocol version which the proxy is using. You need to update the corresponding Opcodes if the protocol version changed.

Ohh.. Got it! Thanks!
