### ISSUE TITLE
does not work with multiple clients after last update

### ISSUE THREAD

**Issue by Ebnzo** [SoliaRdi/auto-fishing#17]

**Comment by SoliaRdi** [comment]
Config conflict or something else?

**Comment by Ebnzo** [comment]
some issue with player location

**Comment by SoliaRdi** [comment]
weird. Update of proxy(Caali gui things) or only my mod?

**Comment by Ebnzo** [comment]
only ur mod, im use updated caali proxy without BigInt.prototype.toJSON fix

**Comment by SoliaRdi** [comment]
Try again, cant test this behaviour

**Comment by Ebnzo** [comment]
issue solved, ty
