### ISSUE TITLE
Bot/Mod won't properly use the "Event Icefish" bait.

### ISSUE THREAD

**Issue by kath19x** [SoliaRdi/auto-fishing#170]
It keeps on crafting and using the typical bait after using only 1 of the event bait.  If it can't craft or find a typical bait, it will just stop fishing with the error "ERROR: Can't find any fishes for dismantle" 

How to fish bot with the new event bait? [Event] Icefish Bait

**Comment by SoliaRdi** [comment]
Send me abnormality id and item id of this bait

**Comment by kath19x** [comment]
> 
> 
> Send me abnormality id and item id of this bait

How do I do that? or Where to find the ID?

**Comment by SoliaRdi** [comment]
From parsed datacenter or by logs. Use bait and see abnid(in my logger packet blacklisted by default) and id in use item packet

**Comment by kath19x** [comment]
> 
> 
> From parsed datacenter or by logs. Use bait and see abnid(in my logger packet blacklisted by default) and id in use item packet

This is what I got

<---- Hook ENABLED ---->
[22:58:6:665] <-          	 S_ABNORMALITY_END    (id 24361)
{
    "target": "5488762045970859",
    "id": 9943049
}

**Comment by SoliaRdi** [comment]
and C_USE_ITEM

**Comment by kath19x** [comment]
> 
> 
> and C_USE_ITEM

[22:58:10:895] ->          	 C_USE_ITEM    (id 42264)

**Comment by SoliaRdi** [comment]
=) Ok. You can disable autoupdate and test it yourself https://github.com/SoliaRdi/auto-fishing/blob/master/index.js#L47 first is abn id second item(bait) id

**Comment by kath19x** [comment]
> 
> 
> =) Ok. You can disable autoupdate and test it yourself https://github.com/SoliaRdi/auto-fishing/blob/master/index.js#L47 first is abn id second item(bait) id

I added it like this, did not work.

		5000012 : 143188, //event
		24361 : 42264 //ice fish event
	};

**Comment by SoliaRdi** [comment]
because you add opcode id, not item. And idk about abn id, probably this is not even yours

**Comment by kath19x** [comment]
I give up.  Maybe I'll wait for Tera RU to patch with 82.5 :(

**Comment by kath19x** [comment]
Hi, I updated with ur new manigest and index but it still won't use the event bait.  Can you please add the bait since you got the patch already? Thanks!

**Comment by SoliaRdi** [comment]
Idk what bait is this. Because event baits already added

**Comment by SoliaRdi** [comment]
Ru patch delayed to next week

**Comment by kath19x** [comment]
ohh.  I will wait till next week then :(

**Comment by SoliaRdi** [comment]
I dont play this game, so i wont join any events. Try to find at least bait id

**Comment by SoliaRdi** [comment]
Actually. You can add bait to blacklist to see id and then remove it

**Comment by kath19x** [comment]
> 
> 
> Actually. You can add bait to blacklist to see id and then remove it

This is what shows when I blacklist it "856470" which I already used this ID before.  Maybe I have problem with getting the abnormality id?

**Comment by kath19x** [comment]
I already tried

70355: 856470, // ICEFISH
and
9943049: 856470, // ICEFISH

That is all the abnormality ID in the log and still does not use the bait after the first try

**Comment by Codemacchiato** [comment]
I did it, @kath19x 

Add the following to https://github.com/SoliaRdi/auto-fishing/blob/master/index.js#L47
`5060038: 856470, // ICEFISH BAIT`

**Comment by SoliaRdi** [comment]
I'll add later today too, thx =)

**Comment by kath19x** [comment]
Oohh. Nice! Thanks!!

**Comment by kath19x** [comment]
> 
> 
> I did it, @kath19x
> 
> Add the following to https://github.com/SoliaRdi/auto-fishing/blob/master/index.js#L47
> `5060038: 856470, // ICEFISH BAIT`

It worked! Thanks, do you mind how you got the value? 'Cause I can't seem to get it, for future events like this.  Thanks again, now I can use my 600+ event bait lol.

**Comment by Codemacchiato** [comment]
I modify this line to log abnormality id, then right click on bait.

https://github.com/SoliaRdi/auto-fishing/blob/master/index.js#L514

```
mod.hook('S_ABNORMALITY_BEGIN', 3, event => {
 mod.command.message('abnormality id ${event.id}');
 if (mod.game.me.is(event.target))
..
```

remember to turn on debug with `fish debug` command.

**Comment by kath19x** [comment]
oohh. Ok thanks! too advanced for me haha!
