### ISSUE TITLE
Stops auto fishing after dismantle

### ISSUE THREAD

**Issue by wyssmuth** [SoliaRdi/auto-fishing#171]
The bot seems to work fine, i start the game, activate the mod, start fighsing, after the baits end it starts to dismantle, when all the fishs are dismantled it stops saying: "ERROR: Can't find any fishes for dismantle." and them: "Auto fishing deactivated."

**Comment by wyssmuth** [comment]
I can't really say if it is crafting baits properly because i've never get into this part.

**Comment by SoliaRdi** [comment]
This can be if you dismantle fishes and result is less than 60 fillets

**Comment by wyssmuth** [comment]
It is, thanks. it's working properly. Thx a lot for the mod! <3
