### ISSUE TITLE
New EU opcodes version 350022 - v82.5

### ISSUE THREAD

**Issue by trev44** [SoliaRdi/auto-fishing#173]
C_END_FISHING_MINIGAME = 61011
C_PUT_WARE_ITEM = 25884
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 45822
C_START_FISHING_MINIGAME = 25633
C_STORE_COMMIT = 25239
C_STORE_SELL_ADD_BASKET = 61633
C_STORE_BUY_ADD_BASKET = 45016
C_MEDAL_STORE_BUY_ADD_BASKET = 46117
C_MEDAL_STORE_COMMIT = 37316
S_MEDAL_STORE_BASKET = 49612
S_FISHING_BITE = 53982
S_FISHING_CATCH = 22671
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 23497
S_START_FISHING_MINIGAME = 34452
S_START_FISHING_CHARGE = 39900
S_STORE_BASKET = 31815

everything seems fine my side.

**Comment by LxMk864** [comment]
How correction this? Need other tool?

**Comment by LxMk864** [comment]
Past file .map for eu deletion from map directory?

**Comment by SoliaRdi** [comment]
thx
