### ISSUE TITLE
NA version - 29/05 - [command] ERROR: Error: [dispatch] hook: unmapped packet "S_FISHING_BITE" 

### ISSUE THREAD

**Issue by andersonepk** [SoliaRdi/auto-fishing#176]
![image](https://user-images.githubusercontent.com/18029568/58604683-a6057d80-826b-11e9-9880-b5fb5d6da0e1.png)

**Comment by kath19x** [comment]
That error is usually 'cause you need the new OPCODE.  Either you get them urself or ask someone in NA to give u the updated one

**Comment by andersonepk** [comment]
> That error is usually 'cause you need the new OPCODE. Either you get them urself or ask someone in NA to give u the updated one

how hard is get then? 
Any link that u can share that explain hoe to obtain opcodes? i found this one https://github.com/beng-mods/opcodes-4-dummies 

But is pettry outdate.
Thanks

**Comment by kath19x** [comment]
> 
> 
> > That error is usually 'cause you need the new OPCODE. Either you get them urself or ask someone in NA to give u the updated one
> 
> how hard is get then?
> Any link that u can share that explain how to obtain opcodes? i found this one https://github.com/beng-mods/opcodes-4-dummies
> 
> But is pettry outdate.
> Thanks

That is how you get the opcodes. I use two packet logger https://github.com/Owyn/alex-packet-id-finder and https://github.com/SoliaRdi/PacketsLogger

**Comment by andersonepk** [comment]
so i just have do tip "fpi" on alex-packet-id-finder 
or
logC and logS on SoliaRdi...  

Simple like this?

Dont have any how to use guide in this mods xD

**Comment by andersonepk** [comment]
Ah ok i think i got it, i have to tip what i need
like fpi S_FISHING_BITE and do shits around until something log in.
i will see what i get.
thanks  i think

**Comment by andersonepk** [comment]
So i m getting this, omg i m hacker xD

[06:15:32.509] 37906 as S_START_FISHING_MINIGAME:
[06:15:32.518] {
    "rodId": 206715,
    "gameId": "144255925833375310",
    "level": 6,
    "unk1": "6199901"
}
[06:15:33.166] Candidates for id 37906: [S_START_FISHING_MINIGAME].
[06:15:33.175] 37906 as S_START_FISHING_MINIGAME:
[06:15:33.184] {
    "rodId": 206706,
    "gameId": "144255925833385060",
    "level": 7,
    "unk1": "6199901"
}
[06:15:36.568] Candidates for id 37906: [S_START_FISHING_MINIGAME].
[06:15:36.580] 37906 as S_START_FISHING_MINIGAME:
[06:15:36.617] {
    "rodId": 206706,
    "gameId": "144255925833376525",
    "level": 8,
    "unk1": "6199901"
}
[06:15:36.926] Candidates for id 37906: [S_START_FISHING_MINIGAME].
[06:15:36.963] 37906 as S_START_FISHING_MINIGAME:
[06:15:36.976] {
    "rodId": 206707,
    "gameId": "144255925833381262",
    "level": 8,
    "unk1": "6199901"
}

**Comment by andersonepk** [comment]
ok this is working ... i have to manually change de vaues of xxxx.map.

sorry about waste u time guys, i m hacker now, will conquer the world.
thanks for tips dude.

i understand how it works now hehe

**Comment by andersonepk** [comment]
.

**Comment by andersonepk** [comment]
The OPCODES of NA are here and working. Need to replace this file in proxy
here TeraToolbox\node_modules\tera-data\map.
[image: image.png]

Em qui, 30 de mai de 2019 às 05:14, kath19x <notifications@github.com>
escreveu:
