### ISSUE TITLE
How to throw Full bar rod charge?

### ISSUE THREAD

**Issue by andersonepk** [SoliaRdi/auto-fishing#178]
So, if i do manual fish i can hold the button that throw the rod to max like this.
![image](https://user-images.githubusercontent.com/18029568/58637146-45585e00-82c8-11e9-8462-0a8097f17956.png)
And bait move a great distance.

How i do the same with autofishing active?
Thanks for replys

**Comment by LxMk864** [comment]
This are avoid for not getinnapropiate focused in area fishing

**Comment by andersonepk** [comment]
ohh   ok then thanks

**Comment by andersonepk** [comment]
well but anyway, if i can by my own risk, i can active this option?
To semi afk fishing can be great.
not?

**Comment by SoliaRdi** [comment]
rod dist is not available in this mod. If i remember correct if you charge 1 time rod will be throw same distance

**Comment by andersonepk** [comment]
> rod dist is not available in this mod. If i remember correct if you charge 1 time rod will be throw same distance

U right, i just had to save afer first long distance throw.
Thanks
