### ISSUE TITLE
Sell to NPC?

### ISSUE THREAD

**Issue by andersonepk** [SoliaRdi/auto-fishing#179]
Help with this function?
![image](https://user-images.githubusercontent.com/18029568/58719625-8e7edf80-83a6-11e9-9fec-40b1dfb9a413.png)

There is any NPC in any spot in game the be max 6 meters away?

And what NPC is?

have the general shop and the fishmonsger shop.

This one fishmonsger 
![image](https://user-images.githubusercontent.com/18029568/58719776-e1589700-83a6-11e9-9d7b-6538c5a30d57.png)

And this one general 
![image](https://user-images.githubusercontent.com/18029568/58719805-f3d2d080-83a6-11e9-8bac-17138dc8c296.png)

If be general, worth sell? 
Would dismant be more proffit at end?
Thanks for tips

**Comment by SoliaRdi** [comment]
2nd npc

**Comment by andersonepk** [comment]
Thanks for reply.

I already found another thread where players say what NPC is, and now i know why have SOOO many players there LOLz, But i still more profit dismant , and sell the gold one for 500g.

Thanks for reply, will close here

**Comment by Stakerpro** [comment]
Junt found your thread friend, could you please say where is this place where the NPC is 6 meters from the fishing spot?

**Comment by andersonepk** [comment]
Move to castanica, left fish spot u will alot players there around npc.
[image: image.png]

Em dom, 9 de jun de 2019 às 21:30, Stakerpro <notifications@github.com>
escreveu:
