### ISSUE TITLE
Disconnect after fill time?

### ISSUE THREAD

**Issue by andersonepk** [SoliaRdi/auto-fishing#180]
Hi, i m having a issue when i let afk fishing.

Case 1: While sleeping
This happen 100% of the times, but i dont know how long take.

I go sleep and when i woke up fill hours late i m selecting server screen.
I would say 1 hour (maybe a little more)  afk without touch Tera.

Not Erros on log, nothing, just select server screen...
Someone more with this issue? Maybe some mod conflict?

I m using Caali proxys with this mods active.
![image](https://user-images.githubusercontent.com/18029568/58758646-7321ea80-84f4-11e9-81cf-6e858d539b9c.png)

Case 2: When i m in my work i can remote acesse my computer from work, so i dont let to many time without touch tera.
In this case i never get disconnect or something, can let my char fishing for 8 hours + with no probleme.

Any help or tips will be welcome, thanks

**Comment by SoliaRdi** [comment]
try this module https://github.com/TeraProxy/AFKer

**Comment by andersonepk** [comment]
Omg xD
Thanks so mych will test, will close. thanks thanks thanks
