### ISSUE TITLE
Auto buy Bait I

### ISSUE THREAD

**Issue by eraiser89** [SoliaRdi/auto-fishing#181]
Did you consider adding "auto buy bait I"  ? 
It d be great to afk lvl low lvl chars ....

**Comment by kath19x** [comment]
I agree! Before you can craft other bait, but now it is for level 65 only recipe.  Autobuying Bait I from npc would be a cool addition for leveling new toons.

**Comment by SoliaRdi** [comment]
No

**Comment by kath19x** [comment]
Aw.. This would be a good feature for sure!
