### ISSUE TITLE
how to swtich between selltonpc mode to filletmode? 

### ISSUE THREAD

**Issue by andersonepk** [SoliaRdi/auto-fishing#184]
Lets say i m almost running over of fillets, then i need dismant fish to get more again...
how i set off selltonpc mode to bot start dismant fishs again??

thanks

**Comment by SoliaRdi** [comment]
uh, yes. This is not clear rn. you can switch to fish filetmode bank or just fish filetmode(it will stop when filets amount reach 9000)
