### ISSUE TITLE
How to save gold fish

### ISSUE THREAD

**Issue by FXSmpL** [SoliaRdi/auto-fishing#186]
Hello yr project is very usefull, but:
1) I don't undestand how to save gold fish for saling (500 gold per fish).
2) How to use "selltonpc"
   - I stay at the river (Muricai e.g.)
   - write "fish" (for start fishing)
   - write "/8 fish selltonpc"
   - and anything doesn't work

**Comment by SoliaRdi** [comment]
1. Add them to blaklist
2. Configurate mod as you want, save settings(optional), write "fish" and manually start fishing once as mod says

**Comment by FXSmpL** [comment]
Hello,
Thx u verymuch. I'm stupid, 
I've read 

> Blacklist means, that you want this fishes to be dismantled or sold.

but there wrote

> Blacklist means, that you don't want this fishes to be dismantled or sold.

And one more question: I try to fish 24/7, but sometimes I came back at computer and saw that I'm on screen choose of character. (I think it's because I'm AFK).
I've already try `/8 fish gmmode nothing` it doesn't help.

**Comment by SoliaRdi** [comment]
Try afker module

**Comment by FXSmpL** [comment]
If I stay at AFK it means that fishing has already stoped.
And idk a reason of stoping. Console wrote that reason of stoping is "no recipe found" despite of I wrote "fish setrecipe" and it was saved.

**Comment by SoliaRdi** [comment]
Afk in tera = not moving

**Comment by SoliaRdi** [comment]
Maybe you forgot to save

**Comment by FXSmpL** [comment]
> Afk in tera = not moving

Is fishing AFK character doesn't move but he is fishing? 

I'll try install anti-AFK module. I hope that'll help me, but right now fishing stop without anything note. Just "fishing was canceled" and that's all (idk what's reason) I wasn't AFK, I moved 1 minut ago and catched 3 or more fish and it canceled ((

**Comment by FXSmpL** [comment]
I saw YR screenshot in the "**TeraCompass**" there are  some nicknames are Russian. Can u speak Russian?

**Comment by SoliaRdi** [comment]
Конечно :)

**Comment by FXSmpL** [comment]
Вот так проще )
Короче хз, чё за дела, но стою в любом месте для рыбалки, периодически почему-то говорит, что не найден рецепт для шариков, но он забит через команду, а бывает просто перестаёт ловить и всё. У тебя круглые сутки молотить получается? И по поводу продажи рыбы тоже нифига не понял, которые мерчу продать можно - окей, но их 50 и всё, а потом обычному торгашу бегаю в ручную продавать, скрипт умеет это? я не понял как работает фишка с selltonpc(написано, что рядом должен быть, но нифига не понял, это наверное имеется ввиду торговец рыбой, которому рыбу можно продать? и sellscroll тоже не понял какой свиток должен быть?

**Comment by SoliaRdi** [comment]
Для sellscroll нужны свитки или обычного торгаша или даймона(торговца кристаллами). Хз как сейчас на ауке, я в свое время коробок путешественника косарей 15 купил. Сообщение от мода о том, что не найден рецепт может быть только если не указал его. Учти что конфиг для каждого перса отдельный. Работает 24/7 :) По поводу selltonpc нужно находиться в зоне контакта(будет сообщение если это не так).

**Comment by FXSmpL** [comment]
Огромное спасибо, помог, сейчас поставил анти-афк мод, может поможет, но у меня до сего момента не получалось добиться стабильности от мода, постоянно выкидывает, по логам ничего не показывает, просто вылетело и всё. Буду мониторить.
