### ISSUE TITLE
Is there any way of manual adding fishs to blacklist without having them on inventory?

### ISSUE THREAD

**Issue by Stakerpro** [SoliaRdi/auto-fishing#188]
Wanted to add all BAF's to blacklist, plus some HG fishs.

**Comment by kath19x** [comment]
check "Available Fish.txt" for fish IDs, this is inside your mod folder

**Comment by kath19x** [comment]
then you can manually add them on the config of your character like...

	"blacklist": [
		206500,
		206501,
		206502,
		206503,
		206504,
		206505
	],
