### ISSUE TITLE
new opcodes for map 350027 NA

### ISSUE THREAD

**Issue by tsunpot** [SoliaRdi/auto-fishing#189]
C_END_FISHING_MINIGAME = 57240
C_MEDAL_STORE_BUY_ADD_BASKET = 26269
C_MEDAL_STORE_COMMIT = 63629
C_PUT_WARE_ITEM = 44967
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 30970
C_START_FISHING_MINIGAME = 36919
C_STORE_COMMIT = 46341
C_STORE_SELL_ADD_BASKET = 53110
S_FISHING_BITE = 60499
S_FISHING_CATCH = 27203
S_MEDAL_STORE_BASKET = 63265
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 37743
S_START_FISHING_MINIGAME = 60568
S_STORE_BASKET = 33177

everything should be working

**Comment by Stakerpro** [comment]
Im sorry, pretty new on using mods, what am i supposed to do with this?

**Comment by tsunpot** [comment]
open your proxy folder, then go node_modules > tera-data > map > protocol.350027.map (right click on this and edit it with notepad++). if you do not have notepad ++, google it and download it, its free

**Comment by palvaloo** [comment]
tsunpot: how do you know what the new map file is that needs edited op codes? Just would like to help out in the future, i have the packet logger.

**Comment by tsunpot** [comment]
when you start proxy and start the game, the proxy log will show you what map you are on

**Comment by cybrwolf** [comment]
@tsunpot fyi the dismantling aint working ;) just in case u want to look again for those opcodes ;)

**Comment by tsunpot** [comment]
ok will do, only checked selling

**Comment by palvaloo** [comment]
These opcodes are working. I will help you with finding for dismantling

**Comment by cybrwolf** [comment]
> These opcodes are working. I will help you with finding for dismantling

yep its why i pointed at the dismantling ;)  he did a good job at updating us .. had to lets him know

**Comment by tsunpot** [comment]
so I need a check on:
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT

@cybrwolf what aspect of dismantling did not work? did it add everything to dismantle list and if so does that mean it did not hit ok? or did it not even add items to list?

**Comment by cybrwolf** [comment]
> so I need a check on:
> C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT
> S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT
> 
> @cybrwolf what aspect of dismantling did not work? did it add everything to dismantle list and if so does that mean it did not hit ok? or did it not even add items to list?

@tsunpot wasnt adding more then 1 items to dismaltling list (havnt pushed testing further too, had to leave home)

**Comment by palvaloo** [comment]
For some reason my packet id finder is not working? I reinstalled Cali proxy and this mod

**Comment by tsunpot** [comment]
owyn fixed it, go redownload it

**Comment by palvaloo** [comment]
I did. And tried again right now. It says its enabled, but when i do a fpi S_FISHING_BITE it returns nothing

**Comment by tsunpot** [comment]
try it with a packets logger instead

**Comment by tsunpot** [comment]
OK fixed It was S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT, top comment has been edit to reflect correct opcodes for dismantling

**Comment by palvaloo** [comment]
gotcha ill try it out. I wonder why my fpi logger isnt working. It stopped working when i reinstallted tera proxy for somereason

**Comment by tsunpot** [comment]
it works on some packets not all

**Comment by palvaloo** [comment]
and packets logger, i just logc that? I don't see anything with that program

**Comment by tsunpot** [comment]
it depends on what you're logging, logc for packets starting with C or logs for packets starting with S

**Comment by palvaloo** [comment]
and where do i see the packets it logs? is it supposed to be in the proxy command prompt window or in the game proxy window

**Comment by tsunpot** [comment]
when you fist open your proxy folder, there is a txt file that you can read that is called tera-log

**Comment by cybrwolf** [comment]
> OK fixed It was S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT, top comment has been edit to reflect correct opcodes for dismantling

@tsunpot thanks for your work, appreciated

**Comment by AntiScrewdriver** [comment]
@tsunpot thank you for posting all this ! Its really appreciated.

**Comment by Stakerpro** [comment]
Guys, just out of curiosity, i have 11 files inside the map folder, but only some of them have codes inside, why is that?

Btw, Thank you for the codes @tsunpot
