### ISSUE TITLE
Manually editing blacklist isn't working.

### ISSUE THREAD

**Issue by Stakerpro** [SoliaRdi/auto-fishing#190]
I edited the blacklist manually, typed the reload command and left the char fishing, came back and saw that i got 6 BAFS with the "fish stats" but none of them were in my inventory, all dismantled.

What am i doing wrong?

**Comment by SoliaRdi** [comment]
Can you show config?

**Comment by Stakerpro** [comment]
This is the config i edited before lefting the char fishing, i put all tier 6 and BAF on it.

{
	"time": {
		"minigame": {
			"min": 4000,
			"max": 5000
		},
		"stMinigame": {
			"min": 2000,
			"max": 4000
		},
		"rod": {
			"min": 4500,
			"max": 5500
		},
		"bait": {
			"min": 250,
			"max": 750
		},
		"sell": {
			"min": 150,
			"max": 300
		},
		"contract": {
			"min": 500,
			"max": 1000
		},
		"dialog": {
			"min": 1500,
			"max": 3000
		},
		"dismantle": {
			"min": 200,
			"max": 400
		},
		"decision": {
			"min": 500,
			"max": 700
		}
	},
	"blacklist": [
		206414,
		206415,
		206416,
		206417,
		206500,
		206501,
		206502,
		206503,
		206504,
		206505
	],
	"gmmode": "stop",
	"filetmode": false
	"recipe": 204101
}

**Comment by Stakerpro** [comment]
Also, i just got a BAF and for the purpose of testing ive put him and a grade 6 on blacklist with the ingame commands on blacklist, moved them to the upper slots in inventory and they didnt get dismantled, so i think im doing something wrong with the manual edits.

**Comment by Stakerpro** [comment]
Update, its not only the blacklist that isn't working, everytime i edit my config file and type the reloadconf command ingame the mod doesn't craft too, it says "no craft recipe found" even that i did put the BAIT III code in the file.

**Comment by SoliaRdi** [comment]
Are you sure that you edit right file?

**Comment by Stakerpro** [comment]
The file with my nickname, right?

**Comment by SoliaRdi** [comment]
Yes, idk what you doing wrong. All should work fine

**Comment by Stakerpro** [comment]
It seems that is working as intended right now, i reinstalled proxy and all mods except true everful nostrum(friend told me to do it), rebooted PC and then edited the file, logged in and **DID NOT USE** the reloadconf command inside the game, its running smooth, i tested autocraft and auto dismantle and they are both fine, not sure what was causing the errrors before but its ok now, will leave the char there now while i sleep, if for some reason when i wake up all my BAF`s/Tier7 are gone again i`ll come back here, for now, thank you @SoliaRdi .
