### ISSUE TITLE
Text Bug

### ISSUE THREAD

**Issue by andersonepk** [SoliaRdi/auto-fishing#191]
When change mode by setting "fish filetmode" the message text that show on scren is always 
![image](https://user-images.githubusercontent.com/18029568/59419560-8610a680-8da1-11e9-96e3-6edbb1ea0ab0.png)

is just the message, cause bot work just fine.
need fix to show when enable and disable.

**Comment by SoliaRdi** [comment]
no, this is work as intended
![image](https://user-images.githubusercontent.com/34610562/59419859-78c0df80-8dd4-11e9-815f-1aeb8ddb0aa4.png)

**Comment by andersonepk** [comment]
ohh. bad understand of my part then xD

close thanks
