### ISSUE TITLE
PREMIUM SLOT COOLDOWN

### ISSUE THREAD

**Issue by Foks5000** [SoliaRdi/auto-fishing#192]
S_START_COOLTIME_ITEM does not come in response to C_USE_PREMIUM_SLOT. Instead a separate packet for the premium slot.

**Comment by SoliaRdi** [comment]
packet name for replace? can't find anything

**Comment by Foks5000** [comment]
id 24148 for version 350024(RU). I don`t know which name.

int32 set
int32 slot
int32 amount  #??? -1
int32 cooldownRemaining

**Comment by SoliaRdi** [comment]
Thi opcode not public, so no reasons to add more custom defs+opcodes. Such issue not critical
