### ISSUE TITLE
Does auto-fishing send to the game server that you are afk?

### ISSUE THREAD

**Issue by Zezo12345** [SoliaRdi/auto-fishing#193]

**Comment by SoliaRdi** [comment]
idk

**Comment by Zezo12345** [comment]
I ask about your mod if you arent touching your pc and went afk while using it, does the server see you as afk or active?

**Comment by Zezo12345** [comment]
For security what should be your status? afk or active?

**Comment by Zezo12345** [comment]
I know that you have gm mode but what if they now start to ban depending on your status while auto- fishing?

**Comment by Zezo12345** [comment]
Nvm dont wanna scare ppl.
