### ISSUE TITLE
Blacklist fishes were sold

### ISSUE THREAD

**Issue by FXSmpL** [SoliaRdi/auto-fishing#194]
Привет, у меня трабл опять (
Не работает блеклист, Если конкретнее, то:
Ничего не менял, съездил в отпуск, вернулся, не работает блеклист(у меня уже были внесены все шедевры в настройки, но увидел, что рыба как разбирается, так и продаётся, прописал ещё раз /8 fish blacklist add и через ctrl ссылку на рыбу, пишет, что всё добавлено, но когда инвентарь заполняется - всё продаёт без исключения.

**Comment by SoliaRdi** [comment]
Протестировал. Все работает отлично
