### ISSUE TITLE
C_STORE_COMMIT - why stuck at sell to npc?

### ISSUE THREAD

**Issue by trev44** [SoliaRdi/auto-fishing#195]
Loads 6 fish and does not continue

**Comment by kath19x** [comment]
prolly wrong OPCODES, which server do you play?

**Comment by SoliaRdi** [comment]
smth like #61

**Comment by tsunpot** [comment]
mines not working either but we are logging the same opcode every time for C_STORE_COMMIT every time
on NA

**Comment by SoliaRdi** [comment]
you can log incorrect opcode all time too. As always, recheck def+opcode. I publish 100% correct opcodes only for RU

**Comment by ap0521** [comment]
It's not opcode related, it's likely due to new proxy being much faster and client too slow. On old proxy version with same opcodes it works, but on new proxy version it gets stuck.

**Comment by SoliaRdi** [comment]
i dont see any logic here, packet sended with delay of 300ms

**Comment by ap0521** [comment]
Not sure either, old proxy works, new one gets stuck. I'll try playing with the delays and see if something works.

**Comment by SoliaRdi** [comment]
maybe troubles with line 91, i made this for ppls with old def

**Comment by SoliaRdi** [comment]
most likely this(incorrect def on user side, def was updated in Mar 31, 2019). and hidden fix for that stop working

**Comment by SoliaRdi** [comment]
cant find way to retrieve not compiled def, and dont want to overwrite it now, looking back that was bad solution. @trev44 update commit definition
