### ISSUE TITLE
FISHING CANCELLED all the  time T_T

### ISSUE THREAD

**Issue by kath19x** [SoliaRdi/auto-fishing#196]
Why does my character once in a while just stop fishing? It says fishing cancelled, tried debug mode, nothing unusual.  It just stops then you can just cast the fishing rod again and will continue, maybe a GM is passing by  and it stops? Can someone help me? Thanks!

**Comment by SoliaRdi** [comment]
low delays for throwing rod or client lags during animation

**Comment by tsunpot** [comment]
itll stop as well if you arent close enough to the waters edge/not the right angle

**Comment by kath19x** [comment]
I re-adjusted my timeouts, it might be the lag+edited timeouts that I did, I will monitor it.  Thanks for the replies

**Comment by kath19x** [comment]
Ok I get it rarely now but it is still there. Prolly the timeouts needs to be fixed some more.

**Comment by SoliaRdi** [comment]
i dont see any logic here, packet sended with delay of 300ms
