### ISSUE TITLE
Dismantling instead of Selling

### ISSUE THREAD

**Issue by SSmurf99** [SoliaRdi/auto-fishing#199]
Hi there,

So i have everything running ok and all but sometimes when my inventory is full it chooses to dismantle fish instead of selling to npc ( i have selltonpc ON) even tho i already have enough fish filet for bait and all, so any idea why this happens?

Side note: i am not sure what fishfilet mode does or what disabling really do in general so if possible please tell me if it has any impact.

Edit: i noticed something, is it supposed to prioritize dismantling instead of selling if i have less than 60 fish filets in my inventory? 

Thanks.

**Comment by SoliaRdi** [comment]
Your edit is correct https://github.com/SoliaRdi/auto-fishing/blob/master/index.js#L557

**Comment by SSmurf99** [comment]
alright ty and keep up the great work :)
