### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by q848899** [SoliaRdi/auto-fishing#20]
I only do once decomposition
And then it doesn't Continue behind
It's just stuck
I don't know why 
All other functions are normal
Please help me
I play TW server

**Comment by q848899** [comment]
Can you point out the problem for me?
Sorry, my English is poor. is Machine Translation

**Comment by SoliaRdi** [comment]
After decomposition decompose window closing?

**Comment by q848899** [comment]
Not close

**Comment by q848899** [comment]
I closed manually and continued to decompose at the opening meeting

**Comment by SoliaRdi** [comment]
I don't have TW opcodes, so it can be wrong S_RP_COMMIT_DECOMPOSITION_CONTRACT opcode

**Comment by q848899** [comment]
You can upload
S_RP_COMMIT_DECOMPOSITION_CONTRACT.1.def?
thankyou
