### ISSUE TITLE
Do not dismantle with full inventory [NA]

### ISSUE THREAD

**Issue by weltonbraga** [SoliaRdi/auto-fishing#201]
After yesterday's update of the Tera-Toolbox (Merge pull request #21 from tera-toolbox/beta - 5f0c65c).
I tested with few fillets in the inventory, the 'dismantle' action is not being called. Maybe 'mod.game.inventory.bagSize' and 'mod.game.inventory.bag.length' are not working correctly.
Even with only 2 free slots in inventory it calls 'userod'.

**Comment by SoliaRdi** [comment]
should be fixed.
