### ISSUE TITLE
Not picking up fishes to sell to npc

### ISSUE THREAD

**Issue by wujorogal** [SoliaRdi/auto-fishing#202]
You freshly fixed issue with fisher stopping when inventory is full - now he opens the npc window but dosnt actually sell the fishes
Just opening the npc and getting stuck there

**Comment by SSmurf99** [comment]
same issue here

**Comment by SoliaRdi** [comment]
caali added  item.slot -= 40; maybe issue with this too and C_STORE_SELL_ADD_BASKET slot now need +40, but im not sure rn

**Comment by SoliaRdi** [comment]
try now

**Comment by tsunpot** [comment]
its working for me

**Comment by SoliaRdi** [comment]
nice
