### ISSUE TITLE
Getting errors

### ISSUE THREAD

**Issue by Shippou5** [SoliaRdi/auto-fishing#203]
[HIDDEN]

**Comment by SoliaRdi** [comment]
Error is repeatable?

**Comment by P-Unit** [comment]
whoever responded to my last question on last post that was recently removed, thank you.  you're a gentlemen and a scholar.

**Comment by SoliaRdi** [comment]
I didn't remove any issues 🤔

**Comment by P-Unit** [comment]
someone must have, there were like 4 topics like 2h ago, now theres only one. well at least visible to me, i dunno i just made an account here to comment lol but the one that got deleted solved my problem, he said add this --->

C_END_FISHING_MINIGAME = 61382
C_MEDAL_STORE_BUY_ADD_BASKET = 57478
C_MEDAL_STORE_COMMIT = 51720
C_PUT_WARE_ITEM = 42110
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 44077
C_START_FISHING_MINIGAME = 48769
C_STORE_COMMIT = 31801
C_STORE_SELL_ADD_BASKET = 59642
S_FISHING_BITE = 21035
S_FISHING_CATCH = 37928
S_MEDAL_STORE_BASKET = 50795
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 58645
S_START_FISHING_MINIGAME = 49691
S_STORE_BASKET = 59976

to the file protocol.353337.map in your node module, tera data, map folder.

it fixed everything back to normal. thanks again

**Comment by SoliaRdi** [comment]
I comment that pinkie pie posted full list of opcodes, so...
To original issue, seams like random bug. Idk how it went so wrong, cant repeat. I can only make fix for proxy not crash in the end, but later
