### ISSUE TITLE
Call back

### ISSUE THREAD

**Issue by johanplima** [SoliaRdi/auto-fishing#206]
http://prntscr.com/oj7m4chttp://prntscr.com/oj7m4c

I'm getting this error after today att, is that normal?

**Comment by Liliaina** [comment]
I'm getting this too

**Comment by SoliaRdi** [comment]
Update opcodes

**Comment by johanplima** [comment]
@SoliaRdi Changed the protocol, but still dont work. I'm missing something?

**Comment by SoliaRdi** [comment]
probably, recheck folder where you change protocol, version

**Comment by johanplima** [comment]
I move that http://prntscr.com/ojjkkh
to here
" Move the files inside the defs folder into Your-Proxy-Folder/node_modules/tera-data/protocol.
Move or merge the protocol files into Your-Proxy-Folder/node_modules/tera-data/map." 
Right?

**Comment by SoliaRdi** [comment]
to Your-Proxy-Folder/node_modules/tera-data/map - yes

**Comment by SoliaRdi** [comment]
eu is protocol.353338.map

**Comment by johanplima** [comment]
I'm from NA, but still showing the first link http://prntscr.com/oj7m4c

**Comment by johanplima** [comment]
Thanks!
