### ISSUE TITLE
NA Opcodes

### ISSUE THREAD

**Issue by quetall12** [SoliaRdi/auto-fishing#207]
C_END_FISHING_MINIGAME = 61382
C_MEDAL_STORE_BUY_ADD_BASKET = 57478
C_MEDAL_STORE_COMMIT = 51720
C_PUT_WARE_ITEM = 42110
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 44077
C_START_FISHING_MINIGAME = 48769
C_STORE_COMMIT = 31801
C_STORE_SELL_ADD_BASKET = 59642
S_FISHING_BITE = 21035
S_FISHING_CATCH = 37928
S_MEDAL_STORE_BASKET = 50795
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 58645
S_START_FISHING_MINIGAME = 49691
S_STORE_BASKET = 59976

**Comment by P-Unit** [comment]
Sorry but, can u tell a noob like me where to put these?

**Comment by quetall12** [comment]
Go to your proxy folder mine looks like this; CaaliTeraProxy\node_modules\tera-data\map, then look for protocol.353337.map, open it with notepad, copy and paste them OPcodes save it then you're good.

**Comment by SoliaRdi** [comment]
Duplicate of #204
