### ISSUE TITLE
Confused about setrecipe - Auto bait craft

### ISSUE THREAD

**Issue by johanplima** [SoliaRdi/auto-fishing#211]
I craft one time the bait, then I use de command, and when I'm out of bait, fishs become filled (until then perfect) but then the setrecipe command was supposed to activate right? And do more bait. 
I edit index.js file for filled all fishs, but not the bfa. But I guess that's not the problem, or is it? I'm very noob in programming, I don't understand anything! haha
http://prntscr.com/ojpkp2

**Comment by SoliaRdi** [comment]
you dont understand anything, but already edited script 🤔
use blacklist and readme
