### ISSUE TITLE
Activating filet mode back again

### ISSUE THREAD

**Issue by Frostwaffles** [SoliaRdi/auto-fishing#216]
I deactivated filet mode with " /8 fish filetmode " and set it on sell to npc. But right now i cant activate filetmode back. i tried typing  " /8 fish filetmode " and " /8 fish reloadconf " can you add an option to activate filetmode back again?  if there is , i am really sorry for being stupid.

**Comment by SoliaRdi** [comment]
Right now there only one settings for fillets. But im lazy to change this. /8 fish filetmode bank or nothing with /8 fish filetmode

**Comment by SoliaRdi** [comment]
And all other modes not related to fillets using same field. Yes, this can be confusing when manually editing the config
