### ISSUE TITLE
OFFTOPIC help question: Account blocked after 4th account login? 

### ISSUE THREAD

**Issue by zokiopp** [SoliaRdi/auto-fishing#217]
First i apologize for this off topic question but i cant seem to find any answers on the web. Im aware that everyone is using multiclient here for fishing and im asking:  is there a way to login more than 4 chars on 1 PC since after the 4th login i get account blocked on the launcher on every next try. Thanks in advance

**Comment by SoliaRdi** [comment]
on ru no any limitations, so idk :(

**Comment by SoliaRdi** [comment]
probably noone answer you. If not NA try to block iesnare in hosts, idk if this helps
