### ISSUE TITLE
Error running callback for command "fish"

### ISSUE THREAD

**Issue by Jay00022** [SoliaRdi/auto-fishing#219]
Hi there! I've read the previous threads on fixing this issue but it doesnt seem to be working for me..
I've tried copying the code into protocol.347375 and protocol.344895 but neither of them are working for me.. any way you could help me out?
thank you v much

**Comment by SoliaRdi** [comment]
You are doing smth wrong. Write what you doing step by step. folders, etc

**Comment by Jay00022** [comment]
protocol.347375 has:
C_END_FISHING_MINIGAME = 37147
C_MEDAL_STORE_BUY_ADD_BASKET = 26233
C_MEDAL_STORE_COMMIT = 23731
C_PUT_WARE_ITEM = 38072
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 22532
C_START_FISHING_MINIGAME = 57483
C_STORE_COMMIT = 34904
C_STORE_SELL_ADD_BASKET = 43470
S_FISHING_BITE = 57273
S_FISHING_CATCH = 50270
S_MEDAL_STORE_BASKET = 38431
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 50250
S_START_FISHING_CHARGE = 26383
S_START_FISHING_MINIGAME = 23036
S_STORE_BASKET = 41810 

and protocol.344895 is now empty

**Comment by SoliaRdi** [comment]
you dont ansver

**Comment by Artligth** [comment]
Mine is making the same error..

@SoliaRdi I install and used your mod before the update (20 days ago) and it worked normal. Yesterday when I came back to use does not work and give these errors.

Print  error in game: [https://prnt.sc/onl8fz]()
Print  error in proxy: [https://prnt.sc/onl8wh]()

I tried to redownload the mod, followed the tutorial according to what you put, but it does not work and gives this error.

My proxy is the TERAToobox.

I researched this error and it looks like it's a problem with the maps files (I read that they are probably outdated)

I tried to solve the problem but couldn't.

**Comment by SoliaRdi** [comment]
Unmapped packet = you need to install opcodes for your region, like in readme in \node_modules\tera-data\map

**Comment by SoliaRdi** [comment]
read last note too. Your current protocol version typed in console
![image](https://user-images.githubusercontent.com/34610562/62390774-c0115400-b56b-11e9-9b73-2a340f740295.png)

**Comment by Artligth** [comment]
Well, i play in NA, so I tried to get the maps as you said from [https://github.com/tera-proxy/tera-data/tree/master/map](https://github.com/tera-proxy/tera-data/tree/master/map)

![printmaps](https://user-images.githubusercontent.com/53622807/62392257-5f6b2280-b53d-11e9-80bc-d1e3255dc1c9.png)

I took these maps and put them in the folder (proxy-Folder/node_modules/tera-data/map), but the ERROR not fixes.

=/

**Comment by SoliaRdi** [comment]
These 3 can be not for NA. Look at protocol version in console

**Comment by SoliaRdi** [comment]
For example 
![image](https://user-images.githubusercontent.com/34610562/62392589-8000a000-b570-11e9-82d4-9c661e9a5d7c.png)

**Comment by Artligth** [comment]
Nice, mine version is 35337, let me try change and see what happens

**Comment by SoliaRdi** [comment]
Dev uploaded opcodes for 4 regions in 1 commit. They are not the same, you had to think about this =)

**Comment by Artligth** [comment]
Yes. I tried to disable auto-update to test if the proxy loads 353342 But the proxy dont change, it load only 353337 =/

Another strange thing, look how the map 353337 is:

![protocol 353337](https://user-images.githubusercontent.com/53622807/62393439-8e36c800-b540-11e9-8266-bc4f9c83e9a0.png)

Is empty? why?

So there is no way to make the proxy load the new map? = /

**Comment by Jay00022** [comment]
I use toolbox and from NA.
CaaliTeraProxy>node_modules>tera-data>map
this is where my protocol files are.

**Comment by SoliaRdi** [comment]
Artligth from NA too and that says thay you should have 353337 protocol too. Not 347375 or 344895

**Comment by Artligth** [comment]
Yes, the current protocol NA (caally or pinkie proxy) is 3353337. With the exception that I use proxy free.

I don't know if the protocol changes for paid proxies.

**Comment by SoliaRdi** [comment]
idk about paid proxies and why they exist
