### ISSUE TITLE
ERROR uncaught exeption

### ISSUE THREAD

**Issue by zokiopp** [SoliaRdi/auto-fishing#220]
![soliardi](https://user-images.githubusercontent.com/49364142/62360568-5b2d0e00-b519-11e9-8b8e-fe189c98dc7f.PNG)
I saw SoliaRdi text in the error so i think its something with this module. 
This dces my accounts after several hours of fishing.

**Comment by SoliaRdi** [comment]
lol. That someone named folder with my nickname. Better to rename it without soliardi, especially if you want help in toolbox disc.
