### ISSUE TITLE
fail to catch tier 10 fish

### ISSUE THREAD

**Issue by siambr** [SoliaRdi/auto-fishing#222]
look like the same problem to this post but it's did happen again.
https://github.com/SoliaRdi/auto-fishing/issues/131

**Comment by SoliaRdi** [comment]
do you use any bufs for fishing?

**Comment by siambr** [comment]
use only fish salad

**Comment by SoliaRdi** [comment]
Probably no one get tier 10 rod. Idk why its first report after long time. This is result of skip baf option, and under salad fish level is lowered. Current baf level(11) under salad in code is 7 (7.7 calculated, but if i remember correct packet send it without rounding in greater side). With tier 10-7 calculated. So idk how to determite baf in this case

**Comment by SoliaRdi** [comment]
So no solution in this point

**Comment by siambr** [comment]
so turn off fish salad then?

**Comment by SoliaRdi** [comment]
or skipbaf or fish salad, yes

**Comment by siambr** [comment]
ok. thank you.
