### ISSUE TITLE
NA

### ISSUE THREAD

**Issue by XelZero** [SoliaRdi/auto-fishing#226]
Opcodes arent avil for NA - even in the poxy's data

**Comment by Potaatoo1** [comment]
already has opcode for NA ?

**Comment by palvaloo** [comment]
No havent seen any

**Comment by SoliaRdi** [comment]
¯\_╏ ՞ ︿ ՞ ╏_/¯

**Comment by palvaloo** [comment]
I tried manually searching but the fpi logger thing doesnt work for any opcode but like 1, and packetlogger is extremely complicated given there are so many OPcodes. If solia you know of a way of finding them with packetlogger or another mod, can you let us know?

**Comment by SoliaRdi** [comment]
NA added
