### ISSUE TITLE
Fairy Snakeheads getting dismantled even after pushed to blacklist

### ISSUE THREAD

**Issue by Shippou5** [SoliaRdi/auto-fishing#228]
https://puu.sh/E9n9M/205a3c2016.png

I also confirmed with the main JSON file.

"blacklist": [
		206502,
		206503,
		206504,
		206505,
		206500,
		206501,
	],

Why does it keep dismantling the baf no matter what I do?

**Comment by SoliaRdi** [comment]
i just checked and everything work fine

**Comment by SoliaRdi** [comment]
Tested again and all fine. Btw what is main JSON file? We have only per character configs
