### ISSUE TITLE
Character stops fishing for no reason

### ISSUE THREAD

**Issue by Shippou5** [SoliaRdi/auto-fishing#229]
Full open inventory, 100 baits available, it still stops fishing every now and then

**Comment by SoliaRdi** [comment]
seems like only you have problems. Nothing changed in this part.

**Comment by PiBuddy** [comment]
this happens to me once in a while, i wonder if it is tied to lag and needs some retry mechanism to check and see if we are still fishing.

**Comment by SoliaRdi** [comment]
there exist idle timer. For example item-cache can fuckup any module than use inventory

**Comment by Shippou5** [comment]
The issue still happens so I redownloaded the fishing module just now, followed the installation instructions perfectly and then removed all of the other modules to make sure there is no clashing like with item-cache and the same issue repeats, sometimes my character just flat-out stops fishing

**Comment by SoliaRdi** [comment]
fishing can be stoped due to fps issues or lags. If this happen all time try to increase delays
