### ISSUE TITLE
the dismantle error still happen after the fixes

### ISSUE THREAD

**Issue by Hydra4269** [SoliaRdi/auto-fishing#23]
I just got 102/104 on inventory and the auto-dismantle can't put any fishes on the dismantle windows cuz the error "item can't be dismantled" still happens, not 100% tho.

![screenshot_13](https://user-images.githubusercontent.com/45980748/50192416-f5d13780-0310-11e9-8398-607e80a9bb29.jpg)

**Comment by SoliaRdi** [comment]
check now

**Comment by SoliaRdi** [comment]
someone provide me incorrect sea opcode, redownload it

**Comment by Hydra4269** [comment]
I'll keep testing but I play on NA tho
