### ISSUE TITLE
Fishing will dismantle first time around when selltonpc option set

### ISSUE THREAD

**Issue by PiBuddy** [SoliaRdi/auto-fishing#233]
when i have no fillets in my inventory, the first time my inventory is full, the mod will dismantle fish instead of sell to NPC when i have the selltonpc option set.  I've not yet tested if this happens if there are fillets in my inventory.  To be sure there wasn't a conflict i reinstalled proxy from scratch and only included this mod, and it still happens.

**Comment by SoliaRdi** [comment]
mod checks if there 60 fillets in inv and only then decide about dismantling

**Comment by PiBuddy** [comment]
so we should keep at least 60 fillets in inventory if we we want to avoid this behavior?

**Comment by SoliaRdi** [comment]
yes, this was made before increased worm limit. But well, im not going to change this

**Comment by PiBuddy** [comment]
ok, fair enough.

**Comment by SoliaRdi** [comment]
![image](https://user-images.githubusercontent.com/34610562/63887450-80f8e600-c9e5-11e9-9cff-58e21c4845f6.png)
