### ISSUE TITLE
Sometimes all fish aren't dismantled or sold to npc.

### ISSUE THREAD

**Issue by PiBuddy** [SoliaRdi/auto-fishing#234]
Sometimes i notice that when my inventory. the dismantle/sell option will not clean out my inventory of all fish but seem to only do 1 load of fish and then start fishing again instead of getting rid of all fish then restart.  To be sure there was no conflict i reinstalled proxy from scratch and used only this mod (besides the defaults that come with proxy).

**Comment by SoliaRdi** [comment]
dismantle load only 20 fishes. Selling should load almost all fishes

**Comment by PiBuddy** [comment]
ok, then i guess this is tied to my other issue about dismantling with no fillets in inventory.  If there are fillets when 1st full inventory action happens then this behavior should disappear correct?
