### ISSUE TITLE
Character refuses to put fish filet in the summoned bank

### ISSUE THREAD

**Issue by Shippou5** [SoliaRdi/auto-fishing#236]
My character summons banker at 9100 fish filets and then...does nothing, it should be placing the filets there, no?

**Comment by SoliaRdi** [comment]
do you update defs?

**Comment by Shippou5** [comment]
Yeah I did

**Comment by SoliaRdi** [comment]
no any errors in console?

**Comment by Eli048** [comment]
Same problem and no errors in console

**Comment by SoliaRdi** [comment]
On toolbox right? I can check tomorrow, weird error

**Comment by Eli048** [comment]
Yeah

**Comment by SoliaRdi** [comment]
And what you see before bot stuck? Like dialog or bank window, or nothing after banker appear?

**Comment by Eli048** [comment]
Banker appear opened and the fish fillet nothing move to bank

**Comment by Shippou5** [comment]
Well the module summoned my banker 20 times and still did not put any filets in so I am putting my banker scrolls in the bank until this is fixed I don't want the module using all of them for no reason

**Comment by SoliaRdi** [comment]
tbh still dk what reason of this bug. Like nothing changed except newer def

**Comment by Eli048** [comment]
When patch 85 realesed coming this wierd bug

**Comment by SoliaRdi** [comment]
if someone can. I need log from packets logger with moment of banker interactions by mod. send to hop4ey@yandex.ru

**Comment by Shippou5** [comment]
No clue how to get log from packets logger, also the recent EU hotfix broke fishing

**Comment by SoliaRdi** [comment]
recent hotfix broke EU

**Comment by SoliaRdi** [comment]
try with updated def

**Comment by SoliaRdi** [comment]
but no, i dont think it affect anything

**Comment by Eli048** [comment]
Bank bug still

**Comment by SoliaRdi** [comment]
cant test full route with fillets. On RU from packets side all ok, like notning changed. Idk reason of bug. Until someone found fix this function will be deprecated

**Comment by SoliaRdi** [comment]
fml, found typo

**Comment by SoliaRdi** [comment]
fixed. Im blind tho =_=
