### ISSUE TITLE
Java error when trying to sell to npc

### ISSUE THREAD

**Issue by Stakerpro** [SoliaRdi/auto-fishing#237]
![Screenshot_2](https://user-images.githubusercontent.com/51405349/63912745-5407fb80-ca04-11e9-8c24-26ac2ac909a7.png)

**Comment by SoliaRdi** [comment]
read error

**Comment by Stakerpro** [comment]
> read error

I did, but i dont know what to do to fix it, im sorry.

**Comment by SoliaRdi** [comment]
Download and install def

**Comment by Stakerpro** [comment]
Ok, tyvm.
