### ISSUE TITLE
S_STORE_BASKET and ban

### ISSUE THREAD

**Issue by DaXmAn** [SoliaRdi/auto-fishing#238]
Is this really an issue?
https://i.imgur.com/wP5h52D.png

**Comment by SoliaRdi** [comment]
yes
![image](https://user-images.githubusercontent.com/34610562/64061967-d43b8600-cbe9-11e9-9920-3d8e70171418.png)

**Comment by DaXmAn** [comment]
well I didn't explicitly asked for help :) I asked generic question about packets. So we can get ban because of using selltonpc option?

**Comment by SoliaRdi** [comment]
exactly this - no. But if all would stay near npc, admin may have suspicions ;)

**Comment by DaXmAn** [comment]
oh man, sorry I deleted my comment, I saw you closed issue :) Aparently in EU gameforge closes their eyes, because often many many characters fish near npc.

so is not like sending this packet is incorrect or illegal?

**Comment by SoliaRdi** [comment]
you receive this packet

**Comment by DaXmAn** [comment]
ah ok, sorry I am still learning about programming tera proxy
