### ISSUE TITLE
Not a coding releated issue, just me not knowing how to install

### ISSUE THREAD

**Issue by nicolai0007** [SoliaRdi/auto-fishing#239]
So I can't locate the proxy folder for Tera. Is it because I'm using the steam version? Or is there a spot where it's usually hidden?

**Comment by SoliaRdi** [comment]
1) No. 2) You select folder during installation

**Comment by nicolai0007** [comment]
The only thing i selected while installing was to have the main files on my d drive
![tera folder](https://user-images.githubusercontent.com/54758280/64076418-f6ee9d00-ccc4-11e9-8313-c8f9a37fccbe.JPG)

**Comment by SoliaRdi** [comment]
Why you ask me? Its not even proxy related questions xD
