### ISSUE TITLE
Problems with dismantling

### ISSUE THREAD

**Issue by bryanfuryz** [SoliaRdi/auto-fishing#24]
After my bag is full, it will start dismantling random 20 fish, then stops. I need to manually click one fish then it will start randomly picking fish for dismantling again. I've been getting "You cant use that now" or "The item cannot be dismantled".

**Comment by SoliaRdi** [comment]
check now

**Comment by SoliaRdi** [comment]
someone provide me incorrect sea opcode, redownload it
