### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by ascit1234545** [SoliaRdi/auto-fishing#241]
I did both of these steps:
Move the files inside the defs folder into Your-Proxy-Folder/node_modules/tera-data/protocol.
Move or merge the protocol files into Your-Proxy-Folder/node_modules/tera-data/map.
But the bot doesnt work. When ı type /8 fish it says unknown command.Do ı have something else I need to do?
Please help, thanks in advance.

**Comment by SoliaRdi** [comment]
look in console

**Comment by ascit1234545** [comment]
Apparently I don't have the mod installed, I just have the defs. Where do I install the mod from?

**Comment by SoliaRdi** [comment]
:D

**Comment by ascit1234545** [comment]
?

**Comment by SoliaRdi** [comment]
like... install mod. How tf it shoud work then? Download and put in mods folder

**Comment by ascit1234545** [comment]
Like making a folder in mods folder, renaming it to fish bot, copying all the things including readme and protocol and all the stuff ?  Where do I install the mod from ? Aren't these files the mod itself? If not then where do I get the mod ?

**Comment by ascit1234545** [comment]
Oh my God, can't believe how stupid I am. Sorry for troubling you and thank you for bearing with me.
