### ISSUE TITLE
kindly please help me with logging one packet

### ISSUE THREAD

**Issue by DaXmAn** [SoliaRdi/auto-fishing#243]
I struggle with S_STORE_BASKET packet logging, I use alex-packet-id-finder and your PacketsLogger, and as far as I know S_STORE_BASKET should pop, when you open merchant NPC window right? Which action should I perform in game so logger will catch it?

**Comment by SoliaRdi** [comment]
There's no def for this packet. So you cant log it with this mod. Use search in issues

**Comment by DaXmAn** [comment]
ok I think I found it, I'm testing with ID if fount... I hope this is still valdi :)

> (...)  the S_STORE_BASKET triggers after the C_STORE_SELL_ADD_BASKET. They appear as 'null' in the "tera-log" for some reason after the new patch. Last patch it did show "C_STORE_SELL_ADD_BASKET" so that's how you could find the S_STORE_BASKET easier. You'll see (id 49467) null , which is "C_STORE_SELL_ADD_BASKET" and right after it there should be (id 27932) null, which is "S_STORE_BASKET". (...)

_Originally posted by @kyogo123 in https://github.com/SoliaRdi/auto-fishing/issues/56#issuecomment-463399245_

**Comment by DaXmAn** [comment]
ok... so... I think it is not working... not sure why, this time logger even showed me packet name, and ID is the same.. but bot stopped after it opened merchant window where you can put items to buy/sell. This is what I got from the log, and I use these IDs in protocol map. Any ideas?

[16:11:45:840] ->          	 C_STORE_SELL_ADD_BASKET    (id 62760)
{
    "cid": "140737490849448",
    "npc": 136041,
    "item": 206009,
    "quantity": 1,
    "pocket": 0,
    "slot": 106
}
[16:11:45:875] <-          	    (id 59862) S_STORE_BASKET

**Comment by SoliaRdi** [comment]
give me hex of S_STORE_BASKET

**Comment by SoliaRdi** [comment]
https://github.com/tera-proxy/tera-data/commit/106054bfcd14c9e2368f292ca514b22be9224dd1

**Comment by DaXmAn** [comment]
[16:11:45:875] <-          	    (id 59862) S_STORE_BASKET
00000004: 00000000 01003000 A80E2600 00800000 69130200 00000000 00000000 00000000  ......0.(.&.....i...............
00000024: 00000000 E8030000 00000000 30000000 B9240300 01000000 00000000 00000000  ....h.......0...9$..............
00000044: 000000                                                                   ...

4700d6e90000000001003000a80e2600008000006913020000000000000000000000000000000000e80300000000000030000000b9240300010000000000000000000000000000

**Comment by SoliaRdi** [comment]
check it if you want

**Comment by SoliaRdi** [comment]
Opcode is correct btw

**Comment by DaXmAn** [comment]
exactly :D I will confirm again in couple minutes if this works, I restarted everything again, whole PC...

**Comment by DaXmAn** [comment]
I checked all my opcodes based on pinkipi list and I had wrong id for C_STORE_COMMIT :( I dunno how that could happen, will confirm in a minute if that was the issue

**Comment by DaXmAn** [comment]
Yeah that was it, I am so sorry for trouble. But at least I learned how to get id for S_STORE_BASKET :) Thank you for your time SoliaRdi
