### ISSUE TITLE
cannot setrecipe anymore

### ISSUE THREAD

**Issue by Reny900** [SoliaRdi/auto-fishing#25]
was switching from bait II to bait III, and the chat kept saying "incorrect item ID"
ended up crafting bait II instead
![image](https://user-images.githubusercontent.com/19189602/50222243-fc56c200-0397-11e9-8860-43a08844ca59.png)

Modifying the config file manually fixes this

**Comment by SoliaRdi** [comment]
/8 fish setrecipe set last manually used recipe for craft. Then /8 fish setbait link.(to new bait) after this you can /8 fish save.
