### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jay00022** [SoliaRdi/auto-fishing#259]
Uncaught excepton:
Error: dispatch write: failed to generate C_STORE_SELL_ADD_BASKET <2>?:
no definition found for message

**Comment by SoliaRdi** [comment]
https://github.com/SoliaRdi/auto-fishing/blob/master/defs/C_STORE_SELL_ADD_BASKET.2.def

**Comment by Jay00022** [comment]
what do I do with this code? where do I put it?

**Comment by SoliaRdi** [comment]
![image](https://user-images.githubusercontent.com/34610562/65429565-09b94500-de1f-11e9-99c9-dcb05a5f88b4.png)

**Comment by Jay00022** [comment]
how do I download this particular folder? from the link u sent me

**Comment by SoliaRdi** [comment]
![image](https://user-images.githubusercontent.com/34610562/65429978-c27f8400-de1f-11e9-8216-f9f781e2c725.png)

**Comment by Jay00022** [comment]
i deleted and redownload but i still have the same error.
when i open the link u sent me for the new basket file, there is no download link

**Comment by SoliaRdi** [comment]
Then you doing something wrong. Task is simple af

**Comment by SoliaRdi** [comment]
Reinstall mod then, if you cant put files

**Comment by Jay00022** [comment]
i realize it's simple but i just need someone to explain what im supposed to do. create a random text file within the folder and input that code?

**Comment by SoliaRdi** [comment]
hmm, gonna repeat in text format.
1) Downoad zip. Unpack it
2) Move the files inside the defs(in unpacked folder/defs) folder into Your-Proxy-Folder/node_modules/tera-data/protocol
