### ISSUE TITLE
one fish problem

### ISSUE THREAD

**Issue by DaXmAn** [SoliaRdi/auto-fishing#260]
With updated opcodes, while trying to sell fish to npc, module puts one fish into basket and stops.

**Comment by SoliaRdi** [comment]
I suggest to stop mod using untill i see changes. Idk what defs was changed

**Comment by SoliaRdi** [comment]
But this is sounds like unrelated to them

**Comment by DaXmAn** [comment]
ok, I'll wait for you to check this, EU is using protocol 356368 now.

**Comment by SoliaRdi** [comment]
Actually. Sounds like wrong basket packet. But i'll write here when i ckeck everything

**Comment by zokiopp** [comment]
Excuse me, where can i download these new opcodes that acually work? Thanks

**Comment by DaXmAn** [comment]
> Actually. Sounds like wrong basket packet. But i'll write here when i ckeck everything

is it about this?

[15:41:48:31] <-          	    (id 25471) S_STORE_BASKET
00000004: 82820700 00800C00 28072600 00800000 00000000 01000000 00000000           ........(.&.................

20007f638282070000800c002807260000800000000000000100000000000000

**Comment by DaXmAn** [comment]
ok so the thing is logger is missleading on S_STORE_BASKET packet, is showing name with id, but ID actually is different

**Comment by SoliaRdi** [comment]
logger is not missleading, you give him wrong info

**Comment by SoliaRdi** [comment]
logger is not supposed to magically define opcode for you

**Comment by DaXmAn** [comment]
what is required for your PacketLogger so it interpret this packet correctly? :)

**Comment by SoliaRdi** [comment]
Correct protocol

**Comment by DaXmAn** [comment]
you mean definition of S_STORE_BASKET in TeraToolbox\node_modules\tera-data\protocol folder?

**Comment by SoliaRdi** [comment]
You probably missunderstand purpose of raw logger. This is not fpi

**Comment by DaXmAn** [comment]
most probably, you are the guru and master here :) I am just humble padwan :D

**Comment by SoliaRdi** [comment]
Logger set in packet header already known opcodes.
