### ISSUE TITLE
NA opcodes (356367)

### ISSUE THREAD

**Issue by tsunpot** [SoliaRdi/auto-fishing#263]
C_STORE_SELL_ADD_BASKET = 43999
C_STORE_COMMIT = 29080
C_END_FISHING_MINIGAME = 47064
C_PUT_WARE_ITEM = 20943
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 20398
C_START_FISHING_MINIGAME = 61003
S_FISHING_BITE = 34529
S_FISHING_CATCH = 39272
S_FISHING_CATCH_FAIL = 43549
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 29282
S_START_FISHING_MINIGAME = 41973
S_STORE_BASKET =

I need help mapping S_STORE_BASKET but everything else here works

**Comment by SoliaRdi** [comment]
already aswered many times about S_STORE_BASKET =(

**Comment by tsunpot** [comment]
So is store basket no longer required to sell?

**Comment by SoliaRdi** [comment]
How did you come to this thought?

**Comment by tsunpot** [comment]
I remember having some conversation with you about this but cant remember specifics at all

**Comment by SoliaRdi** [comment]
S_STORE_BASKET goes after C_STORE_SELL_ADD_BASKET  and increase it size with each item in basket

**Comment by SoliaRdi** [comment]
Also you can find ids of added items in hex of S_STORE_BASKET

**Comment by tsunpot** [comment]
ok ill look that up now then

**Comment by Potaatoo1** [comment]
if you find it here I'm trying I'm not succeeding.

**Comment by SoliaRdi** [comment]
logger works as intended

**Comment by SoliaRdi** [comment]
Oh, wait. Not as intended

**Comment by SoliaRdi** [comment]
I was thinking that null only for unknown

**Comment by tsunpot** [comment]
one of these is wrong, when trying to sell fish, it will list all of them but wont click sell

**Comment by SoliaRdi** [comment]
I know :)

**Comment by SoliaRdi** [comment]
P86.6 gonna be same for regions again. When NA next maint? Btw na opcodes in repo already correct

**Comment by tsunpot** [comment]
next maint is in 6 hours and what repo

**Comment by SoliaRdi** [comment]
My repo. Auto-fishing. I post them yesterday
