### ISSUE TITLE
New patch bait

### ISSUE THREAD

**Issue by Distortionn** [SoliaRdi/auto-fishing#265]
Apparently this patch has some new baits that you HAVE to use in these new zones because the other ones aren't working apparently.

Any chance you could add it? I think for now it's just this single one called 

"Pilidium Bait" - You can buy these from the Exodar reputation merchant for 1 rep.

Could you please take a look into this so we could fish there?

Thanks in advance.

**Comment by SoliaRdi** [comment]
I need abnormality id and id of bait for this

**Comment by Distortionn** [comment]
Found this in the abnormal list, does this help?

```
70276	358	Buff	True	perc	0	0	1	Pilidium Bait			For fishing in Exodor.	icon_items.krill_tex	icon_items.krill_tex	True

70276	362	Buff	True	swch	0	0	206053	Pilidium Bait			For fishing in Exodor.	icon_items.krill_tex	icon_items.krill_tex	True
```

**Comment by SoliaRdi** [comment]
Yes. I'll add tomorrow/today

**Comment by Distortionn** [comment]
Thank you very much, Soli!

**Comment by zokiopp** [comment]
@Distortionn Is it better to use those new zones ? more income ?

**Comment by SoliaRdi** [comment]
remove inaccessible baits from bag and inv to fish in new zone

**Comment by SoliaRdi** [comment]
Oh, forgot smth. How did you get this baits?
