### ISSUE TITLE
problem in selling

### ISSUE THREAD

**Issue by Potaatoo1** [SoliaRdi/auto-fishing#266]
everything fuinciona more time to sell in npc fish he just opens merchat more not sell fish ... I'm in NA :<

**Comment by SoliaRdi** [comment]
incorrect opcodes

**Comment by Potaatoo1** [comment]
S_STORE_BASKET = 31000 this is wrong ,I have to find the right number

**Comment by SoliaRdi** [comment]
Gonna post correct soon, just wait

**Comment by Potaatoo1** [comment]
ok
