### ISSUE TITLE
Not an issue with mod, just need help. What actions do i do, to get these IDs ?

### ISSUE THREAD

**Issue by AntiScrewdriver** [SoliaRdi/auto-fishing#270]
fpi C_MEDAL_STORE_COMMIT
fpi C_PUT_WARE_ITEM
fpi C_STORE_COMMIT
fpi C_STORE_SELL_ADD_BASKET
fpi S_MEDAL_STORE_BASKET
fpi S_STORE_BASKET

These two seem to have the same id when i tried. not sure what i did wrong.
fpi C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT
fpi S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT

**Comment by tsunpot** [comment]
its not the same ID in your tera log, but if its anything like mine, it'll just show up as NULL. so you have to think of what each ID actually does after each action before it to properly find out what goes where.

**Comment by SoliaRdi** [comment]
Tera log shows raw packets. It cant map them automatically. If your proxy dont know opcode it shows NULL. But if know and you still got null, then smth broken(i tested and no, everything fine)

**Comment by AntiScrewdriver** [comment]
ok.

gonna play around with this some more. thank you guys !
