### ISSUE TITLE
You are out of fishing area.

### ISSUE THREAD

**Issue by wujorogal** [SoliaRdi/auto-fishing#274]
So im on a vexatus fishing area standing 6m from npc to be able to sell the fishes i use the bait i start fishing i catch the fish no problem but issue starts here : 
After gettign my first fish module tries to use the rod again...and it say you are out of fishing area ...even tho i just fished one fish there - im facing water and everything...changed spots numerous times too to find a better spot...i even jumped into cluster of ppl and it keeps happening...its not pernament tho - after 2 3 max 4 "fails" of using the rod and getting msg im out of fishing area next one is finnaly succesfull and fishes normally...then after that one lucky throw...i get the msg again for few times. proxy log dosnt show any errors and thing is cos of it my time per fish insted of being 43-46sec per fish its actually 60-70 sec per fish. Was wonderign if i do something wrong or if theres some kind of trick to fishing now - didnt do it for 2 months and just came back to it,

**Comment by tridewice** [comment]
Its tera problem, some spots its kinda buggy, try to find a spot as close of the water and spamm ur fishing rod to make sure its working fine. Thats how I do it, hopeffuly it helps you.

**Comment by wujorogal** [comment]
turns out it was purely a class issue...or this char issue in general...elin it was and it was buggy as hell - worked perfectly with other acc
