### ISSUE TITLE
Gameforge EU  outdated

### ISSUE THREAD

**Issue by username011111** [SoliaRdi/auto-fishing#275]
update please :)
thanks

**Comment by zokiopp** [comment]
still no opcodes?

**Comment by username011111** [comment]
i dont know about that :/  iam new at this..

**Comment by PsykoDev** [comment]
S_START_FISHING_MINIGAME = 38566
C_END_FISHING_MINIGAME = 31995
S_FISHING_BITE = 23894
S_FISHING_CATCH = 29655
C_START_FISHING_MINIGAME = 28334
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 33061
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 50739
C_STORE_COMMIT = 51832
C_STORE_SELL_ADD_BASKET = 60707
C_PUT_WARE_ITEM = 49789

S_STORE_BASKET = missing
