### ISSUE TITLE
how to trigger S_STORE_BASKET

### ISSUE THREAD

**Issue by Zakhaev31** [SoliaRdi/auto-fishing#276]
its the only op code i cant find
I open the merchant, put items and sell it but didnt trigger the code.
Im using alex packet id.

i tried using PacketsLogger but didnt work and i get the hexy

**Comment by SoliaRdi** [comment]
Check needed map in current repo

**Comment by Zakhaev31** [comment]
> Check needed map in current repo

i checked u recently update the new op codes, i just wanna know how u trigger or get S_STORE_BASKET

**Comment by SoliaRdi** [comment]
![image](https://user-images.githubusercontent.com/34610562/68709685-3f6ce580-05a7-11ea-8c3a-d4b139e3dd02.png)
Also search in issues by S_STORE_BASKET keyword

**Comment by Zakhaev31** [comment]
> Also search in issues by S_STORE_BASKET keyword

well i tried again and seems your PacketsLogger work, and found the op code in your logger
In alex id finder didnt work

**Comment by SoliaRdi** [comment]
Raw loggers works with existing opcodes. And you determine what opcode is it by hex and logic
