### ISSUE TITLE
Auto-dismantle  ignore  blacklist

### ISSUE THREAD

**Issue by username011111** [SoliaRdi/auto-fishing#278]
hello,
i edit the file by myself .
I just use  fish blacklist add  one time to see if its the right  direction of the config file

C:\Users\xxx\AppData\Local\Programs\TeraToolbox\mods\auto-fishing-master
NAME OF MY CHARACTER 

my Inventory only got 20 Slots left free
iam sure i use  reloadconf  before start 

*what iam doing after i submit that new issue, 
restart client, debug and reloadconf    if that dont work i will post a comment below 

My file looks like this after i add all rar fishes 
____
{
	"time": {
		"minigame": {
			"min": 4000,
			"max": 5000
		},
		"stMinigame": {
			"min": 2000,
			"max": 4000
		},
		"rod": {
			"min": 4500,
			"max": 5500
		},
		"bait": {
			"min": 250,
			"max": 750
		},
		"sell": {
			"min": 150,
			"max": 300
		},
		"contract": {
			"min": 500,
			"max": 1000
		},
		"dialog": {
			"min": 1500,
			"max": 3000
		},
		"dismantle": {
			"min": 200,
			"max": 400
		},
		"decision": {
			"min": 500,
			"max": 700
		}
	},
	"blacklist": [
		206501,
		206513,
		206508,
		206502,
		206500,
		206504,
		206511,
		206505,
		206501,
		206503,
		206507,
		206509,
		206514,
		206506,
		206512,
		206510,
		206435,
		206455,
		206454,
		206432,
		206456,
		206434,
		206451,
		206425,
		206431,
		206433,

	],
	"gmmode": "stop"
}

**Comment by username011111** [comment]
Question :   how can i dismantle  completly  inventory ( more than 1 time dismantle windows need to open, is that possible? )

**Comment by username011111** [comment]
eu gameforge steam version

**Comment by SoliaRdi** [comment]
remove comma after 206433,

**Comment by SoliaRdi** [comment]
About question. Not in my mod

**Comment by username011111** [comment]
thanks for the short answer !!!  and its work !!
Wow.  hoow can i donate a littlebit via paypal ? :)

**Comment by SoliaRdi** [comment]
Only this https://www.buymeacoffee.com/S93stBQkm ;)
