### ISSUE TITLE
fish setrecipe not working

### ISSUE THREAD

**Issue by tatersmasher7** [SoliaRdi/auto-fishing#28]
as of this morning, using fish setrecipe gives "incorrect item id" when setting recipe.
i have deleted mod contents and reinstalled mod contents with 
1. craft manual bait
2. fish setrecipe
3. incorrect item id

**Comment by SoliaRdi** [comment]
fish setbait?

**Comment by tatersmasher7** [comment]
fish setbait link works correctly.

**Comment by SoliaRdi** [comment]
Do you enable mode before crafting bait?

**Comment by tatersmasher7** [comment]
i have both attempted with it enabled and with it disabled.

**Comment by tatersmasher7** [comment]
i have found the issue now. i never crafted the bait with it enabled.

**Comment by SoliaRdi** [comment]
Well, this behaviour should be changed on my side. Not user friendly. I will think about it =)
