### ISSUE TITLE
модуль смены каналов

### ISSUE THREAD

**Issue by apostol-roman** [SoliaRdi/auto-fishing#282]
добрый день. подскажи пожалуйста по модулю для быстрого переключения каналов, я пытаюсь его создать но он не хочет работать ( что я делаю не так? помоги пожалуйста [https://github.com/apostol-roman/swich-channels-instantly](url)

**Comment by SoliaRdi** [comment]
Это невозможно. На евро, ру, na регионах на уровне сервера установлена задержка

**Comment by apostol-roman** [comment]
спасибо за ответ. очень жаль что нельзя.. просто увидев вот эти модули подумал что раз с чата управляют сменой каналов, то и время ожидания переключения каналов 5 секунд эти можно убрать(( печаль
[https://github.com/TerableCoder/cmd-channel](url)
[https://github.com/tsunpot/channel-switch-command](url)
[https://github.com/Snugglez/channel-switch-command](url)
[https://github.com/AlteriaX/channel-command](url)
