### ISSUE TITLE
Need EU fix

### ISSUE THREAD

**Issue by Mamento12** [SoliaRdi/auto-fishing#283]
EU fix please.

Thanks in advance

**Comment by Skaaxy** [comment]
That would be great. Can´t autofish anymore since the new update and replacing the map files doesnt work either.

**Comment by SoliaRdi** [comment]
![image](https://user-images.githubusercontent.com/34610562/70335253-064b2c80-1858-11ea-81c9-ae23d922d043.png)

**Comment by maryannew** [comment]
> EU fix please.
> 
> Thanks in advance

make new protocol
protocol.359532.map

C_END_FISHING_MINIGAME = 49129
C_PUT_WARE_ITEM = 30065
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 52247
C_START_FISHING_MINIGAME = 30960
C_STORE_COMMIT = 50056
C_STORE_SELL_ADD_BASKET = 24454
S_FISHING_BITE = 57127
S_FISHING_CATCH = 22226
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 43445
S_START_FISHING_MINIGAME = 30840
S_STORE_BASKET = 32367
