### ISSUE TITLE
After patch, module dont work

### ISSUE THREAD

**Issue by DotDot90** [SoliaRdi/auto-fishing#284]
the character start to fish, but when he got a bite, didnt do anything, and then the time finish, dont restart fishing

**Comment by ElToupet** [comment]
It's written : "disable for p88"
Author modified index.js to disable mod if game version is 88 or over.

Wait for updates :v

**Comment by Nykkyta** [comment]
New OpCodes are available at https://github.com/tera-proxy/tera-data/tree/master/map

but I can't remove the "disable for version >88" part, so can't activate the mod anymore...

**Comment by SoliaRdi** [comment]
update pushed. New defs was added

**Comment by Liliaina** [comment]
So the mod is safe to use now?



On Saturday, December 14, 2019, 7:55 AM, SoliaRdi <notifications@github.com> wrote:


update pushed. New defs was added

**Comment by SoliaRdi** [comment]
relatively, it's still a bot

**Comment by Liliaina** [comment]
I just wasn’t sure if it was detectable anymore..It’s not though? That was a pretty quick fix! o.o


Sent from Yahoo Mail for iPhone


On Saturday, December 14, 2019, 12:18 PM, SoliaRdi <notifications@github.com> wrote:


relatively, it's still a bot
