### ISSUE TITLE
Its not an Issue but cant find somewhere else

### ISSUE THREAD

**Issue by LielZ** [SoliaRdi/auto-fishing#289]
Its not an Issue but cant find somewhere else,
How do I open multi client for this ?

**Comment by Liliaina** [comment]
If you use the Tera launcher, close the launcher while your game is open, reopen the launcher, and log into a different account. Then launch like normal. Though keep in mind, if the first account disconnects (cause internet or some shit idk), you'll have to close that client, close your launcher again, and log into your first account again. I guess the game uses the launcher for server select or something.
Hope this made sense.

**Comment by LielZ** [comment]
> If you use the Tera launcher, close the launcher while your game is open, reopen the launcher, and log into a different account. Then launch like normal. Though keep in mind, if the first account disconnects (cause internet or some shit idk), you'll have to close the disconnected client, close your launcher again, and log into your first account again. I guess the game uses the launcher for server select or something.
> Hope this made sense.

Hey, thanks for helping me out.
So on Tera EU there is a new GameForge launcher, even if I close it (the launcher) after I reopen the launcher and trying logout its says that I cant because the game is still running, there is a solution for this? Thanks!!

**Comment by Liliaina** [comment]
> > If you use the Tera launcher, close the launcher while your game is open, reopen the launcher, and log into a different account. Then launch like normal. Though keep in mind, if the first account disconnects (cause internet or some shit idk), you'll have to close the disconnected client, close your launcher again, and log into your first account again. I guess the game uses the launcher for server select or something.
> > Hope this made sense.
> 
> Hey, thanks for helping me out.
> So on Tera EU there is a new GameForge launcher, even if I close it (the launcher) after I reopen the launcher and trying logout its says that I cant because the game is still running, there is a solution for this? Thanks!!

o Gameforge.. Is there an option for it to not keep you logged in? So that if you close and reopen, it asks for a login? That's the most I can think of.. I'm from NA xD

**Comment by LielZ** [comment]
> > > If you use the Tera launcher, close the launcher while your game is open, reopen the launcher, and log into a different account. Then launch like normal. Though keep in mind, if the first account disconnects (cause internet or some shit idk), you'll have to close the disconnected client, close your launcher again, and log into your first account again. I guess the game uses the launcher for server select or something.
> > > Hope this made sense.
> > 
> > 
> > Hey, thanks for helping me out.
> > So on Tera EU there is a new GameForge launcher, even if I close it (the launcher) after I reopen the launcher and trying logout its says that I cant because the game is still running, there is a solution for this? Thanks!!
> 
> o Gameforge.. Is there an option for it to not keep you logged in? So that if you close and reopen, it asks for a login? That's the most I can think of.. I'm from NA xD

I dont think there is a way for me open 2 another launcher with diffrent user, 
Thanks anyway man your great! 👍
