### ISSUE TITLE
Patch 88

### ISSUE THREAD

**Issue by fisherman1717** [SoliaRdi/auto-fishing#290]
[command] ERROR: Error: [dispatch] [auto-fishing] hook: unmapped packet "S_FISHING_BITE"

Failed to auto "pull-in" the fish.

Have been using this mod for a couple of months now, so I'm familiar with placing the "defs" into node_modules/tera-data/protocol; and also the protocol.359882.map file into node_modules/tera-data/map. Am playing on NA server.

Although i notice toolbox starting up log writes:
Loaded protocol version 359881 (NA v88.4)

I don't have the protocol.359881.map file.

Am i doing something wrong?

**Comment by SoliaRdi** [comment]
No. You need na opcodes. I dont have them. Try to check pinkie repo or wait

**Comment by fisherman1717** [comment]
could you guide how to "check pinkie repo"

**Comment by PsykoDev** [comment]
C_CAST_FISHING_ROD = 46443
C_END_FISHING_MINIGAME = 61060
C_PUT_WARE_ITEM = 
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 62476
C_START_FISHING_MINIGAME = 60116
C_STOP_FISHING = 24197
C_STORE_COMMIT = 55123
C_STORE_SELL_ADD_BASKET = 23100
S_FISHING_BITE = 42528
S_FISHING_CATCH = 36131
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 61485
S_START_FISHING_MINIGAME = 40318
S_STORE_BASKET = 

NA 88.4 update

**Comment by fisherman1717** [comment]
> C_CAST_FISHING_ROD = 46443
> C_END_FISHING_MINIGAME = 61064
> C_PUT_WARE_ITEM = 64242
> C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 62476
> C_START_FISHING_MINIGAME = 60116
> C_STOP_FISHING = 24197
> C_STORE_COMMIT = 55123
> C_STORE_SELL_ADD_BASKET = 23100
> S_FISHING_BITE = 42528
> S_FISHING_CATCH = 36131
> S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 61485
> S_START_FISHING_MINIGAME = 40318
> S_STORE_BASKET =
> 
> NA 88.4 update

sorry, could you guide what to do with that

**Comment by PsykoDev** [comment]
add this in your protocol map in the proxy

**Comment by fisherman1717** [comment]
some strange issue - when inventory is full, they only automatically sell ONE fish and don't sell the rest of the fishes in the inventory.

**Comment by SoliaRdi** [comment]
no S_STORE_BASKET opcode

**Comment by fisherman1717** [comment]
anyone knows how to edit/generate this opcode for S_STORE_BASKET?

**Comment by PsykoDev** [comment]
i dunno how to trigger that :'(

**Comment by fisherman1717** [comment]
anyone can help? about the fish not being sold to NPC

**Comment by fisherman1717** [comment]
refer to post by PsykoDev for opcodes
