### ISSUE TITLE
Safe to use like before patch 88?

### ISSUE THREAD

**Issue by Liliaina** [SoliaRdi/auto-fishing#294]
I don't really know where else to ask so..
Any updates on whether or not we're able to be detected when using this mod right now? When I type "fish", I see it telling me that they're unsure if the solution is safe or not.

**Comment by PsykoDev** [comment]
i dunno if it's safe or not with all new .def let other player try and maybe take a ban :/

**Comment by Mamento12** [comment]
Would also like to know if anyone heard of people getting banned after patch 88 for using it

**Comment by SoliaRdi** [comment]
As i know no one was banned during p88
