### ISSUE TITLE
Exador fishing

### ISSUE THREAD

**Issue by EjderDede** [SoliaRdi/auto-fishing#302]
As you all know exador bait cant be crafted and only way to get it is buying from npc.
And most important thing is you can carry only 60 bait. So for bot that is a problem.
But I found something that may work around this issue. **Special Storage**.
Companions Special storage can carry However much you want.
So if bot can take baits from special storage after bait in the inventory gone that will fix the problem.
For that bot needs to do 3 more tasks
1 Feed the companion from inventory Puppy Figurine item in certain timeframe so companion stamina will not depleted. 1 Puppy Figurine for 30 min.
2 Open companions special storage and take x10 x50 or x60 Philidium Bait to inventory
3 Do not create any normal bait because it will not work in exador. 
And continue fishing.
Its just an idea but I hope it can be doable. It can be like  /8 fish exadormode or something. Can you please look for this?
PS: Sorry for bad language

**Comment by SoliaRdi** [comment]
Great idea. But i don't have any motivation for the development of functionality or do anything here
