### ISSUE TITLE
If i use "fish save" all my configuration settings gets resetted 

### ISSUE THREAD

**Issue by Mephistou** [SoliaRdi/auto-fishing#306]

**Comment by SoliaRdi** [comment]
Why only you have this problem?

**Comment by SoliaRdi** [comment]
Nothing changed in settings part for half year

**Comment by Mephistou** [comment]
I don't know i'm trying everything but if i save some settings whole file resets to new, and i didn'teven have it yesterday i think

**Comment by SoliaRdi** [comment]
Describe what you do step by step

**Comment by Mephistou** [comment]
i added fish to blacklist, then "fish save". also now i think it ignores configuration file completely

**Comment by Mephistou** [comment]
I think i fixed. Dunno what triggered it, i think i added fish code for blacklist manually maybe that?

**Comment by SoliaRdi** [comment]
If without reload command - yes. Or your save corrupted json

**Comment by Mephistou** [comment]
i used reload, later i even removed what i added. Or maybe i used "fish save" command without adding anything and that made to remake new file?

**Comment by SoliaRdi** [comment]
No, then corrupted json, extra comma or smth else
