### ISSUE TITLE
Not working after patch

### ISSUE THREAD

**Issue by Mephistou** [SoliaRdi/auto-fishing#307]

**Comment by SoliaRdi** [comment]
eu got new patch?

**Comment by Mephistou** [comment]
got some update idk

**Comment by Mephistou** [comment]
will it be fixed?

**Comment by SoliaRdi** [comment]
Idk too. Give me more details. I dont play eu

**Comment by DotDot90** [comment]
suppose new patch, toolbox ask about protocol.359960.map

**Comment by Mephistou** [comment]
![err](https://user-images.githubusercontent.com/45772604/72353667-1b379d00-36ed-11ea-9ce8-e716842be5ca.PNG)
I get this error on toolbox ^
And in game when i write "fish" to activate, it shows also error:
"Error running callback for command "fish".

**Comment by Mephistou** [comment]
I even reinstalled mod.

**Comment by SoliaRdi** [comment]
obviously you need new opcodes. I dont have them yet

**Comment by Mephistou** [comment]
So when you will get them you will fix it?

**Comment by SoliaRdi** [comment]
when someone send me them or they appear here https://github.com/tera-proxy/tera-data/tree/master/map

**Comment by SoliaRdi** [comment]
opcodes up
