### ISSUE TITLE
Error running callback for command "fish"

### ISSUE THREAD

**Issue by fisherman1717** [SoliaRdi/auto-fishing#309]
looks like the latest maintenance for NA made auto fishing not working again.
Anyone has latest opcodes for NA?

**Comment by Mephistou** [comment]
i still have that on eu, do i have to reinstall mod?

**Comment by Mephistou** [comment]
oh yea that fixed

**Comment by AntiScrewdriver** [comment]
Credit goes to this guy on discord. 
i tried the codes and it worked.
![image](https://user-images.githubusercontent.com/47073195/72402223-674d1500-37b3-11ea-83b5-1b02cda79c28.png)

S_FATIGABILITY_POINT = 44601
S_CURRENT_CHANNEL = 60964
C_CAST_FISHING_ROD = 49903
C_END_FISHING_MINIGAME = 34898
C_PUT_WARE_ITEM = 50057
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 34198
C_START_FISHING_MINIGAME = 30849
C_STOP_FISHING = 30252
C_STORE_COMMIT = 32258
C_STORE_SELL_ADD_BASKET = 48023
S_CAST_FISHING_ROD = 54966
S_FISHING_BITE = 23762
S_FISHING_CATCH = 52483
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 35409
S_START_FISHING_MINIGAME = 60838
S_STORE_BASKET = 61509
C_REQUEST_RECV_DAILY_TOKEN = 64360
S_CANT_FLY_ANYMORE = 57490
C_SELECT_CHANNEL = 40096
S_CANCEL_SELECT_CHANNEL = 43495
S_PREPARE_SELECT_CHANNEL = 39800
S_CURRENT_CHANNEL = 60964



---

I don't know what S_FATIGABILITY_POINT is, i've never seen it in the fishing mod.

**Comment by EjderDede** [comment]
is this NA or EU ?

**Comment by fisherman1717** [comment]
only one way to find out! going to test the opcodes on NA server

**Comment by Mephistou** [comment]
na and eu had different opcodes?

**Comment by AntiScrewdriver** [comment]
> 
> 
> is this NA or EU ?

I think its for both. i tried it for NA and it worked.



> 
> 
> na and eu has different opcodes?

Sometimes they do. You have to see the protocol number.



> 
> 
> only one way to find out! going to test the opcodes on NA server. Yep didn't work for NA!

@fisherman1717 , im on NA, using tera-toolbox, it works for me. currently fishing with the mod as im typing this.

**Comment by fisherman1717** [comment]
@AntiScrewdriver hmmm odd i must be doing something wrongly then.
But from my experience I just copied all the opcodes above into the protocol.359881 readme file in node_modules\tera_data\map

**Comment by AntiScrewdriver** [comment]
@fisherman1717 

Ah.. thats the problem maybe.
current protocol on NA is 
![image](https://user-images.githubusercontent.com/47073195/72479151-78039680-3858-11ea-996a-ce0fac6fc300.png)

**Comment by SjinYo** [comment]
I found the problem. T.T is updating eveytime you launch it , then it change your Protocol and delete what you need for fish ( i just make the file " read only " for the moment

**Comment by metin1980** [comment]
any here know why no selling? you dont have enoght inventory space...

**Comment by SoliaRdi** [comment]
https://github.com/tera-proxy/tera-data/tree/master/map
