### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ChicknWing** [SoliaRdi/auto-fishing#310]
Is it possible to add support for companion Kuncun with Backup Fisherman passive? I have the mod that auto-gifts my partner but it doesn't work well when using auto-fishing. Some built in auto-partner-gifting would be nice. 

Thanks.

**Comment by SoliaRdi** [comment]
This is possible, but i don't have any motivation to do anything here. Also i don't play tera for almost year. I can accept pr if someone make this
