### ISSUE TITLE
protocol.363037

### ISSUE THREAD

**Issue by UnexpectedUser93** [SoliaRdi/auto-fishing#311]
Except one, by the way... any idea why packet finder isnt working? was working fine untill some time. :) 

C_END_FISHING_MINIGAME = 36477 
C_CAST_FISHING_ROD = 21453
C_STOP_FISHING = 62275
C_PUT_WARE_ITEM = 51689 
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 56037 
C_START_FISHING_MINIGAME = 25644 
C_STORE_COMMIT = 37934 
C_STORE_SELL_ADD_BASKET = 58920 
S_FISHING_BITE = 62833 
S_FISHING_CATCH = 33271 
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 27219 
S_START_FISHING_MINIGAME = 22386 
S_STORE_BASKET = - couldnt find this one.

**Comment by RobinNorling** [comment]
S_STORE_BASKET = 20797

**Comment by metin1980** [comment]
You dont have enough inventory space, when is selling no sell nothing

**Comment by SoliaRdi** [comment]
https://github.com/tera-proxy/tera-data/tree/master/map
