### ISSUE TITLE
NA opcodes ? 

### ISSUE THREAD

**Issue by IlyaNik92** [SoliaRdi/auto-fishing#316]
After yesterdays NA patch. need some update for opcodes please :).
Thanks you

**Comment by IlyaNik92** [comment]
S_FATIGABILITY_POINT = 24897 
S_CURRENT_CHANNEL = 62984
C_CAST_FISHING_ROD = 38028 
C_END_FISHING_MINIGAME = 45614 
C_PUT_WARE_ITEM = 23779 
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 21698 
C_START_FISHING_MINIGAME = 51383 
C_STOP_FISHING = 40109 
C_STORE_COMMIT = 23897 
C_STORE_SELL_ADD_BASKET = 48533 
S_FISHING_BITE = 45229 
S_FISHING_CATCH = 38224 
S_CAST_FISHING_ROD = 42364 
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 51053 
S_START_FISHING_MINIGAME = 64296 
S_STORE_BASKET = 24503

**Comment by IlyaNik92** [comment]
C_CAST_FISHING_ROD = 38028 
C_END_FISHING_MINIGAME = 45614 
C_PUT_WARE_ITEM = 23779 
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 21698 
C_START_FISHING_MINIGAME = 51383 
C_STOP_FISHING = 40109 
C_STORE_COMMIT = 23897 
C_STORE_SELL_ADD_BASKET = 48533 
S_FISHING_BITE = 45229 
S_FISHING_CATCH = 38224 
S_CAST_FISHING_ROD = 42364 
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 51053 
S_START_FISHING_MINIGAME = 64296 
S_STORE_BASKET = 24503

**Comment by fisherman1717** [comment]
Error running callback for command "fish", even after putting below opcodes into protocol file: 363034 for NA. Anyone can advise?

C_CAST_FISHING_ROD = 38028
C_END_FISHING_MINIGAME = 45614
C_PUT_WARE_ITEM = 23779
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 21698
C_START_FISHING_MINIGAME = 51383
C_STOP_FISHING = 40109
C_STORE_COMMIT = 23897
C_STORE_SELL_ADD_BASKET = 48533
S_FISHING_BITE = 45229
S_FISHING_CATCH = 38224
S_CAST_FISHING_ROD = 42364
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 51053
S_START_FISHING_MINIGAME = 64296
S_STORE_BASKET = 24503

**Comment by IlyaNik92** [comment]
The module is having a problem selling fish, it locks and does nothing after talking to the merchant

**Comment by fisherman1717** [comment]
yeah some opcode must be broken, regarding the selling fishes to NPC function.
gotta wait for someone to figure it out.

**Comment by fisherman1717** [comment]
@IlyaNik92 found the right Opcodes for merchanting yet?

**Comment by IlyaNik92** [comment]
@fisherman1717  i put these all opcodes and it work https://github.com/tera-proxy/tera-proxy/blob/master/node_modules/tera-data/map/protocol.363034.map
