### ISSUE TITLE
Please add Event Shark Bait

### ISSUE THREAD

**Issue by ChicknWing** [SoliaRdi/auto-fishing#320]
70371 : 209189 // Event Shark Bait - can only be used at Murcai Fishery.

**Comment by PsykoDev** [comment]
disable auto-update and add it by yourslef

**Comment by SoliaRdi** [comment]
i'll add in few h, forgot

**Comment by ChicknWing** [comment]
@PsykoDev I did dude. Just want SoliaRdi to update it so everyone doesn't have to do the same. DUH
