### ISSUE TITLE
OPCODE FOR EU 91.4

### ISSUE THREAD

**Issue by PsykoDev** [SoliaRdi/auto-fishing#324]
C_CAST_FISHING_ROD = 42562 
C_END_FISHING_MINIGAME = 44336 
C_PUT_WARE_ITEM = 29954 
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 35467 
C_START_FISHING_MINIGAME = 34988 
C_STOP_FISHING = 44597 
C_STORE_COMMIT = 20145 
C_STORE_SELL_ADD_BASKET = 30797 
S_FISHING_BITE = 21335 
S_FISHING_CATCH = 24258 
S_CAST_FISHING_ROD = 23051 
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 38187 
S_START_FISHING_MINIGAME = 31027 
S_STORE_BASKET = 37908

**Comment by metin1980** [comment]
where have to paste this? wherE?

**Comment by Purgator** [comment]
Juste paste this in the same directory as the url : https://raw.githubusercontent.com/tera-proxy/tera-data/master/map/protocol.365098.map
