### ISSUE TITLE
New toolbox release broke fishbot module :/

### ISSUE THREAD

**Issue by DaXmAn** [SoliaRdi/auto-fishing#326]
[15:23:45.636] [mods] ERROR: Module "Auto-Fishing" (auto-fishing) could not be loaded!
[15:23:45.637] [mods] ERROR: Please contact the module's author: https://github.com/SoliaRdi/auto-fishing
[15:23:45.639] Error: Cannot find module 'moment'

Do you know where should I look for this module and where to put it in new version of Toolbox?

**Comment by SoliaRdi** [comment]
Install moment.js manually

**Comment by DaXmAn** [comment]
If I put moments folder into TeraToolbox\node_modules and restart toolbox, it removes it from that folder

**Comment by SoliaRdi** [comment]
blame caali

**Comment by DaXmAn** [comment]
is moment module forbidden or something?

**Comment by SoliaRdi** [comment]
his migration logic is broken

**Comment by DaXmAn** [comment]
what this moment module is responsible for?

**Comment by SoliaRdi** [comment]
https://momentjs.com/

**Comment by DaXmAn** [comment]
ok I guess I can safely ask on discord then

**Comment by SoliaRdi** [comment]
i'll bundle moment with mod soon

**Comment by DaXmAn** [comment]
response from discord: "if you want to bundle node_modules with your mods, put them into a node_modules folder within your mod's folder" hmmm

**Comment by SoliaRdi** [comment]
yea, not very convenient, but nothing to do

**Comment by metin1980** [comment]
sorry for coment but i need to know where i put the moment file
