### ISSUE TITLE
error  could not be loaded!

### ISSUE THREAD

**Issue by metin1980** [SoliaRdi/auto-fishing#327]

**Comment by metin1980** [comment]
MODULE_NOT_FOUND

**Comment by metin1980** [comment]
was working i reset pc and no work when i put "fish" Unknown command "fish"

**Comment by metin1980** [comment]
Cannot find module 'moment'

**Comment by SoliaRdi** [comment]
wait few min

**Comment by SoliaRdi** [comment]
done, reread installation notes. Defs folder was changed

**Comment by metin1980** [comment]
From now on this module will only work on Caali's Tera Proxy where can get the caali tera proxy?

**Comment by SoliaRdi** [comment]
lol, this line is already a year old

**Comment by SoliaRdi** [comment]
now it named toolbox

**Comment by metin1980** [comment]
i donwload again the mod
i replace the folder
but no working

**Comment by SoliaRdi** [comment]
what error?

**Comment by metin1980** [comment]
moment modile

**Comment by metin1980** [comment]
[17:09:32.307] [mods] ERROR: Please contact the module's author: https://github.com/SoliaRdi/auto-fishing
[17:09:32.309] Error: Cannot find module 'moment'

**Comment by SoliaRdi** [comment]
i did same and 
![image](https://user-images.githubusercontent.com/34610562/76166814-8a23f600-6172-11ea-9c26-7b223ef09be1.png)
Try to figure out what you doing wrong

**Comment by SoliaRdi** [comment]
or maybe you reinstall before my fix

**Comment by metin1980** [comment]
omg... i was reading the previous messages.. sorry and retard... ty

**Comment by metin1980** [comment]
oh lol but now other error
error running callback for comand fish

**Comment by SoliaRdi** [comment]
You need to reinstall defs and opcodes. Folder was changed

**Comment by metin1980** [comment]
u meant about the tera-data?

**Comment by SoliaRdi** [comment]
![image](https://user-images.githubusercontent.com/34610562/76166927-86dd3a00-6173-11ea-9b61-4ab1fab580fa.png)

**Comment by SoliaRdi** [comment]
oops

**Comment by SoliaRdi** [comment]
defs in definitions

**Comment by SoliaRdi** [comment]
caali changed custom defs, opcodes location

**Comment by metin1980** [comment]
and i need change the codes, right? but how i can do?

**Comment by SoliaRdi** [comment]
no, no. Just another folder now

**Comment by metin1980** [comment]
can u guide me plis?

**Comment by metin1980** [comment]
just tell me what i have to do

**Comment by SoliaRdi** [comment]
fixed ss
![image](https://user-images.githubusercontent.com/34610562/76166988-43cf9680-6174-11ea-96b7-f8f182f74145.png)

**Comment by metin1980** [comment]
i dont understand nothing...

**Comment by metin1980** [comment]
i have to copi the protocol and sysmsg files there? in data/definitions?

**Comment by metin1980** [comment]
i see 2 folder there, opcodes and definition

**Comment by metin1980** [comment]
i paste the files map in opcodes folder

**Comment by metin1980** [comment]
kkk i get it, sorry english is not my first lenguage
