### ISSUE TITLE
It's still not working for me.. after that last toolbox patch or smth

### ISSUE THREAD

**Issue by Mephistou** [SoliaRdi/auto-fishing#332]
"Error running callback for command "fish".
could send you all error message if you want.
But really i'm only one on EU has this issue?

**Comment by SoliaRdi** [comment]
only full error message can point issue. "Error running callback for command "fish" can be anything

**Comment by Mephistou** [comment]
okay sec

**Comment by Mephistou** [comment]
![Capture](https://user-images.githubusercontent.com/45772604/76311187-0b959880-62d9-11ea-9678-1a1a2cdeb348.PNG)

**Comment by SoliaRdi** [comment]
check installation part of readme

**Comment by Mephistou** [comment]
i did, are you saying i should replace opcodes? cuz i did 4 days ago when they were added

**Comment by SoliaRdi** [comment]
https://github.com/SoliaRdi/auto-fishing/commit/d38620b7afb24df37648412285c1d4b157516c8c#diff-26205fa396afae7e698346556c23f256

**Comment by SoliaRdi** [comment]
folder was changed(current readme is correct)

**Comment by Mephistou** [comment]
so what i have to do to fix?

**Comment by SoliaRdi** [comment]
follow installation notes

**Comment by Mephistou** [comment]
so i have to reinstall it all?

**Comment by SoliaRdi** [comment]
not everything, but defs & opcodes part

**Comment by Mephistou** [comment]
finally working. Thanks.
