### ISSUE TITLE
Updated NA 91.04 op code request

### ISSUE THREAD

**Issue by fishfishfish5** [SoliaRdi/auto-fishing#333]
New na op codes?

**Comment by fisherman1717** [comment]
yeah need new opcodes to fish fish hehe

**Comment by zashe7861** [comment]
someone teach me how to do the op codes so i can do it myself instead of waiting

**Comment by AntiScrewdriver** [comment]
C_REQUEST_RECV_DAILY_TOKEN = 24646
S_TRADE_BROKER_BOUGHT_ITEM_LIST = 55781
S_CANT_FLY_ANYMORE = 45625
C_START_SERVANT_ACTIVE_SKILL = 23870
S_PREPARE_SELECT_CHANNEL = 29952
C_SELECT_CHANNEL = 25472 
S_CANCEL_SELECT_CHANNEL = 27683 
S_CURRENT_CHANNEL 55732
C_GET_WARE_ITEM = 56273 
S_FATIGABILITY_POINT = 42629 
C_CAST_FISHING_ROD = 23647 
C_PUT_WARE_ITEM = 27766
C_END_FISHING_MINIGAME = 64923 
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 35219 
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 43573
C_START_FISHING_MINIGAME = 58121 
C_STOP_FISHING = 45220 
S_FISHING_BITE = 45937 
S_FISHING_CATCH = 32054 
S_START_FISHING_MINIGAME = 50837 
C_STORE_COMMIT = 38051 
C_STORE_SELL_ADD_BASKET = 36513 
S_STORE_BASKET = 31965

---

I took this from
◤やsͥץkͣoͫ◢#4280 
who posted it on discord.

**Comment by fisherman1717** [comment]
@AntiScrewdriver may i know which discord it is and can i have the link

**Comment by fisherman1717** [comment]
selling fish to NPC seems broken

**Comment by Monstertera** [comment]
C_DELIVERY_STORE_ADD_BASKET
C_DELIVERY_STORE_COMMIT
C_MEDAL_STORE_BUY_ADD_BASKET
C_MEDAL_STORE_COMMIT
C_REJECT_CONTRACT
C_STORE_BUY_ADD_BASKET
C_UPDATE_AFK_STATUS
Probably need to map this as well to make the selling work.

**Comment by Marikate** [comment]
how i can map this instructions missing? selling fish to NPC seems broken

**Comment by PsykoDev** [comment]
S_STORE_BASKET = 31965 not good

**Comment by PsykoDev** [comment]
C_CAST_FISHING_ROD = 23647 
C_PUT_WARE_ITEM = 27766
C_END_FISHING_MINIGAME = 64923 
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 35219 
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 43573
C_START_FISHING_MINIGAME = 58121 
C_STOP_FISHING = 45220 
S_FISHING_BITE = 45937 
S_FISHING_CATCH = 32054 
S_START_FISHING_MINIGAME = 50837 
C_STORE_COMMIT = 59268 
C_STORE_SELL_ADD_BASKET = 36513 
S_STORE_BASKET 31965

**Comment by Monstertera** [comment]
Psyko, do you have those too as well ?
C_REJECT_CONTRACT
C_UPDATE_AFK_STATUS

**Comment by elmir221** [comment]
do you guys have the one for eu 91.04? or is it the same with na?

**Comment by PsykoDev** [comment]
reject contract for whats contract and afk status ? oO

**Comment by PsykoDev** [comment]
C_REQUEST_RECV_DAILY_TOKEN = 24646
S_TRADE_BROKER_BOUGHT_ITEM_LIST = 55781
S_CANT_FLY_ANYMORE = 45625
C_REQUEST_SERVER_ADMINTOOL_AWESOMIUM_URL = 52569
C_REJECT_CONTRACT 41358
C_REQUEST_EVENT_MATCHING_TELEPORT 57284

C_START_SERVANT_ACTIVE_SKILL = 23870
C_REQUEST_SPAWN_SERVANT 64154
S_UPDATE_SERVANT_INFO 36557

S_PREPARE_SELECT_CHANNEL = 29952
C_SELECT_CHANNEL = 25472 
S_CANCEL_SELECT_CHANNEL = 27683 
S_CURRENT_CHANNEL 55732

C_GET_WARE_ITEM = 56273 
S_FATIGABILITY_POINT = 42629 

C_CAST_FISHING_ROD = 23647 
C_PUT_WARE_ITEM = 27766
C_END_FISHING_MINIGAME = 64923 
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 35219 
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 43573
C_START_FISHING_MINIGAME = 58121 
C_STOP_FISHING = 45220 
S_FISHING_BITE = 45937 
S_FISHING_CATCH = 32054 
S_START_FISHING_MINIGAME = 50837 
C_STORE_COMMIT = 59268 
C_STORE_SELL_ADD_BASKET = 36513 
S_STORE_BASKET 31965

C_REQUEST_FIELD_POINT_REWARD 24163
C_REQUEST_ONGOING_FIELD_EVENT_LIST 52882
C_REQUEST_START_GUILD_QUEST 34608
C_REQUEST_FINISH_GUILD_QUEST 39665
S_FIELD_EVENT_PROGRESS_INFO 25553
S_SHOW_GUILD_QUEST_LIST 31300
S_UPDATE_GUILD_QUEST_STATUS 44699
S_GUILD_QUEST_LIST 55743

**Comment by PsykoDev** [comment]
last opcode NA 91.04

**Comment by ic3dt3a** [comment]
psyko, whenever u get the sell code, i'd appreciate it as well xD
