### ISSUE TITLE
dismantling

### ISSUE THREAD

**Issue by wasd123567** [SoliaRdi/auto-fishing#34]
hi,

dismantling window opens but it doesnt put the fish in i've added to blacklist before. Got the message "you don't have enough inventory space" instead. 
Also downloaded new protocol but nothing changed

**Comment by SoliaRdi** [comment]
In blacklist you put fishes, you don't want to be dismantled. Did you add all fishes in this list?

**Comment by wasd123567** [comment]
ohhh i thought it's adding the fish i want to be dismantled like in the version before :D 

thanks for the quick response o/
