### ISSUE TITLE
Syntax error when linking items

### ISSUE THREAD

**Issue by kex0** [SoliaRdi/auto-fishing#38]
Can't blacklist items and can't setbait.
http://prntscr.com/m79gah
I would set it manually but can't find config.json
http://prntscr.com/m79ilh

**Comment by SoliaRdi** [comment]
config.json would be generated after first fish save. Did you make space before link? Example (rename to config.json)
[config.txt](https://github.com/SoliaRdi/auto-fishing/files/2758753/config.txt)

**Comment by kex0** [comment]
Thank you for the config file, I'm still getting the syntax error for some reason but it works when I edit the config manually. 
These are the commands I tried: 
`!fish setbait <Bait II> //<Bait II> being the link from inventory`
`!fish setbait 206001`
`!fish setbait link <Bait II>`
`!fish setbait link 206001`

All of them return syntax error

**Comment by kex0** [comment]
Mods I have installed: http://prntscr.com/m7je97
The command mod was installed by default.

When I try it in /8
`[Proxy] Unknown command "!fish".`

**Comment by SoliaRdi** [comment]
in /8 no need '!'

**Comment by kex0** [comment]
Thank you very much. 
in /8
`[Proxy][auto-fishing] Bait id set to: 206001`
