### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by abiee88** [SoliaRdi/auto-fishing#39]
![new bitmap image](https://user-images.githubusercontent.com/46728693/51212219-dd3f4780-18e5-11e9-8526-f54ccc6a3c94.jpg)

**Comment by SoliaRdi** [comment]
No opcodes yet. So you can comment mod (add _ at the autofishing folder name start) or remove it for a time

**Comment by ChicknWing** [comment]
NA opcodes.

S_FISHING_BITE = 41766
S_CHANGE_RELATION = 44429
S_USER_DEATH = 26940
C_CAST_FISHING_ROD = 21205
C_END_FISHING_MINIGAME = 39236
C_START_FISHING_MINIGAME = 20693
C_STOP_FISHING = 60129
S_CAST_FISHING_ROD = 41526
S_FISHING_CATCH = 55122
S_FISHING_STOP = 28888
S_START_FISHING_CHARGE = 40114
S_START_FISHING_MINIGAME = 46037
S_FISHING_CATCH_FAIL = 43319
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 28626
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 51289
S_RP_START_SOCIAL_ON_PROGRESS_DECOMPOSITION = 51885
S_RP_COMMIT_DECOMPOSITION_CONTRACT = 55847

You're welcome again. :^)

**Comment by SoliaRdi** [comment]
Thanks =)
