### ISSUE TITLE
Decompose weird behavior.

### ISSUE THREAD

**Issue by SongRongLee** [SoliaRdi/auto-fishing#41]
Server: SEA
After the update, I have a problem that the decomposition function gets stuck -- it either puts fish into the dismantling window and then close without dismantling, or puts nothing into the window and leaves the window opened (and generates many "This item cannot be dismantled" warnings).
It doesn't happen every time and gets back to normal after a restart of the proxy, but it will happen again after fishing awhile.
Do you have any idea what's wrong here? Thank you very much!

**Comment by SoliaRdi** [comment]
Can you logc as well? I dont have 79 patch on RU servers so cant test. Are you sure you don't have more than 9,800 fish fillets in your inventory with disabled filetmode? Anybody else have similar problems?

**Comment by SongRongLee** [comment]
One of my friends has this problem too. He describe it as "the module doesn't dismantle fish when full inventory".
[Here](https://drive.google.com/open?id=1FzCJ0nEF9bN016Fb1pNKAOBEKoHMqiuC)  is my log including both logc and logs.
The steps I took to reproduce the problem:
1. Leave only one bait in the inventory.
2. Leave fish fillets lesser than required to craft batis (under 20 in my case)
3. Fish once. Then the module will try to craft (but not enough fillets)->try to dismantle and then stuck.  

The problem will NOT happen when dismantling few fish (say 5\~10), but will occur when trying to add up to 15\~20.

**Comment by SoliaRdi** [comment]
You can remove log, i downloaded it

**Comment by SoliaRdi** [comment]
Can't reproduce at current version(no changes actually at this routine), try avoid step 2 before fishing.
