### ISSUE TITLE
Angler token seller idea

### ISSUE THREAD

**Issue by Lambda11** [SoliaRdi/auto-fishing#42]
It would be nice if you could make an `angler token seller` module in addition to this one, cuz you can't sell tokens right away, you have to buy 80 `fish crate I design` costing `10 tokens` and which could be sold for `10 gold` each, so `1 token = 1 gold`, then go to nearby npc selling stuff for gold and sell those 80 designs for gold, repeat... there are places where those two are standing near each other so no need for movement, just interacting with two NPCs.

BHS just wants us to bot, don't them?

**Comment by SoliaRdi** [comment]
right now i test completed fish seller with traveling merchant , >20k gold~8h. I will look at your idea after fixing this dismantle errors(when i test dismantle, it works perfectly =_=)

**Comment by Lambda11** [comment]
Yea, that's why I suggested it as separate module, cuz no need to do it during fishing.
