### ISSUE TITLE
Sell to NPC suggestion

### ISSUE THREAD

**Issue by MeongMeongMeong** [SoliaRdi/auto-fishing#43]
In Vexatus Swamp Fishery, there is this one NPC called FIshing Supplies that is really close to the waters. I tried already, you can throw your fishing rod and trade with the NPC in the same spot. Instead of bringing travelling merchan why not try to do with the NPC.

**Comment by kex0** [comment]
That would be great!

**Comment by SoliaRdi** [comment]
I will make it in few days. Too busy with new patch

**Comment by SoliaRdi** [comment]
Well, made it.
