### ISSUE TITLE
about error about autofishing

### ISSUE THREAD

**Issue by Fatalfuryy** [SoliaRdi/auto-fishing#45]
hi, i was using autofishing very well thank you very much but after todays patch it gives an error and does not work 
![auto fish error](https://user-images.githubusercontent.com/46627189/51555001-a938c900-1e87-11e9-8400-696104066709.jpg)

do you know why ?

**Comment by SoliaRdi** [comment]
wait opcodes

**Comment by SoliaRdi** [comment]
EU opcodes added
