### ISSUE TITLE
about the "fish sellfishes" command

### ISSUE THREAD

**Issue by tantananann** [SoliaRdi/auto-fishing#46]
Need help with the "fish sellfishes" command. It's just stuck and not putting the fishes on the sell window after pulling up the "Buy General Goods" window  from the travelling merchant NPC, waited for several minutes but does not do anything. 
I used Pocketlogger to get the ff 
C_STORE_SELL_ADD_BASKET = 42341
C_STORE_COMMIT = 36973

S_STORE_BASKET = 36050 (got this from https://github.com/busann/tera-opcodes/blob/master/protocol.339840.map. I can't find S_STORE_BASKET after going through the "Tera Logs" from the Pocketlogger )

Any help will be appreciated. thank you.

**Comment by SoliaRdi** [comment]
thats old patch opcodes, you cant use them.

**Comment by tantananann** [comment]
Thank you for the reply, Anyway you can point me on the right direction on how to get opcode for S_STORE_BASKET? spawned crystal and travelling merchant to trigger but to no avail. Sorry am a complete noob just trying to see if can get this part of the module working. Thanks again for the taking the time. I play on NA.

**Comment by SoliaRdi** [comment]
S_STORE_BASKET appear right after C_STORE_SELL_ADD_BASKET. This packуе increases the size depending on the number of items added
