### ISSUE TITLE
Massive lag with error

### ISSUE THREAD

**Issue by rayted-r** [SoliaRdi/auto-fishing#47]
[dispatch] handle: failed to parse S_INVEN<17>

on NA server

introduces massive lag on proxy and game cause it outputs a huge paragraph of numbers every couple minutes. worked good yesterday but update today killed it. Increases ping by about 20-40ms.

at the end of the huge array of code it says 
error: S_INVEN<17>..items..unk1: cannot find next element of array at 160 (found value 0)
or
error: S_INVEN<17>..items..unk1: cannot find next element of array at 10114 (found value 39)

next huge block says
error: The value of "offset" is out of range. It must be >= 0 and <= 9675. Received 10114

and repeats the huge block every time with slight differences

**Comment by SoliaRdi** [comment]
Which proxy you using? S_INVEN got update, do you have modules with S_INVEN 16 ?

**Comment by rayted-r** [comment]
using pinkie proxy. his loot mod uses S_INVEN 16. protocol folder has S_INVEN 11-17
auto pet feeder also uses 16, but that mod is broken for me cause I don't have opcodes for S_SPAWN_SERVANT and S_CHANGE_SERVANT_ENERGY. 
skimmed through the rest of my mods and I dont think anything else uses S_INVEN

switching it to 16 on autofish index.js fixed it. thanks :)
