### ISSUE TITLE
Error inventory

### ISSUE THREAD

**Issue by DiegoDaniel** [SoliaRdi/auto-fishing#48]
![imagen](https://user-images.githubusercontent.com/14002872/51789300-3882fc80-2166-11e9-8b2a-9e16ac27e588.png)

New error idk why. Sorry i have only this.

**Comment by SoliaRdi** [comment]
https://github.com/caali-hackerman/tera-data/blob/master/protocol/S_INVEN.17.
So reason for this error - some mod using old v16 S_INVEN

**Comment by DiegoDaniel** [comment]
Solved replacing that S_INVEN.17 in my files. Ty
