### ISSUE TITLE
missing some DEFS

### ISSUE THREAD

**Issue by Reny900** [SoliaRdi/auto-fishing#5]
such as "S_RP_COMMIT_DECOMPOSITION_CONTRACT", to begin with

**Comment by Owyn** [comment]
it's a default def in Caalis proxy

**Comment by Reny900** [comment]
i just checked, and also run the auto-update as suggested, but that def is still missing
[look](https://github.com/caali-hackerman/tera-data/tree/master/protocol)

**Comment by Niacinamine** [comment]
all the opcodes needed are in the respective region protocol map file provided with this module

**Comment by SoliaRdi** [comment]
I don't need structure of this packet for my mod. If you try log this packet-it contains an array, so the size can be different. And comes after C_RQ_COMMIT_DECOMPOSITION_CONTRACT(mapped in Caali proxy)
