### ISSUE TITLE
Crash when trying to sell after todays patch.

### ISSUE THREAD

**Issue by wujorogal** [SoliaRdi/auto-fishing#51]
After todays patch fishing goes smoothly but when inventory gets full and he try to sell to npc proxy error pops up:
![obraz](https://user-images.githubusercontent.com/46306175/52355092-f5603d80-2a31-11e9-9eff-ab314871e5b6.png)
and then the whole game crashes

**Comment by SoliaRdi** [comment]
uh, try in a few minutes
