### ISSUE TITLE
Please give me some advice

### ISSUE THREAD

**Issue by terranceyiw** [SoliaRdi/auto-fishing#53]
I have packet id finder and I want to find 
"S_STORE_BASKET"  opcodes  i don't know where to interact for get the codes.

my server is SEA/TH
sorry for my bad english

**Comment by kyogo123** [comment]
I have the same problem for NA. Can't find the "S_STORE_BASKET" opcode. When I try the sell to NPC it places one fish in the NPC sell basket and then does nothing.

**Comment by SoliaRdi** [comment]
S_STORE_BASKET goes after C_STORE_SELL_ADD_BASKET, packet length
 will grow depending on the number of items added

**Comment by kyogo123** [comment]
> I have packet id finder and I want to find
> "S_STORE_BASKET" opcodes i don't know where to interact for get the codes.
> 
> my server is SEA/TH
> sorry for my bad english

We're you able to find it? Or how you interacted to get the code?
