### ISSUE TITLE
opcodes unmapped

### ISSUE THREAD

**Issue by Calitalon** [SoliaRdi/auto-fishing#56]
The NA opcodes need updating as of this morning.

Thanks!

**Comment by ViralDoom** [comment]
try this out:

S_CAST_FISHING_ROD = 51817
C_CAST_FISHING_ROD = 27871
S_FISHING_BITE = 42148
S_START_FISHING_MINIGAME = 31252
C_START_FISHING_MINIGAME = 41826
C_END_FISHING_MINIGAME = 32911
S_FISHING_CATCH = 51796
S_FISHING_CATCH_FAIL = 49606
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 24833
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 62602
S_RP_COMMIT_DECOMPOSITION_CONTRACT = 22175

**Comment by russopie** [comment]
Could you pls post here the opcode to C_STORE_COMMIT thx

**Comment by AntiScrewdriver** [comment]
@ViralDoom 

Thanks ViralDoom ! it worked !

To the noobs who knows very little about these things, like ME.
Do what i do.

Download fresh copy of your proxy so the map files are clean.
cut and paste those things up there into every *.map file.

-_- 
yeah thats what i did.. i probably did it wrong, but it worked.

**Comment by MeongMeongMeong** [comment]
i think NA got new opcode, 344300

**Comment by ViralDoom** [comment]
> Could you pls post here the opcode to C_STORE_COMMIT thx

C_STORE_COMMIT = 27153

**Comment by ViralDoom** [comment]
> @ViralDoom
> 
> Thanks ViralDoom ! it worked !
> 
> To the noobs who knows very little about these things, like ME.
> Do what i do.
> 
> Download fresh copy of your proxy so the map files are clean.
> cut and paste those things up there into every *.map file.
> 
> -_-
> yeah thats what i did.. i probably did it wrong, but it worked.

hehehe, u only need to update the opcodes in a new file acording to the new protocol: protocol.344300.map

**Comment by ViralDoom** [comment]
> i think NA got new opcode, 344300

yup, u need to put those opcodes in a new file: protocol.344300.map

**Comment by MeongMeongMeong** [comment]
Do you have the opcodes for NA S_STORE_BASKET ?
i cant seems to find them, thx

**Comment by yl2401** [comment]
An error happened:

> Error: [dispatch] hook: unmapped packet "S_FISHING_BITE"
>     at Dispatch.createHook (R:\Games\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:233:23)
>     at Dispatch.hook (R:\Games\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:301:21)
>     at Module.hook (R:\Games\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:87:32)
>     at new autoFishing (R:\Games\CaaliTeraProxy\mods\auto-fishing\index.js:97:6)
>     at ModuleManager.load (R:\Games\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:157:35)
>     at installedModules.forEach.mod (R:\Games\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:57:22)
>     at Map.forEach (<anonymous>)
>     at ModuleManager._loadAll (R:\Games\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:55:31)
>     at Dispatch.ModuleManager.dispatch.on (R:\Games\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:18:45)
>     at Dispatch.emit (events.js:182:13)

**Comment by kyogo123** [comment]
S_CAST_FISHING_ROD = 51817
C_CAST_FISHING_ROD = 27871
S_FISHING_BITE = 42148
S_START_FISHING_MINIGAME = 31252
C_START_FISHING_MINIGAME = 41826
C_END_FISHING_MINIGAME = 32911
S_FISHING_CATCH = 51796
S_FISHING_CATCH_FAIL = 49606
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 24833
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 62602
S_RP_COMMIT_DECOMPOSITION_CONTRACT = 22175
C_STORE_SELL_ADD_BASKET = 49467
S_STORE_BASKET = 27932
C_STORE_COMMIT = 27153

These seem to be working well for me.  These are NA opcodes. I included the ones needed to sell fishes.

**Comment by Niacinamine** [comment]
how do you get to trigger S_STORE_BASKET ? it's always the one i can't find. I've been selling different items to different merchants and i never get it.

**Comment by kyogo123** [comment]
> how do you get to trigger S_STORE_BASKET ? it's always the one i can't find. I've been selling different items to different merchants and i never get it.

If you use his packet logger(https://github.com/SoliaRdi/PacketsLogger) you need to add hexy from here(https://github.com/beng-mods/opcodes-4-dummies) then you'll be able to see log all the actions you do in Tera. The file will be in your proxy folder and it will be named, "tera-log". After you open the merchant window just put stuff in the sell tab and then sell it. If you go back to your "tera-log"  the S_STORE_BASKET triggers after the C_STORE_SELL_ADD_BASKET. They appear as 'null' in the "tera-log" for some reason after the new patch. Last patch it did show "C_STORE_SELL_ADD_BASKET" so that's how you could find the S_STORE_BASKET easier. You'll see (id 49467) null , which is "C_STORE_SELL_ADD_BASKET" and right after it there should be (id 27932) null, which is "S_STORE_BASKET". No one really explains it in detail so I had a hard time finding it too since there really is no clear tutorial anywhere.

**Comment by Niacinamine** [comment]
oh damn, no wonder i never saw it, thanks a lot for the explanation!

**Comment by Maaia** [comment]
I been having trouble with once inventory is full and it tries to sell/dismantle, it does that part, but then stops. so like.
1. Craft
2. Fish -> catch -> repeat
3. Inventory full
4. Starts to sell/dismantle.
5. Should repeat 1-4.
It used to do that but doesn't anymore. Any ideas?

**Comment by kyogo123** [comment]
> I been having trouble with once inventory is full and it tries to sell/dismantle, it does that part, but then stops. so like.
> 
> 1. Craft
> 2. Fish -> catch -> repeat
> 3. Inventory full
> 4. Starts to sell/dismantle.
> 5. Should repeat 1-4. It used to do that but doesn't anymore. Just dismatles/sells then stops. Any ideas?

Can you post your opcodes? Maybe they are outdated? Other than that idk what it could be.

**Comment by Maaia** [comment]
S_CAST_FISHING_ROD = 51817
C_CAST_FISHING_ROD = 27871
S_FISHING_BITE = 42148
S_START_FISHING_MINIGAME = 31252
C_START_FISHING_MINIGAME = 41826
C_END_FISHING_MINIGAME = 32911
S_FISHING_CATCH = 51796
S_FISHING_CATCH_FAIL = 49606

S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 24833
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 62602
S_RP_COMMIT_DECOMPOSITION_CONTRACT = 22175

C_STORE_SELL_ADD_BASKET = 49467
S_STORE_BASKET = 27932
C_STORE_COMMIT = 27153

**Comment by AntiScrewdriver** [comment]
@Maaia 

I have the same problem as you. Everything works, from fishing to blacklisting to crafting.
It will also dismantle the right type of fishes.

But after dismantling, the dismantle window doesn't close, it just stays there. 

At this point i will manually close the window, and click on the rod again, and everything works
as it should, untill the point where it has dismantled another batch of fishes. 
then its stuck again.

**Comment by Maaia** [comment]
Yup exactly.. Hopefully someone smarter than us can figure it out..

**Comment by SoliaRdi** [comment]
on Saturday I will look what is wrong. no access to pc now

**Comment by yl2401** [comment]
Might I ask, how to get the following opcode:
C_END_FISHING_MINIGAME
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT
C_RQ_COMMIT_DECOMPOSITION_CONTRACT
C_RQ_START_SOCIAL_ON_PROGRESS_DECOMPOSITION
C_START_FISHING_MINIGAME
S_RESULT_DECOMPOSITION
Other got, but these cannot got by alex-packet-id-finder. How can I get? Thanks.

**Comment by ArtemKovalenko** [comment]
same problem on RU server, protocol 144300 filling no working

Error: [dispatch] hook: unmapped packet "S_FISHING_BITE"
    at Dispatch.createHook (C:\Users\Artem\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:233:23)
    at Dispatch.hook (C:\Users\Artem\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:301:21)
    at Module.hook (C:\Users\Artem\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:87:32)
    at new autoFishing (C:\Users\Artem\AppData\Local\Programs\CaaliTeraProxy\mods\auto-fishing-master\index.js:97:6)
    at ModuleManager.load (C:\Users\Artem\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:157:35)
    at installedModules.forEach.mod (C:\Users\Artem\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:57:22)
    at Map.forEach (<anonymous>)
    at ModuleManager._loadAll (C:\Users\Artem\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:55:31)
    at Dispatch.ModuleManager.dispatch.on (C:\Users\Artem\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:18:45)
    at Dispatch.emit (events.js:182:13)

**Comment by Maaia** [comment]
@ArtemKovalenko 

Did you put the new protocols/defs into proxy?
node_moudles/tera_data/map

or whatever it was?

**Comment by SoliaRdi** [comment]
Still no access to PC, sorry :(

**Comment by AntiScrewdriver** [comment]
@SoliaRdi 
don't sweat it Sol =]
