### ISSUE TITLE
Freezing on Dismantle/Sell.

### ISSUE THREAD

**Issue by heckity** [SoliaRdi/auto-fishing#57]
Basically its only dismantling 20/20 or selling 8/8 and just stopping there completely on NA

heres my OPcodes

S_CAST_FISHING_ROD = 51817
C_CAST_FISHING_ROD = 27871
S_FISHING_BITE = 42148
S_START_FISHING_MINIGAME = 31252
C_START_FISHING_MINIGAME = 41826
C_END_FISHING_MINIGAME = 32911
S_FISHING_CATCH = 51796
S_FISHING_CATCH_FAIL = 49606
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 24833
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 62602
S_RP_COMMIT_DECOMPOSITION_CONTRACT = 22175
C_STORE_SELL_ADD_BASKET = 49467
S_STORE_BASKET = 27932
C_STORE_COMMIT = 27153

**Comment by SoliaRdi** [comment]
With yesterday update? dismantling completes? Dismantling window closes?

**Comment by cybrwolf** [comment]
Having pretty much the same issue, open dismantle box, dosent put anything in, and stop there, auto-sell is working perfectly

**Comment by rayted-r** [comment]
dismantle works most of the time. sometimes doesn't close the window after dismantle. auto sell crashes game/proxy entirely.
says [dispatch] handle: error running hook for S_DIALOG<2>
with a bunch of area/location stuff and then
[dispatch] handle: error running hook for S_REQUEST_CONTRACT<1>
both also have "TypeError: Cannot read property 'contractId'" of null at the bottom

**Comment by SoliaRdi** [comment]
How to reproduce your error? I don't have any problem. Fishing working 24\7

**Comment by rayted-r** [comment]
using vexatus swamp npc. it gets to 2 free spaces left, then attempts to sell but crashes the proxy. config resets "selltonpc": true to false on crash. contdist I have changed from 5-8 still does not fix. using pinki prox.

different error this time and in red text
mods\auto-fishing\index.js:658
                                id: currentSeller.contractId
TypeError: Cannot read property 'contractId' of null
 at endSelling (\mods\auto-fishing\index.js:658:23)
    at Timeout.setTimeout [as _onTimeout] (mods\auto-fishing\index.js:706:5)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)

**Comment by SoliaRdi** [comment]
Npc contact window was opened?

**Comment by rayted-r** [comment]
ok I think I found the fix. I would say a bunch of defs got modified. 1 was also missing. replaced all defs with the provided ones and now everything works, no crash. also reset my config file just in case. now if only we can auto buy bait 1 from the merchant...
