### ISSUE TITLE
fish setbait ?

### ISSUE THREAD

**Issue by jrfrankenstein** [SoliaRdi/auto-fishing#58]
I for the life of me cant get fish setbait to work it keeps saying incorrect item id am I supposed to mod some file or something ??

I start with 
Fish which starts mod 
then I craft bait iv 
then type fish setrecipe (this sets bait iv)
Then Ive tried fish setbait link 
                       fish setbait 206003
                       fish setbait link 206003 
all come back incorrect item id 
Im pulling my hair out please help !

**Comment by SoliaRdi** [comment]
Read hint

**Comment by jrfrankenstein** [comment]
> Read hint

Hi I really have I still don't get what it means ive tried activating bait and all sorts do I need to find some other program to find id ?

**Comment by rayted-r** [comment]
ctrl + left click puts item in the chat
so it looks like
fish setbait <Bait IV>
you dont put the item id# in there. the item that you ctrl click in the chat should also be clickable by you before you hit enter.

**Comment by jrfrankenstein** [comment]
ok ty  for simple explanation ray that was all i needed thanks a lot .

> ctrl + left click puts item in the chat
> so it looks like
> fish setbait <Bait IV>
> you dont put the item id# in there. the item that you ctrl click in the chat should also be clickable by you before you hit enter.
