### ISSUE TITLE
add delay for minigame :thonk: 2 sec ~

### ISSUE THREAD

**Issue by Unkn01w** [SoliaRdi/auto-fishing#6]

**Comment by SoliaRdi** [comment]
Or increase the time from the difficulty level

**Comment by SoliaRdi** [comment]
I add option to config

**Comment by Unkn01w** [comment]
Oki nice works mate love on you

**Comment by Unkn01w** [comment]
Tryed with 5sec, its working fine 💯

**Comment by SoliaRdi** [comment]
pushed update with /8 fish setdelay
