### ISSUE TITLE
Selling fishes to npc not working 

### ISSUE THREAD

**Issue by Prodemozai** [SoliaRdi/auto-fishing#61]
It open up the shop and put one fishes in the sell basket and then stuck there.Hope you can help me solve this.

**Comment by SoliaRdi** [comment]
Looks like wrong S_STORE_BASKET opcode. idk your region

**Comment by Prodemozai** [comment]
Hmm now it put fishes into it but does not sell it what opcode is wrong for that.Much appreciate for ur help.

**Comment by Prodemozai** [comment]
nvm i found it is my C_STORE_COMMIT opcode wrong thanks for the help :)
