### ISSUE TITLE
Banking fish 10000 filet error?

### ISSUE THREAD

**Issue by trev44** [SoliaRdi/auto-fishing#64]
/8 fish filetmode bank 5000
Set to bank 5000 files after filling inventory
 C_PUT_WARE_ITEM not mapped, banker functions for auto-fishing will now be disabled.

my config is as follows:

	"delay": 6000,
	"contdist": 6,
	"blacklist": [
	        206500,
		206501,
		206502,
		206503,
		206504,
		206505
	],
	"bait": 206001,
	"recipe": 204100,
	"autosalad": true,
	"bankAmount": 5000,
	"filetmode": false

am i doing something wrong?

**Comment by SoliaRdi** [comment]
C_PUT_WARE_ITEM not mapped, banker functions for auto-fishing will be disabled!

**Comment by SoliaRdi** [comment]
Somehow i missed this opcode on eu

**Comment by SoliaRdi** [comment]
Fixed. Update protocol.344301.map
