### ISSUE TITLE
fishing keep cancel after a few minute of fishing

### ISSUE THREAD

**Issue by Prodemozai** [SoliaRdi/auto-fishing#65]
today i get a weird problem.First when i type fish in the proxy it open inventory and it will fish as usual but after awhile it will stop fishing.

**Comment by SoliaRdi** [comment]
I need more info. Today i dont get any weird problem

**Comment by Prodemozai** [comment]
is it normal when i enable the mob and it will open up my inventory?

**Comment by SoliaRdi** [comment]
Yes, why not?

**Comment by Prodemozai** [comment]
thanks for the info
