### ISSUE TITLE
{Error: Cannot find module 'moment' . Was working yesterday, stopped working after today's update.

### ISSUE THREAD

**Issue by AntiScrewdriver** [SoliaRdi/auto-fishing#67]
![image](https://user-images.githubusercontent.com/47073195/54246835-6ba91000-459b-11e9-9a2f-4aee39911551.png)

I got this error today. Yesterday night it was working fine, woke up today after the update, and got this error, anyone know whats up ?

**Comment by SoliaRdi** [comment]
Caali proxy?

**Comment by SoliaRdi** [comment]
Just checked fresh install. Its default module in CaaliTeraProxy\node_modules

**Comment by AntiScrewdriver** [comment]
Thanks for the help Sol. You're right, it works in Caali proxy.

That error came from Pinkie's Proxy. Maybe he changed something in the proxy overnight.

**Comment by SoliaRdi** [comment]
most likely it just not installed by default

**Comment by SoliaRdi** [comment]
You can download it from https://registry.npmjs.org/moment/-/moment-2.20.0.tgz and extract package folder to node_modules(where tera-data folder and other)\moment (create this folder)

**Comment by AntiScrewdriver** [comment]
![cannot find moment](https://user-images.githubusercontent.com/47073195/54313346-035f3a80-463e-11e9-968c-bb7873402db7.jpg)

It works ! thanks Sol ! Made a small picture guide ... too much time at work.
