### ISSUE TITLE
node_modules\tera-data does not exist

### ISSUE THREAD

**Issue by sichtbar3333** [SoliaRdi/auto-fishing#68]
you told "Move defs to node_modules\tera-data\protocol" but i cant find node_modules\tera-data on my pc

**Comment by cybrwolf** [comment]
DRIVE:\PROXYDIR\node_modules\tera-data\protocol

**Comment by sichtbar3333** [comment]
sady cant find this to..maby its called diffrent cuz my pcs launguage is not english

**Comment by sichtbar3333** [comment]
i downloaded it via steam if that can be the issue to..idk

**Comment by cybrwolf** [comment]
First of all, this is an addon for Tera Proxy,  those files need to be moved in the appropriate proxy folder, not into game folder, i suggest you to do some reading regarding CaliiProxy or Pinky Proxy in the first place.

**Comment by sichtbar3333** [comment]
well okay thx
