### ISSUE TITLE
Item ID

### ISSUE THREAD

**Issue by Niacinamine** [SoliaRdi/auto-fishing#7]
getting "incorrect item id" using Fish and Bait ID from Teralore.com or item-id-finder and trying to use "fish setrecipe"

**Comment by SoliaRdi** [comment]
Use chat links for adding fishes and bait from chat. fish setrecipe - manually craft bait once and then use command. Or just manually edit config.json. {
	"items": [
		206400,
		206402,
		206404,
		206406,
		206408,
		206411
	],
	"recipe": 204100,
	"bait": 206001,
	"delay": 2000
}
