### ISSUE TITLE
fish selltonpc vexatus swamp not work? EU

### ISSUE THREAD

**Issue by trev44** [SoliaRdi/auto-fishing#70]
i see there is a closed issue about this: [Sell to NPC suggestion #43]

/8 fish selltonpc 

im within [pressing the use key] range while fishing but it says: warning no seller np at acceptable range.
it just proceeds with dismantling anyway.

if you are fishing on auto for a long time, you cant keep up with buying monti summonable npc's etc. needing like at least 20 per day, and there aren't even 10 in the broker...
The fishing supplies guy standing reasonably close the the water at Vexatus swamp fishery.
He is in range of 6 meters all the time. Can you not make it so it sells to that permanent npc.
Fish can be sold to him.
the npc's name for eu atleast is "Tanysilain".

**FOR PEOPLE THAT USE AUTO-FISHER>>>**
reason i bring this up is because if you on a high tier fishing rod, auto-fishing for 15 hours etc. you can make up to perhaps 50k gold by using this easy permanent npc. (through the night and while at work)

this gold is better than selling fish steak buff because you don't need to go gather cobseed for it...

Appreciate this auto-fisher so much. you are the boss kind sir!

**Comment by SoliaRdi** [comment]
?_?. I never sell fish steak. It works but for added npc's. Rn only [this](https://teralore.com/en/npc/000619906/?sl=1) and [this](https://teralore.com/en/npc/000619903/?sl=1). Btw on RU i have about 10k scrolls

**Comment by trev44** [comment]
so right now you saying it does work? im trying and warning no seller np at acceptable range.
it just proceeds with dismantling anyway?

am i doing something wrong?

/8 fish selltonpc

**Comment by SoliaRdi** [comment]
It work. Give me your config

**Comment by trev44** [comment]
should it say "sell to npc instead using scrolls disabled" ?

{
	"delay": 6000,
	"contdist": 6,
	"blacklist": [
		206500,
		206501,
		206502,
		206503,
		206504,
		206505
	],
	"bait": 206001,
	"recipe": 204100,
	"autosalad": true,
	"bankAmount": 9000,
	"filetmode": "bank"
}

it didnt add anything once i saved>

**Comment by SoliaRdi** [comment]
New config files has your nickname in file name. First you type fish sellfishes, then fish selltonpc 6 (Like in readme: fish selltonpc range | Option for fish sellfishes)

**Comment by trev44** [comment]
OHHHH you literally have to say 6. ty i'll test now! ty for your patients :)

**Comment by trev44** [comment]
we works. all the best to you sir !
