### ISSUE TITLE
Banking not working

### ISSUE THREAD

**Issue by tsutemaki** [SoliaRdi/auto-fishing#71]
After reaching the maximum amount of fishfilet the module tries to dismantle, I get the message I can't hold any more filet and instead of banking the filet I have nothing happens. I don't get any further error messages or anything, neither ingame nor in the proxy window. I'm standing at a place where a banker can be used, I have one in my inventory and can manually use it and bank the items. The config file for the char in question is: 
`{
	"delay": 3000,
	"contdist": 6,
	"blacklist": [],
	"bait": 206004,
	"recipe": 204103,
	"bankAmount": 9000,
	"filetmode": "bank",
	"autosalad": true
}`
Any idea what the problem might be? It worked until recently and I can't recall having changed anything.

**Comment by tsutemaki** [comment]
Never mind, apparently I got an error in the proxy window, it reads as follows:

```
[dispatch] handle: error running hook for S_REQUEST_CONTRACT<1>
hook: (anonymous) in auto-fishing
data: { senderId: 72198331528127944n,
  recipientId: 0n,
  type: 26,
  id: 1111384,
  unk3: 0,
  time: 0,
  senderName: '[...]',
  recipientName: '',
  data: <Buffer > }
error: Cannot set property 'contractId' of null
    at Object.mod.hook.event [as callback] (C:\Users\[...]\AppData\Local\Programs\CaaliTeraProxy\mods\auto-fishing-master\index.js:287:30)
[dispatch] handle: error running hook for S_CANCEL_CONTRACT<1>
hook: (anonymous) in auto-fishing
data: { senderId: 72198331528127944n,
  recipientId: 0n,
  type: 26,
  id: 1111384 }
error: Cannot read property 'contractId' of null
    at Object.mod.hook.event [as callback] (C:\Users\[...]\AppData\Local\Programs\CaaliTeraProxy\mods\auto-fishing-master\index.js:307:62)
[dispatch] handle: error running hook for S_REQUEST_CONTRACT<1>
hook: (anonymous) in auto-fishing
data: { senderId: 72198331528127944n,
  recipientId: 0n,
  type: 26,
  id: 1112991,
  unk3: 0,
  time: 0,
  senderName: '[...]',
  recipientName: '',
  data: <Buffer > }
error: Cannot set property 'contractId' of null
    at Object.mod.hook.event [as callback] (C:\Users\[...]\AppData\Local\Programs\CaaliTeraProxy\mods\auto-fishing-master\index.js:287:30)
[dispatch] handle: error running hook for S_CANCEL_CONTRACT<1>
hook: (anonymous) in auto-fishing
data: { senderId: 72198331528127944n,
  recipientId: 0n,
  type: 26,
  id: 1112991 }
error: Cannot read property 'contractId' of null
    at Object.mod.hook.event [as callback] (C:\Users\[...]\AppData\Local\Programs\CaaliTeraProxy\mods\auto-fishing-master\index.js:307:62)
```
What have I done wrong?

**Comment by SoliaRdi** [comment]
This errors appear when you contact manually? Banker spawns and then nothing happen?

**Comment by tsutemaki** [comment]
No, they happen when the banker should be summoned by the module
The module doesn't summon a banker and my char just sits there doing nothing from this point on

**Comment by SoliaRdi** [comment]
There is no trigger if no summoned banker. Dk how this errors can happen. So banker scroll just not being used?

**Comment by tsutemaki** [comment]
Exactly, sorry if I didn't clarify it enough. As soon as the filet limit is reached and the filet should be banked the Phargo scroll is not used and nothing happens from that point on

**Comment by SoliaRdi** [comment]
Ok idk rn. What difference beetween character where mod can use scrolls?

**Comment by tsutemaki** [comment]
The one that doesn't work is a lancer with Angle Whiskers X and Smelting master
The other one I tried is a Sorc with Angle Whiskers IX and Smelting master

Not sure what else to say. Thinking back I think I had a similar issue with this char with some other module a long time ago, but can't remember how I got rid of it...

**Comment by tsutemaki** [comment]
Ok, I tried it again and it seems the messages in the proxy window came from something different. Not summoning phargo doesn't produce any error messages. Also, if I just manually click on the banker scroll it works and the mod continues doing what it's supposed to do.

**Comment by SoliaRdi** [comment]
Is there any new information?
