### ISSUE TITLE
Need help, ho to finding id

### ISSUE THREAD

**Issue by edhe15** [SoliaRdi/auto-fishing#72]
I need somne to tell me how to find id, exmple: S_CAST_FISHING_ROD = ...

i tried using id finder, but dint work.. ty

**Comment by SoliaRdi** [comment]
Ohh, you don't need this opcode. S_CAST_FISHING_ROD wasn't in manifest.json. I'll exclude it from next opcodes, it was added in first versions and I just forgot to put it away.
