### ISSUE TITLE
auto-fish if character somehow has stopped and is idle?

### ISSUE THREAD

**Issue by trev44** [SoliaRdi/auto-fishing#73]
just curious if there is any contingency to continue auto-fishing if for some reason after few hours my character has just stopped fishing ? like to start fishing if character is idle for more than 20 minutes or something?

inventory is not full and everything works fine too.

**Comment by SoliaRdi** [comment]
Reason is network issues or what? You can type /8 fish printdebug for some additional info. And there no any errors in game chat?

**Comment by trev44** [comment]
network is fine. normally if dc, would have to relog to server anyway.
no errors in chat no.
i was just wondering if character is just standing idle, that auto-fishing can start again without coming back to manually /8 fish start it again

**Comment by SoliaRdi** [comment]
It possible, but no reason to do this since bot shouldn't stopped.

**Comment by trev44** [comment]
alright. im guessing you never had this problem maybe?
thanks anyway

**Comment by SoliaRdi** [comment]
Yes. Check next time system messages, like "you can't do this" or "fishing canceled". Maybe other mod trying to do smth and block rod

**Comment by trev44** [comment]
Ive found that /8 fish setdelay 10000-12000 helps alot too with fishing canceling

**Comment by SoliaRdi** [comment]
This delay only for minigame. I'll do rod delay configurable soon

**Comment by SoliaRdi** [comment]
This delay only for minigame. I'll do rod delay configurable soon
