### ISSUE TITLE
Stuck at NPC to sell fish

### ISSUE THREAD

**Issue by edhe15** [SoliaRdi/auto-fishing#75]
Sorry for my bad english.

I alLredy got S_STORE_BASKET using packetlogger link u give without hexy :).
My character put all fish at npc, but just like that, didnt sell it. wich part i missing?

Stopped after dismantle fish too.

**Comment by edhe15** [comment]
![123](https://user-images.githubusercontent.com/48638947/54652019-d6040800-4ae7-11e9-8239-62bce375fc33.jpg)

**Comment by SoliaRdi** [comment]
Most likely incorrect C_STORE_COMMIT opcode

**Comment by edhe15** [comment]
Did i make mistake using packet logger?  hahha
I'll tell u if this time work.

![123](https://user-images.githubusercontent.com/48638947/54666574-ac190880-4b1c-11e9-9591-d8a08edf28dc.jpg)

**Comment by edhe15** [comment]
Owh, its work well now....

Ty so much, ur so nice person. 👍
