### ISSUE TITLE
Not all Npc Work to sell?

### ISSUE THREAD

**Issue by teraoo** [SoliaRdi/auto-fishing#76]
tera EU  npc @Seren's Lake  not Work since update ?!

**Comment by SoliaRdi** [comment]
Link to npc. Yes, not all

**Comment by teraoo** [comment]
https://teralore.com/en/npc/002309903/?sl=1

**Comment by SoliaRdi** [comment]
Actually should work

**Comment by teraoo** [comment]
Ty for fast answer. WicH code Must I change?!

**Comment by SoliaRdi** [comment]
Not you :D

**Comment by teraoo** [comment]
Okay xD

**Comment by teraoo** [comment]
You make a nice update xnet time?

**Comment by SoliaRdi** [comment]
Sadly, i'm just too lazy. Playing ffxiv rn. As temporary solution change location or make that needed seller appear last. Maybe on weekend =_=
