### ISSUE TITLE
Randomly stops fishing.

### ISSUE THREAD

**Issue by Poohtatoe** [SoliaRdi/auto-fishing#77]
All's working fine except it randomly stops after fishing for several hours.

**Comment by trev44** [comment]
This is what im talking about too...
If you check the system messages, you will find that it said fishing
canceled somewhere along the line.
SoliaRrdi says it could be other mods like fish salad or everful nostrum
kicking in every 30 min that is interfering etc.
But ive switched those mods off.
Sometimes im fishing in 2 chars 2 separate accounts. Ill be actively
gathering something on one char and sometimes when i look at the other char
fishing ive found he has stopped fishing and "fishing canceled" a little
bit up in the chat.
There needs to be something else that will start auto fishing if character
is idle for more than.. for example 5 minutes, even less.
I dunno thats just my take on it.

**Comment by SoliaRdi** [comment]
"fishing canceled" is client lag - 99%. I can increase delay for 1 more second, or ok, make idle checks

**Comment by trev44** [comment]
making idle checks would be great! would i have to download the auto-fisher again if this was to be implemented?

**Comment by trev44** [comment]
Ive found that /8 fish setdelay 10000-12000 helps alot too with fishing canceling
