### ISSUE TITLE
Cant log in

### ISSUE THREAD

**Issue by kamusan** [SoliaRdi/auto-fishing#78]
while fishing with bot it dced me and cant log in to character it stays on character selection

**Comment by SoliaRdi** [comment]
Any errors in console?

**Comment by kamusan** [comment]
it happened while dismantling fishes it stopped after few fishes dismantled and character stopped playing but i could see other peoples moves (no errors at console)

**Comment by SoliaRdi** [comment]
Сan you login without proxy or can you login with another char?

**Comment by kamusan** [comment]
i can log in my other chars in same account with proxy or without proxy i play at eu

**Comment by SoliaRdi** [comment]
So after few fishes added to dismantle window?

**Comment by kamusan** [comment]
it stopped adding fishes to dismantle list and i tried to add myself and i realised that i couldnt press anything i could only move and open ingame ui but when i click something nothing happened and i restarted game i tried to log in but when i select the character it just stops and doesnt allow me to select any other character

**Comment by SoliaRdi** [comment]
Ok, got it. Still don't know how this possible, but at least know direction. Probably you need to wait maint, if it what i think. Sadly can't help right now and this case very rare
