### ISSUE TITLE
Occasional Error and Server Disconnect

### ISSUE THREAD

**Issue by ap0521** [SoliaRdi/auto-fishing#79]
![43R8BKb](https://user-images.githubusercontent.com/48301387/54889362-94be8000-4e7a-11e9-8586-e639e917258a.png)

Had it happen a few times, sometimes when not even fishing.

**Comment by SoliaRdi** [comment]
So this happen during fishing or when you try doing something?

**Comment by ap0521** [comment]
It has happened during fishing and also while I was not fishing and just in highwatch.

**Comment by SoliaRdi** [comment]
Mod was disabled?

**Comment by ap0521** [comment]
That crash was when mod was disabled, but I also had a similar disconnect while fisher was running.

**Comment by SoliaRdi** [comment]
With same text error and line? Don't know how mod.game become undefined during game. Show module list =_=

**Comment by ap0521** [comment]
It is quite rare issue, only has happened 3 or so times in few weeks, so might also just be proxy issue.
![wCcoFYt](https://user-images.githubusercontent.com/48301387/54897557-4f607980-4e9f-11e9-92a0-0c95acef1e7a.png)
