### ISSUE TITLE
autofishing problem?

### ISSUE THREAD

**Issue by kath19x** [SoliaRdi/auto-fishing#81]
Do I have to constantly press F for his mod?  Cause after the initial casting of rod, it always requires me to press F to get the bite then it will auto capture the fish and auto cast the rod again, then ask me again to press F.  It seems automatic except for the part "You got a bite! Press F key to see what it is" 

Tera SEA

**Comment by SoliaRdi** [comment]
You wrote in time. Almost added yours opcodes. No you don't have to. So issue here is wrong opcodes

**Comment by kath19x** [comment]
I'm trying to map the opcodes one by one right now :(.  I was wondering why does this mod need opcodes while the other mod I used for fishing does not?  

Anyway This is what I got so far for TERA SEA opcodes:
C:\USER\Tera SEA\CaaliTeraProxy\node_modules\tera-data\map
file name "protocol.344305"

S_FISHING_BITE = 33881
S_START_FISHING_MINIGAME = 26026
S_FISHING_CATCH = 54645
S_FISHING_CATCH_FAIL = 62938
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 41461
C_START_FISHING_MINIGAME = 30163

**Comment by SoliaRdi** [comment]
Because more functions?

**Comment by kath19x** [comment]
Ok I'm done getting the opcodes in Tera SEA.  So far it is working fine as of march 27, 2019
Selling in npc: "Tanysilain"
Fishing area: Vexatus
File Location: C:\USER\Tera SEA\CaaliTeraProxy\node_modules\tera-data\map
File name: protocol.344305

S_FISHING_BITE = 33881
S_START_FISHING_MINIGAME = 26026
S_FISHING_CATCH = 54645
S_FISHING_CATCH_FAIL = 62938
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 41461
C_START_FISHING_MINIGAME = 30163
C_END_FISHING_MINIGAME = 40715
C_STORE_SELL_ADD_BASKET = 20997
C_STORE_COMMIT = 31328
S_STORE_BASKET = 56314
