### ISSUE TITLE
Fishing work but other dont

### ISSUE THREAD

**Issue by Prodemozai** [SoliaRdi/auto-fishing#85]
fishing work but wont auto craft bait and dismantle fillet got problem it show dont have enough inventory and also say you are busy.

**Comment by SoliaRdi** [comment]
I don't have such issues. Give more details, current mode. You busy on which step?

**Comment by Prodemozai** [comment]
busy on dismantle fishes and i think it need update def.

**Comment by SoliaRdi** [comment]
So you have errors in console?

**Comment by Prodemozai** [comment]
yes iven one many code very laggy on the log

**Comment by Prodemozai** [comment]
i know you are updating the inven so will see how after you update. TQ

**Comment by Prodemozai** [comment]
dismantle work now but very weird it put many fishes into it then cancel the window then open the dismantle window and dismantle only a few fishes. Wont auto craft bait also.

**Comment by SoliaRdi** [comment]
Any errors?

**Comment by Prodemozai** [comment]
contract id error

**Comment by Prodemozai** [comment]
that is sell fishes one i need to find the right opcode but the dismantle and bait wont autocraft dosent show error at all

**Comment by SoliaRdi** [comment]
As i say before, give more detail. I'm not psychic.

**Comment by Prodemozai** [comment]
SEA

**Comment by Prodemozai** [comment]
i try redo the opcode and see how it work .sorry

**Comment by SoliaRdi** [comment]
I see a lot of wrong opcodes from here. You should be careful.

**Comment by Prodemozai** [comment]
i still dont understand why cant craft bait after bait finish.

**Comment by SoliaRdi** [comment]
Do you have enough fish fillets?

**Comment by Prodemozai** [comment]
yes

**Comment by SoliaRdi** [comment]
Do you have correct bait\recipe in config?

**Comment by Prodemozai** [comment]
yes checked many times

**Comment by SoliaRdi** [comment]
Try fish printdebug

**Comment by Prodemozai** [comment]
Debug log
[21:44:47.538] bankerUsed=false
[21:44:47.567] sellerUsed=false
[21:44:47.617] scrollsInCooldown=false
[21:44:47.647] noItems=true
[21:44:47.690] needToDecompose=true
[21:44:47.724] needToBankFilets=false
[21:44:47.751] needToSellFishes=false
[21:44:47.780] needToCraft=false
[21:44:47.807] needToDropFilets=false
[21:44:47.834] invFishes count=0
[21:44:47.860] sellItemsCount=0

**Comment by SoliaRdi** [comment]
So here we go. 0 Fishes and no filets

**Comment by Prodemozai** [comment]
fishes 0 is true cause all get dismantle but fillet i got 800

**Comment by SoliaRdi** [comment]
Flags refreshed when you disable\enable mod. Do you dismantle all of them manually?

**Comment by Prodemozai** [comment]
after inventory full it auto dismantle but when bait finish it search for inventory if got some fish to dismantle then dismantle then stopped.

**Comment by SoliaRdi** [comment]
Idk, maybe sysmsg is blocked by other mod, maybe anything else. Did mod ever work for you? You can use alternative - https://github.com/Lambda11/let-me-fish

**Comment by Prodemozai** [comment]
yes it work very well every time just this time bait wont auto craft first time get this problem

**Comment by SoliaRdi** [comment]
Try relog. If problem persist, check def for C_START_PRODUCE with logger. If still same result wait EU server maintenance

**Comment by Prodemozai** [comment]
Probably i dont know. Thank you for your patient :)
