### ISSUE TITLE
updated opcode and still does not work in Tera SEA

### ISSUE THREAD

**Issue by kath19x** [SoliaRdi/auto-fishing#86]
I already got the new op code for S_FISHING_BITE = 29236 and it used to work before the patch and now new code after the patch but I still get the error 
--------------------------------------
[mods] ERROR: Module "auto-fishing" could not be loaded!
[22:54:09.932] [mods] ERROR: Please contact the module's author: https://github.com/SoliaRdi/auto-fishing
[22:54:09.933] Error: [dispatch] hook: unmapped packet "S_FISHING_BITE"
-------------------------------------

this is the log for the new OPCODE and it still does not work
22:56:01.609] Candidates for id 29236: [S_FISHING_BITE].
[22:56:01.615] 29236 as S_FISHING_BITE:
[22:56:01.621] {
    "rodId": 206702,
    "gameId": "140737488424013",
    "unk1": "180000"
}

Any SEA  player out there who can help me?  I already reinstalled the mod, got all the OPCODES manually after the patch.  Still does not work in SEA server.  It was working  fine before the patch fyi

**Comment by SoliaRdi** [comment]
unmapped packet means not added to opcodes file.

**Comment by SoliaRdi** [comment]
Your issue doesnt related to 80 patch

**Comment by kath19x** [comment]
Yes I added it to "protocol.344305" for SEA like I used to last time,  I got it to work already before the patch, I'm already trying to solve the selling to npc part last time then the new patch hits and everything seem to not work anymore on my server

**Comment by kath19x** [comment]
do I have to change something else after the patch aside from the opcodes?

**Comment by flytomoon88** [comment]
patch 80 is not protocol.344305, it should be protocol.345891.map

**Comment by kath19x** [comment]
Ohhh so it changes every patch.  I thought it is constantly "protocol.344305" that you have to edit.  Thank you very much, that helped a lot. 

As reference for others the protocol that you have to edit and put your new opcodes can be found in "mappings.json" inside tera-data folder.  It depends per server and again changes every major  patch it seems.  Thanks again

**Comment by kath19x** [comment]
Fyi there are the new opcodes that I got for Tera SEA
These are my opcodes:
S_FISHING_BITE = 29236
S_START_FISHING_MINIGAME = 57576
S_FISHING_CATCH = 61637
S_REQUEST_CONTRACT = 25729
C_RQ_COMMIT_DECOMPOSITION_CONTRACT = 28456
C_RQ_START_SOCIAL_ON_PROGRESS_DECOMPOSITION = 39925
S_FISHING_CATCH_FAIL = 26569
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 46411
C_START_FISHING_MINIGAME = 58013
C_END_FISHING_MINIGAME = 50168
C_STORE_SELL_ADD_BASKET = 60107
C_STORE_COMMIT = 59186
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 53131
