### ISSUE TITLE
Dosen't craft bait anymore

### ISSUE THREAD

**Issue by Bo7-Benamor** [SoliaRdi/auto-fishing#87]
Dosen't craft bait anymore after patch 80. it keeps fishing until bait is over than it stops there. no error messages

**Comment by SoliaRdi** [comment]
Ok, wait update.

**Comment by Bo7-Benamor** [comment]
i think the problem is in this code:

if (message.id == 'SMT_CANNOT_FISHING_NON_BAIT') {
				needToCraft = true;
				startCraft();

after update, when bait is over we no longer have error message, it just stops and game dosent tell you that you don't have enough bait.

**Comment by SoliaRdi** [comment]
I know

**Comment by SoliaRdi** [comment]
Should work. Write if you have any problems
