### ISSUE TITLE
Dismantling not run correct

### ISSUE THREAD

**Issue by herowinb** [SoliaRdi/auto-fishing#88]
I have problem with Dismantling, i think my opcode is correct so it can auto dismantle but it only dismantle 3-8 fishes and stop.
![image](https://user-images.githubusercontent.com/8396689/55174256-ad4ad500-51af-11e9-8b8a-c70b7f788265.png)
Log:
![image](https://user-images.githubusercontent.com/8396689/55174127-74126500-51af-11e9-8773-73cb383dac3b.png)

**Comment by SoliaRdi** [comment]
![2019-03-28_19-30-07](https://user-images.githubusercontent.com/34610562/55175221-ebd09780-518f-11e9-938d-031bd3d1dc35.png)

**Comment by SoliaRdi** [comment]
Actually this is another error. So if after update it happen again we will return to this =(

**Comment by SoliaRdi** [comment]
Should work. Write if you have any problems

**Comment by herowinb** [comment]
It not work :(

Full inventory -> Open Dismantle dialog -> Input 20 Fishes -> **Not Dismantle 20 fishes -> clear Dismantle dialog** -> Input more fish (3-8 fishes) -> Dismantle success -> Cancel Dismantle -> Continue Fishing -> 10s later cancel Fishing and stop all.

**Comment by Prodemozai** [comment]
same dismantle getting the same problem

**Comment by SoliaRdi** [comment]
Well, wait 1-2 days untill i rewrite mod

**Comment by Fatalfuryy** [comment]
well i have still the same issue, when my inventory gets full it starts dismentling, opens the dismentle window but after it put fishes there, turn them back to inventory without dismentling and stop fishing. do you know anything like this ?

**Comment by herowinb** [comment]
> 
> 
> Well, wait 1-2 days untill i rewrite mod

And selltonpc function not work anymore :(

**Comment by trev44** [comment]
i have the same issue dismantling just to let you guys that having trouble too

**Comment by kath19x** [comment]
same problem, cant dismantle and sell to npc

**Comment by SoliaRdi** [comment]
I'll close all issues related to old version
