### ISSUE TITLE
Issue while crafting bait

### ISSUE THREAD

**Issue by Sevih** [SoliaRdi/auto-fishing#89]
When running out of bait, the character open craft window and craft then keep trying to craft after  reaching the 60 limit of bait.

**Comment by SoliaRdi** [comment]
Did you have any abnormality blocker?

**Comment by Sevih** [comment]
I don't think

**Comment by redshooter14** [comment]
Same problem here.
We will have to wait for the fix (for this and the dismantling problem too)

**Comment by totallynotmandy** [comment]
same problems, cant craft cant dismantle

**Comment by SoliaRdi** [comment]
I'll close all issues related to old version
