### ISSUE TITLE
No seller npc at acceptable range

### ISSUE THREAD

**Issue by PisicaImputita** [SoliaRdi/auto-fishing#93]
Warning: no seller npc at acceptable range
I get this error only on one specific character, it works on every other character. I've tried reinstalling the module, deleting the config file, reinstalling Caali but nothing works...

**Comment by firesk1** [comment]
I'm not able to sell my fish to NPC either. Whenever my inventory gets full, my character just dismantles a few fish into fish filets, then stops fishing.

**Comment by SoliaRdi** [comment]
I'll close all issues related to old version

**Comment by PisicaImputita** [comment]
> I'll close all issues related to old version

Sell to npc instead using scrolls enabled.
Error running callback for command "fish" when I enable fish selltonpc

[command] ERROR: TypeError: Cannot read property 'distance' of undefined
    at npc.reduce (X:\Fish\mods\auto-fishing-master\index.js:1039:32)
    at Array.reduce (<anonymous>)
    at String.mod.command.add (X:\Fish\mods\auto-fishing-master\index.js:1038:9)
    at CommandBase.exec (X:\Fish\mods\command\index.js:183:16)
    at hookCommand (X:\Fish\mods\command\index.js:61:30)
    at Object.CommandBase.mod.hook.event [as callback] (X:\Fish\mods\command\index.js:71:29)
    at Dispatch.handle (X:\Fish\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:497:27)
    at Socket.RealClient.socket.on (X:\Fish\node_modules\tera-proxy-game\lib\clients\RealClient.js:38:31)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)

**Comment by SoliaRdi** [comment]
Are you sure that using latest version?

**Comment by PisicaImputita** [comment]
> Are you sure that using latest version?

Yes, did a fresh install of Caali too

**Comment by SoliaRdi** [comment]
Some stupid errors here =_=

**Comment by kath19x** [comment]
I'm getting "No seller npc at acceptable range" eventhough I'm beside him in Vexatus,  I already updated the mod and opcodes

**Comment by SoliaRdi** [comment]
Are you sure about range to npc? Link me npc from teralore, i'll check

**Comment by kath19x** [comment]
I was able to talk to the npc before with this range so I think the range is fine. Also I tested to be beside him but still same error,  

https://teralore.com/en/npc/000619903/

I'm testing it right now what will happen if my inventory gets full and I will recheck OPcode again just to make sure

**Comment by SoliaRdi** [comment]
Warning doesn't related to opcodes

**Comment by kath19x** [comment]
Well I check it just to make sure, opcodes are all updated for TERA SEA,  when inventory gets full it just says "ERROR: No seller npc found at the acceptable range.  Auto fishing deactivated.
**
C_END_FISHING_MINIGAME = 50168
C_PUT_WARE_ITEM = 50576
C_RQ_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 53131
C_START_FISHING_MINIGAME = 58013

C_STORE_COMMIT = 59186

C_STORE_SELL_ADD_BASKET = 60107

S_FISHING_BITE = 29236
S_FISHING_CATCH = 61637
S_FISHING_CATCH_FAIL = 26569
S_RP_ADD_ITEM_TO_DECOMPOSITION_CONTRACT = 46411
S_START_FISHING_MINIGAME = 57576

S_STORE_BASKET = 53098

S_REQUEST_CONTRACT = 25729
C_RQ_COMMIT_DECOMPOSITION_CONTRACT = 28456
C_RQ_START_SOCIAL_ON_PROGRESS_DECOMPOSITION = 39925
**

**Comment by SoliaRdi** [comment]
Found issue, but after relog it disappear. Give me some time to figure it out

**Comment by kath19x** [comment]
I relogged also and no more error when i type /8 fish selltonpc 6 , trying to fish again, ill see if the error will appear once inventory gets full

**Comment by kath19x** [comment]
Ok it is now communicating  with the NPC after the relog but now it is putting the fishes in and get stuck there.  C_STORE_COMMIT is updated also S_STORE_BASKET updated.  I have to manually press  OK to sell them

[20:12:51:692] ->          	 C_STORE_COMMIT    (id 59186)
[19:47:2:938] <-          	    (id 53098) S_STORE_BASKET

**Comment by SoliaRdi** [comment]
how C_STORE_COMMIT looks like in logger

**Comment by kath19x** [comment]
**
[20:19:48:888] ->          	 C_STORE_COMMIT    (id 59186)
{
    "gameId": "9652020998",
    "contract": 0
}
00000004: 06274E3F 02000000 00000000                                               .'N?........

100032e706274e3f0200000000000000
[20:19:48:889] ->          	    (id 32445) null
**

**Comment by SoliaRdi** [comment]
no, try compare this 9652020998 value with S_REQUEST_CONTRACT senderId, Are they same?

**Comment by kath19x** [comment]
[20:17:13:633] <-          	 S_REQUEST_CONTRACT    (id 25729)
{
    "senderId": "140737488444794",

**Comment by kath19x** [comment]
I have a different log like this

[20:15:34:491] -> [CRAFTED]	 C_STORE_COMMIT    (id 59186)
{
    "gameId": "140737488444794",
    "contract": 884063
}

**Comment by SoliaRdi** [comment]
You have wrong opcode

**Comment by SoliaRdi** [comment]
gameId in C_STORE_COMMIT (NOT crafted by proxy) must be same with senderId.

**Comment by kath19x** [comment]
I deleted the tera-log and got new logs, all "C_STORE_COMMIT" has contract 0.

**Comment by SoliaRdi** [comment]
Wrong, this packet always has value, loggers repelled from already provided opcodes

**Comment by kath19x** [comment]
Ok I got a new OPCODE via the other logger with fpi command

C_STORE_COMMIT = 41490

It works fine now.  Thank you.
