### ISSUE TITLE
filetmode drop?

### ISSUE THREAD

**Issue by Snake26183** [SoliaRdi/auto-fishing#96]
does it use filetmode drop by default if everything else is disabled or? what does it do when you reach 10k, also there is an issue, if you use autosalad and the salad runs out when you run out of baits it will break, it uses the salad, enables the bait, but doesnt start fishing, needs to be done manually

**Comment by SoliaRdi** [comment]
salad fixed. filetmode drop removed, if no banker mod will be disabled

**Comment by Snake26183** [comment]
so the best thing to do is just use fish deleted?

**Comment by SoliaRdi** [comment]
Why you even need this?

**Comment by Snake26183** [comment]
Well if I get 10k filets the mods stop fishing if i dont have banker or merchant scrolls, thats what you said right?

**Comment by SoliaRdi** [comment]
Yes, but if you have bank mode + fish deleter it would be unexepted result =)
