### ISSUE TITLE
rod use fail

### ISSUE THREAD

**Issue by kamusan** [SoliaRdi/auto-fishing#97]
![Untitled](https://user-images.githubusercontent.com/48852277/55281581-93dc9100-5347-11e9-9125-c090b68f81df.png)
![Untitled 1](https://user-images.githubusercontent.com/48852277/55281583-9b039f00-5347-11e9-88cb-95e67dacb0e7.png)

i got first error when using rod 
i get second error when it is gonna use rod after catch fish 
problem is its not auto using rod and stop
EU region

**Comment by SoliaRdi** [comment]
Do you have filets in inv?

**Comment by kamusan** [comment]
oh i didnt have it works now TY

**Comment by SoliaRdi** [comment]
I'll add checks for this case, forgot them
