### ISSUE TITLE
No more set bait ?

### ISSUE THREAD

**Issue by Fatalfuryy** [SoliaRdi/auto-fishing#98]
hey, as i see in the commands no more !fish setbait. or maybe it's missing

**Comment by SoliaRdi** [comment]
Yes, i removed this
Duplicate of 95#

**Comment by trev44** [comment]
yea like what is happening.. not even setdelay works ???

**Comment by SoliaRdi** [comment]
Delays in config file. No ingame settings

**Comment by trev44** [comment]
when my guy runs out of bait . nothing happens

**Comment by SoliaRdi** [comment]
hm, make fish debug

**Comment by Fatalfuryy** [comment]
Well I still don’t understand how to do it. Sorry maybe I’m a bit bad at
this I guess. How can I do that

31 Mar 2019 Paz, saat 00:16 tarihinde SoliaRdi <notifications@github.com>
şunu yazdı:

**Comment by trev44** [comment]
{
	"delay": 10000,
	"contdist": 8,
	"blacklist": [
		206500,
		206501,
		206502,
		206503,
		206504,
		206505
	],
	"bait": 206004,
	"recipe": 204103,
	"autosalad": false,
	"bankAmount": 9000,
	"filetmode": "sellfishes",
	"selltonpc": true
}

so i did fish debug
but for how long. how does it work.

nothing hapens

**Comment by SoliaRdi** [comment]
Btw old config.json gone too(I left it before for compatibility, now all configs are attached to the character). fish debug - print decision whith mod take to process. Example 
![image](https://user-images.githubusercontent.com/34610562/55282089-1ec08a00-534e-11e9-958b-82b79c0e6f8c.png)

**Comment by trev44** [comment]
its dismantling my gold fish but its blacklisted in config.

**Comment by SoliaRdi** [comment]
Did your config named {nickname}-{server}.json?

**Comment by SoliaRdi** [comment]
Found typo, nvm

**Comment by trev44** [comment]
ok ty its fixed.
it recrafts only 10 bait now. thats normal?

**Comment by SoliaRdi** [comment]
Yes, maybe add 4 cycles later.
